### ISSUE TITLE
Doc instanceTemplate

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#100]
Polymer creates ShadowDOM from the template that's inside a polymer-element. You can use the instanceTemplate method to customize how this is done.

    instanceTemplate: function(template) {
      var mySyntax = {
          getBinding: function(model, path, name, node) { ... }
      };
      return template.createInstance(this, mySyntax);
    }

Here's a slightly more complex example which may be interesting. A nested template is used and the syntax and model is set only for the nested template.

http://jsbin.com/inavuk/3/edit

**Comment by arthurevans** [comment]
Closing 0.5 bugs.
