### ISSUE TITLE
0.8 - note tokenList is gone in migration guide

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1013]
`{{ {active: isActive, fade: doFade} | tokenList }}`
->
`class$="{{computeClass(isActive,doFade)}}"`

where `computedClass` returns a space separated list of classes. In this example 'active fade' if `isActive` and `doFade` are truthy.

**Comment by katejeffreys** [comment]
To help me manage the issues in the docs repo, I will close this issue in 7 days. If you need it to stay open for some reason, please comment to that effect within 7 days.

**Comment by arthurevans** [comment]
This is the 0.5-1.0 migration guide, we should close as will-not-fix at this point.
