### ISSUE TITLE
[0.8] Migration Guide Attribute bindings clarification

### ISSUE THREAD

**Issue by chuckh** [Polymer/docs#1015]
@ebidel attribute bindings needs clarification. See bold items below. From https://www.polymer-project.org/0.8/docs/migration.html#attribute-bindings.

## Attribute bindings
In 0.5, you can bind a binary attribute value like this:

```<div hidden?="{{isHidden}}">Boo!</div>```

Where the hidden attribute is added if, and only if, isHidden is truthy. For 0.8, change this expression to **attributeName$="{{propertyName}}"**. _should this be **attributeName$="[[propertyName]]"**?_

For example:

**```<div hidden$="[[isHidden]]">Boo!</div>```**
or should this be
_**```<div hidden$="{{isHidden}}">Boo!</div>```**?_

The 0.8 version is more general-purpose: it can handle both boolean and valued attributes. The property value is serialized, just like it is for reflected properties (see Attribute serialization in the Developer guide for details).

**Comment by arthurevans** [comment]
@chuckh you're right, that should be more consistent. I'm pretty sure that attribute bindings are always one-way, so either type of annotation will have the same effect. But I'll verify and update the docs.

**Comment by chuckh** [comment]
@arthurevans thanks for updating.
