### ISSUE TITLE
[0.8] Index unsupported in binding annotation

### ISSUE THREAD

**Issue by wizawu** [Polymer/docs#1019]
[The documentation](https://www.polymer-project.org/0.8/docs/devguide/data-binding.html) states that
> String concatenation is **not** supported inside a tag

I also found the index is not supported yet.

```
<a href="[[site.links[0].href]]" target="_blank">
```

I suggest that it should be mentioned.

**Comment by arthurevans** [comment]
I believe that you can do "[[site.links.0.href]]" however. Will add this to the docs.

**Comment by arthurevans** [comment]
Documented here:

https://www.polymer-project.org/0.9/docs/devguide/data-binding.html#path-binding
