### ISSUE TITLE
core-icons link broken

### ISSUE THREAD

**Issue by bogdan-nourescu** [Polymer/docs#1020]
The page i am visiting: https://www.polymer-project.org/0.5/docs/elements/core-icon.html

The link for core-icons in this phrase "See core-icons for the default set of icons." is broken.
It now goes to 
https://www.polymer-project.org/components/core-icons/demo.html 
and should go to
https://www.polymer-project.org/0.5/components/core-icons/demo.html

**Comment by arthurevans** [comment]
Fixed in the latest site push (fixed a while ago, but the change didn't get picked up on our previous push). Better late than never!
