### ISSUE TITLE
Styles (& behavior) goofed

### ISSUE THREAD

**Issue by nevir** [Polymer/docs#1034]
Ref: https://polymer.slack.com/archives/general/p1430241861000007

> xavie: Hi everyone, I'm trying to enter to the polymer webpage ( https://www.polymer-project.org/0.5/) in firefox, but the page isn't working. Anyone has the same behavior?

> xavie: I'm running the firefox version 37.0.2, this is a screenshot

![2015-04-28_12_22_27-welcome_-_polymer-rtw1simy 1430242804](https://cloud.githubusercontent.com/assets/41373/7376212/15aff470-ed93-11e4-85d4-03aa69a61be2.png)

> xavie: i found this error: `TypeError: siteBanner is null`; and `SyntaxError: An invalid or illegal string was specified`

**Comment by arthurevans** [comment]
I can replicate this by enabling the native web components flag in about:config.

FF currently only implements custom elements, so it looks like Polymer and/or the polyfills are breaking if we have partial native support.

**Comment by arthurevans** [comment]
The short story here is that Polymer 0.5 doesn't work with FF when the webcomponents flag is turned on (I think because of the way the polyfills are structured). 

This won't be fixed for 0.5, but there's an open issue to fix it for 0.8/1.0: https://github.com/webcomponents/webcomponentsjs/issues/289

**Comment by arthurevans** [comment]
Turning off `dom.webcomponents.enabled` in FF about:config fixes this issue on the docs site. Closing this bug in favor of the WC bug cited above.

**Comment by ebidel** [comment]
Downloading polymer is pretty important...I think we should emphasize it!
