### ISSUE TITLE
Data Binding

### ISSUE THREAD

**Issue by wmleler** [Polymer/docs#1044]
My project is using Polymer quite a bit. I'm looking at moving our components over to 0.8 and I'm a bit concerned by some things.  Biggest example is Templates/Data Binding.

I wish you had a good replacement for &lt;template if=condition&gt;.  Here's an example use case, from a hierarchical tree node component in 0.5:

       <template if="{{showEmptyIcon}}">
          <core-icon id="expander"
            icon="remove"
            title="{{emptytext}}">
          </core-icon>
        </template>
        <template if="{{!showEmptyIcon}}">
          <a class="expander-anchor"
             href="javascript:void(0);"
             on-click="{{openme}}"
             tabindex="{{isParent?'0':'-1'}}">
            <core-icon id="expander"
              class="{{isParent?'':'notParent'}}"
              icon="{{open?'expand-more':'chevron-right'}}"
              title="{{open?'Collapse':'Expand'}}"
              >
            </core-icon>
          </a>
        </template>

This is for an icon to expand or collapse the tree node. Looks like this:

![screen-shot-2015-05-04-at-7 02 12-pm](https://cloud.githubusercontent.com/assets/50357/7466019/abc5ecb0-f290-11e4-9fca-07aeb572524d.png)

There are three possibilities: an icon that shows that the node has no children, an icon that shows that the node does have children and can be expanded, and an icon that shows that the children of the node are being displayed and can be collapsed. Note how we have two core-icon elements with the same id, but only one of them can be displayed at a time. So display:none is not an alternative.

Yes, we can rewrite this to work in 0.8 using computed properties and function calls, but the resulting code is much more complex and probably loses most of the speed advantage you are trying to achieve by simplifying data binding.

I'm not saying you should put "template if" back, but at least give us an equivalent alternative. And not just some vague statement (with no justification) that it is an anti-pattern.

It would also be nice to have a reasonable way to conditionally set a class name (although toggleClass might help here).

**Comment by arthurevans** [comment]
There is an experimental x-if element. Not documented yet, and soon to be renamed (and out of experimental status):

https://github.com/Polymer/polymer/blob/0.8-preview/src/lib/template/x-if.html

**Comment by arthurevans** [comment]
I apologize for the vague statement, which was my doing. What we saw was a lot of people switching a lot of stuff on and off with template if. This involves creating and destroying DOM nodes every time the condition changes. In some cases, that proved to be quite a foot gun. 

The new version behaves differently by default -- it gives you a way to create DOM lazily the first time the condition flips to true, but hides/shows it thereafter. You can also choose to  have the old behavior, if you prefer. If your site/app is memory-constrained, this may be what you want.

**Comment by wmleler** [comment]
Thanks!

**Comment by arthurevans** [comment]
The new dom-if element is now documented here:

https://oh-nine-dot-polymer-project.appspot.com/0.9/docs/devguide/templates.html#dom-if
