### ISSUE TITLE
Community link for 0.5 broken when going to Polymer (0.8) site first

### ISSUE THREAD

**Issue by jodekirk** [Polymer/docs#1047]
Goto https://www.polymer-project.org/0.8/
Then click Guides & Resources (0.5)
Then click Community

https://www.polymer-project.org/0.5/discuss.html
Link gets a 404 error.

The link should be: 
https://www.polymer-project.org/0.5/resources/discuss.html

**Comment by arthurevans** [comment]
Fixed in latest site push. Thanks for letting us know!
