### ISSUE TITLE
The official doc site always down.

### ISSUE THREAD

**Issue by longkai** [Polymer/docs#1064]
I have been interested in Polymer lately but when looking at the offciial project page, it just don' t know way, cannot load any content, it' s very disappointing.

Please fix it, thx!

**Comment by arthurevans** [comment]
I'm not aware of any recent downtime, but I know some people have experienced firewall issues.

There is an unofficial mirror at polymer china.org, however it seems to be a  few releases behind.

**Comment by longkai** [comment]
Thanks, the mirror seems a bit old-fashioned compared to 0.9.

I have access to my digtal ocean vps in usa which has no firewall and I can almost visit any site which blocked in china.

Each time ``curl https://www.polymer-project.org/`` the terminal receive empty response, but other site like google, fb, tw is ok.

**Comment by longkai** [comment]
I' m sorry for my mistake. The curl is working(it' s a 302 redirect to the vesion 0.5) but I didn' t check with the proper command option.

I can see the page now, thx!
