### ISSUE TITLE
[0.9] documentation issue - horizontal scrolling broken on code views

### ISSUE THREAD

**Issue by tjsavage** [Polymer/docs#1071]
On https://www.polymer-project.org/0.9/docs/start/quick-tour.html

some of the boxes with code do not scroll horizontally, when trying to use the scrollbars. If you select the long text in the code, you can get it to scroll.

This box doesn't work: https://www.polymer-project.org/0.9/docs/start/quick-tour.html#declared-properties

Browser info: 
Chrome (stable)
Version 42.0.2311.152 (64-bit)

**Comment by arthurevans** [comment]
Appears fixed in the new site.
