### ISSUE TITLE
polyfill behaviour description unclear/incomplete?

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#1082]
on [this](https://www.polymer-project.org/0.5/docs/polymer/styling.html#at-polyfill) page, it says that `::content` is removed, but [#3](https://www.polymer-project.org/0.5/docs/polymer/styling.html#polyfill-details) doesn't say that `::content` is removed - is that an error or is there something I'm missing?

also it says that `> *` is not valid CSS, but [#2](https://www.polymer-project.org/0.5/docs/polymer/styling.html#reformatrules) says they are prepended with the element name, so surely it then becomes something like `my-element > *` which _is_ valid?

**Comment by katejeffreys** [comment]
Sorry this didn't get a response. I'm going to close it now as I believe it is obsolete.
