### ISSUE TITLE
Bower?

### ISSUE THREAD

**Issue by wmleler** [Polymer/docs#1083]
Is it possible to use Polymer without using Bower?  In our toolchain we are using NPM and (because of Polymer) Bower too. Seems redundant and overly complicated.

Here's a good article on problems with Bower and why it might be better to use something else:
http://gofore.com/ohjelmistokehitys/stop-using-bower/

**Comment by ktiedt** [comment]
Before bower and npm there were version control systems... so the short answer would be an obvious yes, check out the tag you want from github. Npm is not without its problems either ;)

**Comment by arthurevans** [comment]
Yeah, you can check things out from github, it's just a little difficult to manage dependencies if you're using a lot of elements (if you're not using anyone else's elements from bower, it's relatively simple to pull the library itself from git).

One of the issues described in that article is the flat dependency tree. Ironically, that's one of the reasons we use Bower. There's a little explanation here:

https://www.polymer-project.org/1.0/docs/start/reusableelements.html#structure

That said, Bower has its challenges. We're looking for ways to make life easier. Whether that's npm or a custom tool is unclear at the moment.

**Comment by wmleler** [comment]
Thanks for your responses. Yes, I know there are trade-offs between a flat dependency tree and one that allows multiple versions of dependencies in a hierarchy. Not sure of a better solution, just hate having two distinct solutions in the same app. Good to know you are looking at this.

Just wanted to point out a typo in that page (linked below):
<link rel="import" href="../icon-icon/icon-icon.html">
I think that should be “iron-icon” (in two places).

**Comment by arthurevans** [comment]
Closing this as the package management issue is tracked elsewhere: 

https://github.com/Polymer/polymer/issues/2578
https://github.com/Polymer/polymer/issues/326
