### ISSUE TITLE
introducing polymer 1.0: wrong link to release notes

### ISSUE THREAD

**Issue by hastebrot** [Polymer/docs#1084]
On the page https://www.polymer-project.org/1.0/docs/ in the sentence "For changes between 0.8 and 1.0, see the Release notes." the link to "Release notes" refers to

https://www.polymer-project.org/1.0/docs/docs/release-notes.html

but should be

https://www.polymer-project.org/1.0/docs/release-notes.html

**Comment by arthurevans** [comment]
Thanks. This should be fixed now.
