### ISSUE TITLE
On mobile Safari, clicking on the appbar dropdown shows empty

### ISSUE THREAD

**Issue by frankiefu** [Polymer/docs#1086]
On mobile Safari or desktop with narrow screen.
![screen shot 2015-05-28 at 2 06 11 pm](https://cloud.githubusercontent.com/assets/116360/7871130/c92b9e52-0542-11e5-82d0-aa67d57c092f.png)

**Comment by frankiefu** [comment]
This CSS rule seems to be the one making the link disappears.
https://github.com/Polymer/docs/blob/master/sass/elements/app-bar.scss#L116

**Comment by frankiefu** [comment]
It looks like we can adjust the rule in [app-bar.scss](https://github.com/Polymer/docs/blob/master/sass/elements/app-bar.scss#L116) to something like this:
```
polyfill-next-selector { content: ':host > a'; }
```
so the selector won't match the `<a>` insice the `paper-drown-menu` which is inside `app-bar`

**Comment by arthurevans** [comment]
Fixed in production. Thanks Frankie!
