### ISSUE TITLE
<body unresolved> issue in Firefox

### ISSUE THREAD

**Issue by back5576** [Polymer/docs#1094]
In Chrome, the injected style to set opacity:0 gets removed.
In Firefox, the injected style is never removed so the page renders but stays completely white.

**Comment by back5576** [comment]
I take it back. In Chrome also it never removes the injected style which sets opacity:0. Is it now necessary for developer to explicitly remove the style "body[unresolved]" ?

**Comment by ebidel** [comment]
`body[unresolved]` is removed in 1.0. Closing this as it's not related to the docs.

**Comment by arthurevans** [comment]
This needs to be documented. So reopening as a doc big.

**Comment by arthurevans** [comment]
Or a doc big. One or the other.

**Comment by katejeffreys** [comment]
Is this still a thing?

**Comment by katejeffreys** [comment]
Please re-open if it is a thing
