### ISSUE TITLE
Firefox and Firebug weirdness

### ISSUE THREAD

**Issue by back5576** [Polymer/docs#1095]
If I include webcomponents.min.js, in a sample, and have Firebug open, then refreshing the page takes over 10 seconds. If I close Firebug, it still takes 10 seconds. If I never open Firebug, the page refreshes basically instantly. 
If I include HTMLImports.min.js this issue does not occur.
It does not occur with Chrome.

**Comment by back5576** [comment]
If I disable then page refreshes immediately. If I re-enable Firebug, the page still refreshes immediately. This is probably a Firebug issue, but I've never seen this behaviour except when I include webcomponents.min.js.

**Comment by arthurvr** [comment]
This looks more like a bug report for firebug (or for webcomponents.js, though I doubt that). This is the documentation repo.

**Comment by ebidel** [comment]
Yea, this bug is unrelated to the polymer documentation.
