### ISSUE TITLE
First example with splices is not styled

### ISSUE THREAD

**Issue by DmitryTrigonis** [Polymer/docs#1104]
First example with splices (Array ob) is not styled

**Comment by arthurvr** [comment]
The first example on which page exactly do you mean?

**Comment by DmitryTrigonis** [comment]
oh sorry. Page about properties
https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-observation

**Comment by arthurevans** [comment]
Thanks! Fixed in #1110.
