### ISSUE TITLE
Site drop down has broken links

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1108]
https://twitter.com/paulgailey/status/604795638933557249

**Comment by arthurevans** [comment]
@robdodson I can't tell why it's not pulling the correct layout here. Everything looks good as far as I can tell, but it's serving the wrong menu.

**Comment by robdodson** [comment]
Should be patched up now. Give it a go!

**Comment by arthurevans** [comment]
D'oh. If it was a snake it'd'a bit me. I was looking in the top-nav, which has the same set of links. Forgot this was a separate element.
