### ISSUE TITLE
Add links from deprecated docs to new docs 

### ISSUE THREAD

**Issue by zmoshansky** [Polymer/docs#1122]
/Aside/ Polymer is great. A slight learning curve then just wow!

Since moving to 1.0, it's becoming difficult to find the correct documentation/patterns/features, etc; so a couple suggestions & Comments. 
#### Suggestions
- Scope search on the site to either prefer or only search based on the version selected (site:polymer-project.org/1.0, etc)
- Add deprecations markers to old content. I assume all of 0.5 is outdated, but some of the docs just doesn't exist yet under 1.0, and some docs are still very useful/haven't changed.
- Add links from old/deprecated docs to new versions.
- Moar demos! :)
#### Comments
- Migration Guides are fantastic
- Great work, seriously.
- I'm very eager to see the new iron-list component :+1:

**Comment by arthurevans** [comment]
We've fixed the first two points (search only covers 1.0, and 0.5 docs have deprecation markers.). Keeping this open for possibly solving #3, adding links from old docs to new.

**Comment by katejeffreys** [comment]
To help me manage the issues in the docs repo, I will close this issue in 7 days. If you need it to stay open for some reason, please comment to that effect within 7 days.
