### ISSUE TITLE
Question: Polymer and Bootstrap

### ISSUE THREAD

**Issue by dartdog** [Polymer/docs#1125]
It seems that Polymer (1.0) can be used for page elements that are then styled using a CSS framework ie Bootstrap? Or am I totally off base?

**Comment by ebidel** [comment]
Yes, with Shady DOM it's a bit easier to apply document-level styles to element internals. However, in a world where native shadow dom exists more widely, it won't be as easy. 

Closing this as it's not related to the documentation site. Feel free to discuss in our slack channel.

**Comment by dartdog** [comment]
No problem, how do I get access to the sack channel? fwiw I think it would be real helpful to lots to understand how this stuff relates and fits, hence would be a nice doc or FAQ answer?
