### ISSUE TITLE
Need to merge Behavior docs into element docs better

### ISSUE THREAD

**Issue by jyasskin** [Polymer/docs#1126]
For example, https://elements.polymer-project.org/elements/paper-dialog mentions `dialog-dismiss` but never defines it or mentions where it's defined. Then https://elements.polymer-project.org/elements/paper-dialog-behavior?active=Polymer.PaperDialogBehavior mentions `closingReason` but never defines it or mentions where it's defined. Developers wind up having to manually search the Behavior tree to find documentation, losing their context as they go.

**Comment by arthurevans** [comment]
Duplicate of https://github.com/Polymer/polymer-element-catalog/issues/97
