### ISSUE TITLE
Minor Typo Orphan </p> tag found in the "binding to properties" section of the docs (Quick tour of Polymer)

### ISSUE THREAD

**Issue by lozandier** [Polymer/docs#1135]
Minor typo found within the  code snippet associated with the [*binding to properties*](https://www.polymer-project.org/1.0/docs/start/quick-tour.html#binding-to-properties) section of the quick start tour portion of the documentation.

A `</p>` is never associated with an opening `<p>` tag if found shortly before `iron-input` is demonstrated for two-way binding purposes.

This is pictured before with the typo highlighted. 

![screen shot 2015-06-04 at 11 10 15 pm](https://cloud.githubusercontent.com/assets/1223224/7998747/edeafff4-0b0e-11e5-8532-312b7040bc64.png)

**Comment by arthurevans** [comment]
Fixed in latest site push. Thanks!
