### ISSUE TITLE
[Accessibility - Get the Code page] Contrast (P2)

### ISSUE THREAD

**Issue by lpalmaro** [Polymer/docs#1144]
Contrast is poor on the "note" portions of this page. Please make that text darker.

**Comment by lpalmaro** [comment]
Also, "Basics" contrast is poor with the white on blue. Please make this text more white and bold.

**Comment by lpalmaro** [comment]
Lastly, contrast on the white buttons is not sufficient

**Comment by arthurevans** [comment]
These should be fixed in #1168.
