### ISSUE TITLE
Migration guide should say what to do with this.super() calls.

### ISSUE THREAD

**Issue by jyasskin** [Polymer/docs#1151]
Presumably they're replaced with a behavior and a `FooBehavior.method.apply(this, arguments)`, but it'd be nice to see that in the docs.

**Comment by katejeffreys** [comment]
To help with prioritization and managing workload, I will close this issue with no docs changes in 7 days. To prevent this from happening, please comment within 7 days. Thanks!

**Comment by arthurevans** [comment]
Another 0.5-1.x migration issue. Closing.
