### ISSUE TITLE
Nuances involving async operations & the use of Polymer.dom.flush() seemingly benefits having a code snippet provided (DOM API Docs) 

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1159]
_From @lozandier on June 7, 2015 20:15_

Given the unconventional (non-standard) way that insert, append, & remove operations are transacted lazily, it seems in the best interest of developers reading up on Polymer to have a code snippet demonstrating the correct usage of `Polymer.dom.flush()` w/ such operations.

This is particularly true in the contexts of having to use `Polymer.dom.flush()` & `window.getComputedStyle`, assuming the latter was in fact the method referred by the `getComputedStyle` reference in the [documentation](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api).

_Copied from original issue: Polymer/polymer#1775_

**Comment by arthurevans** [comment]
_From @kevinpschaaf on June 8, 2015 17:15_

Maybe in the "async operations" box we could add a little code snippit?

**Comment by lozandier** [comment]
@arthurevans Yeah, that be awesome.

**Comment by MeTaNoV** [comment]
we just discuss this with @bicknellr ! so +1 !!! :)

**Comment by katejeffreys** [comment]
To help with prioritization and managing workload, I will close this issue with no docs changes in 7 days. To prevent this from happening, please comment within 7 days. Thanks!

**Comment by lozandier** [comment]
Understood.
