### ISSUE TITLE
[0.9] Array mutation API documentation

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1160]
_From @amannn on May 25, 2015 16:11_

In the [documentation regarding declared properties](https://www.polymer-project.org/0.9/docs/devguide/properties.html#array-observation) it is mentioned that there is a specific API for mutating arrays, so that observers take notice. It appears to me that the link is dead. The section doesn't seem to be availble (#array-mutation).

I guess that part of the documentation should be fixed. Would you mind telling me in the meantime what these APIs are?

_Copied from original issue: Polymer/polymer#1609_

**Comment by arthurevans** [comment]
Thanks for letting us know. I'll take a look at this when I get to the office. In the meantime, see the 0.9 release notes, here:

https://www.polymer-project.org/0.9/docs/release-notes.html#span-classbreakingbreaking-changespan-array-mutation-methods

**Comment by arthurevans** [comment]
_From @amannn on May 25, 2015 19:30_

Thanks for the quick response!

**Comment by zacharytamas** [comment]
This issue exists in 1.0's documentation too, as you'd expect. Running into some really frustrating problems with Polymer today that the documentation either doesn't provide info or I have to look in multiple places and infer what it all means.

**Comment by arthurevans** [comment]
Cleaning up old issues. This was fixed back in June in  https://github.com/Polymer/docs/commit/9d42ff1abf9c97f8a37d2e03518e395430e7d84a, but we missed closing the bug.
