### ISSUE TITLE
distributeContent appears twice in API docs

### ISSUE THREAD

**Issue by jyasskin** [Polymer/docs#1171]
http://polymer.github.io/polymer/ includes 2 rows for `distributeContent()`.

**Comment by ebidel** [comment]
@garlicnation know what's up with this? Generated docs are unhappy.

**Comment by garlicnation** [comment]
It appears in the source twice. I need to ignore functions w/ no docs or give precedence to functions w/ docs.

https://github.com/Polymer/polymer/blob/6dd6aa9755e2911018a199990875974e4e61f410/src/mini/shady.html#L88
https://github.com/Polymer/polymer/blob/fcbb3071bc3194bfd11f9b0d87e17800ad8bbb6c/src/mini/shadow.html#L26

**Comment by arthurevans** [comment]
This issue was moved to Polymer/hydrolysis#189
