### ISSUE TITLE
[1.0] event.target.templateInstance.model?

### ISSUE THREAD

**Issue by robrez** [Polymer/docs#1174]
I'm probably missing something in the docs.. but..

Prior to .8, we could reference `event.target.templateInstance.model` in an event handler.

In >.8, I found `event.target._templateInstance.__data__`, but I'm not sure if its okay to use. Additionally, it is not always defined when it previously was.

Given:
```
<template is="dom-repeat" items="{{items}}">
  <div class="thing" on-tap="_onItemTapped">
    <div>{{item.text}}</div>
    <div>{{item.otherstuff}}</div>
  </div>
</template>  
```

Prior to .8, any descendant of `.thing` (referenced via event.target), would have templateInstance.model.

Now, it seems that only the 1st child (`.thing`) of the binding template contains the _templateInstance.__data__.

Sorry if this is covered and I missed it.

**Comment by arthurevans** [comment]
Hi @robrez,

Documented here: https://www.polymer-project.org/1.0/docs/devguide/templates.html#handling-events-in-dom-repeat-templates

**Comment by robrez** [comment]
haha yeah I just saw that - that actually makes things easier.  My case is still a bit different.

Some clarification - my prior markup was more like this:
```
<div on-tap="_onItemTapped">

<template is="dom-repeat" items="{{items}}">
  <div class="thing">
    <div>{{item.text}}</div>
    <div>{{item.otherstuff}}</div>
  </div>
</template>  

</div>
```

That is in an attempt to have just one event handler for the entire set of items rather than one for each item.

**Comment by arthurevans** [comment]
@robrez: There's a note at the end of the section about handling that case. You can use `itemForElement(e.target)`.

**Comment by robrez** [comment]
Just as the docs @arthurevans linked state:
declarative event handlers inside the dom-repeat can grab the model via `e.model`.

an event handler declared outside the dom-repeat can grab the model via `itemForElement(e.target)`.

```
<div on-tap="_onItemTapped">
  <template id="repeater" is="dom-repeat" items="{{items}}">
  ...
  </template>  
</div>

...

  _onItemTapped: function(e) {
    console.log(this.$.repeater.itemForElement(e.target));
  }
```

Thanks for the help, sorry to bug you w/ stuff that has been documented.
