### ISSUE TITLE
Document scopeSubtree

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1175]
... and other strategies for working with shady DOM and third-party libraries.

**Comment by katejeffreys** [comment]
To help with prioritization and managing workload, I will close this issue with no docs changes in 7 days. To prevent this from happening, please comment within 7 days. Thanks!

**Comment by arthurevans** [comment]
This is documented and should be closed: https://www.polymer-project.org/1.0/docs/devguide/styling#scope-subtree
