### ISSUE TITLE
Wrong file extension shown in external-stylesheets example

### ISSUE THREAD

**Issue by sjmiles** [Polymer/docs#1178]
In the section on external stylesheets (https://www.polymer-project.org/1.0/docs/devguide/styling.html#external-stylesheets) there is an example of how to import an external style-sheet that looks like this:

`<link rel="import" href="my-custom-styles.css">`

This is an HTML import and the file itself contains HTML tags (namely `<style is="custom-style">`) so this cannot be a `.css` file and must be designated `.html`.

Aside: this distinction is confusing, I think we perhaps should abandon the `type="css"` feature.

**Comment by ebidel** [comment]
This is fixed in master (https://github.com/Polymer/docs/commit/651e1a2aeac7a7bc29b7b2cf47a895772858fc5b) but not pushed.

**Comment by ebidel** [comment]
@arthurevans when should we do a docs push?

**Comment by arthurevans** [comment]
Soon! Got a big docs PR I have to merge, and I'm chewing on the a11y PR.
