### ISSUE TITLE
On the articles list page, the date is barely legible

### ISSUE THREAD

**Issue by curioustechizen** [Polymer/docs#1181]
Referring to [this page](https://www.polymer-project.org/1.0/articles/) - there is a date published against each article. This date needs to be in a different color or bolder font in order for it to be legible.

I bring this up because it is possible this might be a theme-wide issue (the CSS style `.article .byline` might be used elsewhere). This might be affecting legibility in places where the information is more important than a mere date of publish!

**Comment by arthurevans** [comment]
Fixed in #1168. Thanks for the report!
