### ISSUE TITLE
Testing and Documenting Behaviors

### ISSUE THREAD

**Issue by indolering** [Polymer/docs#1182]
The [article on behaviors](https://github.com/Polymer/docs/blob/master/1.0/docs/devguide/behaviors.md) fails to discuss documenting them or the best method for testing (do I create a dummy element?).   It would probably be reasonable to add an example behavior element, akin to the seed element.

**Comment by katejeffreys** [comment]
To help with prioritization and managing workload, I will close this issue with no docs changes in 7 days. To prevent this from happening, please comment within 7 days. Thanks!
