### ISSUE TITLE
Update docs to say ::shadow and /deep/ are deprecated in Polymer 1.0

### ISSUE THREAD

**Issue by sorvell** [Polymer/docs#1188]
Here: https://www.polymer-project.org/1.0/docs/devguide/styling.html#xscope-styling

Note, users are still trying to use these [features](https://github.com/Polymer/polymer/issues/1809). We support them but they should be considered deprecated.

**Comment by sorvell** [comment]
They are being removed from the cross scope styling spec, and Chrome may deprecate them soon.

**Comment by wuyizi** [comment]
This is happening:  https://www.chromestatus.com/feature/6750456638341120
I am on chrome 45 beta and seeing warnings already from mostly all polymer based web sites (e.g. elements.polymer-project.org).

Those warnings are probably from these files:
https://github.com/PolymerElements/paper-styles/blob/master/classes/shadow-layout.html
https://github.com/PolymerElements/iron-flex-layout/blob/master/classes/iron-shadow-flex-layout.html

**Comment by mfrost66** [comment]
From 1.0 styling guide:
>>> /deep/ ... For the reasons above, the Polymer team is currently exploring other options for theming that address the shortcomings above and provide a possible path to obsolescence of /deep/ and ::shadow altogether

>>>Custom CSS mixins... Polymer includes an experimental extension

So, /deep/ is deprecated, css mixins are experimental.  Where does that leave us?  The polymer elements seem to be all-in on @apply.  Can we get either a commitment on long-term support for mixins or an update on the "possible path" mentioned above?  

I need to fix my current /deep/ usages, but I'd really hate to do it more than once. If this is already documented and I missed it, please point me in that general direction - thanks!
