### ISSUE TITLE
Docs don't include commit from May 15

### ISSUE THREAD

**Issue by jyasskin** [Polymer/docs#1190]
https://www.polymer-project.org/1.0/docs/devguide/properties.html#computed-properties has a broken link on "arguments types supported by observers, including [paths](https://www.polymer-project.org/1.0/docs/devguide/properties.html#path-observation)", which was fixed at https://github.com/Polymer/docs/commit/2299fd4c82558cae6a893b4b93ce0fbd8ed89a8f#diff-07936cc3163b32c7b2a4f859ae877754R349 on May 15. The release notes say the docs were [updated June 10](https://www.polymer-project.org/1.0/docs/release-notes.html#documentation-updates-10-june-2015), so it's surprising they don't include this fix.

**Comment by arthurevans** [comment]
Actually, the docs include that fix, but there are two more links on that page that had the same error:

https://github.com/Polymer/docs/commit/2299fd4c82558cae6a893b4b93ce0fbd8ed89a8f#diff-07936cc3163b32c7b2a4f859ae877754R612

I'll fix these.
