### ISSUE TITLE
"Filtering and sorting lists" needs more advice around `observe`

### ISSUE THREAD

**Issue by sjmiles** [Polymer/docs#1191]
https://www.polymer-project.org/1.0/docs/devguide/templates.html#filtering-and-sorting-lists

Suggest we need to add more about the scope of `observe` here, and specifically, about the need to call `render` when non-item-scoped filter/sort criterion changes, as is described in the `dom-repeat` docs themselves.

**Comment by arthurevans** [comment]
Closed in #1431.
