### ISSUE TITLE
Open the website country restrictions

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1196]
_From @AliMD on June 16, 2015 12:45_

Could you please open the website country restrictions for iranian users?

![screenshot from 2015-06-16 17 11 36](https://cloud.githubusercontent.com/assets/697913/8183111/f2eff28a-144a-11e5-8d7c-ccbb6745d952.png)

There is no issue to view elements.polymer-project.org !
I think its for app-engine policy and it can be switched.

_Copied from original issue: Polymer/polymer#1885_

**Comment by ebidel** [comment]
_From @sorvell on June 16, 2015 16:19_

This issue tracker is for the Polymer core library. We'll make sure this is moved to an appropriate location.

**Comment by ebidel** [comment]
@AliMD I've never seen this setting before. Do you know where I can find it in the admin console?

**Comment by AliMD** [comment]
No!
Many Google website has same issue for Iranian users!
Google remove this restriction for play store and chrome web store and Android.com in last year.
But this issue still remain for new products!

**Comment by ebidel** [comment]
I'm not sure the process to make this happen though. I can poke around.

**Comment by katejeffreys** [comment]
To help with prioritization and managing workload, I will close this issue with no docs changes in 7 days. To prevent this from happening, please comment within 7 days. Thanks!

**Comment by AliMD** [comment]
Any hope to remove this restriction after 2 years?!

**Comment by katejeffreys** [comment]
I will see what I can do :)

**Comment by arthurevans** [comment]
I'm sorry to say, but I've been informed that we don't have any control over this restriction.

**Comment by AliMD** [comment]
Thank you, this issue finally solved after two years 👍
