### ISSUE TITLE
The requested URL /0.5/components/core-tooltip/demo.html was not found on this server.

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1197]
_From @VikramTiwari on June 16, 2015 2:10_

https://www.dropbox.com/s/rcj7yxn4uehe9ag/Screenshot%202015-06-15%2019.09.50.png?dl=0

_Copied from original issue: Polymer/polymer#1880_

**Comment by ebidel** [comment]
_From @VikramTiwari on June 16, 2015 2:12_

Page URL

https://www.polymer-project.org/0.5/components/core-elements/demo.html#core-tooltip

**Comment by arthurevans** [comment]
Cleaning up old issues -- URL works now, and has for some time.
