### ISSUE TITLE
documentation replacement for 0.5 onMutation

### ISSUE THREAD

**Issue by wmleler** [Polymer/docs#1203]
onMutation from 0.5 is gone, and there is no mention of it in the Migration Guide. Would be nice if at the very least there was a mention that it vanished from 1.0 and to use a MutationObserver instead.

Or even better... add onMutation back. It just seems so much easier to use and makes the resulting code clearer.

**Comment by afandria** [comment]
Agreed. This seems like a common use case, so I think it would be helpful to include it in the API or provide a migration example.

**Comment by arthurevans** [comment]
@sjmiles @sorvell any comment here? (I'm not sure if webcomponents-lite.js includes the MO polyfill?)

**Comment by rohitvarkey** [comment]
+1 for including in the docs and adding a migration example.

**Comment by arthurevans** [comment]
Can point to `observeNodes`: https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#observe-nodes

**Comment by katejeffreys** [comment]
Is this still necessary?

**Comment by arthurevans** [comment]
No, we should close. With apologies that I missed this for the 0.5 -> 1.0 migration, it seems a little late to update that now.
