### ISSUE TITLE
Links in Data Binding doc point to wrong document.

### ISSUE THREAD

**Issue by grokys** [Polymer/docs#1204]
The following links under https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#dependent-properties-in-computed-bindings don't work.

- paths
- paths with wildcards
- paths to array splices

They point to the same document but in reality their documentation is in the "Declared Properties" document at:

https://www.polymer-project.org/1.0/docs/devguide/properties.html

**Comment by arthurevans** [comment]
Thanks for the report. Fixed in the last site update (the direct link to the section has changes slightly, though):

https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#dependent-properties
