### ISSUE TITLE
Clarify limitations of `created`

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/docs#1212]
Refer to https://github.com/Polymer/polymer/issues/1886 and clarifications (particularly re: `created`) in the primer here: 

https://github.com/Polymer/polymer/commit/19cdf42e5af7cda194025ab8bd5a56ca0c16a61d

**Comment by arthurevans** [comment]
The docs section has been improved, but I missed this bug when I was updating it. Kevin's updates to the primer have more detail on created that we should upstream into the docs.

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.
