### ISSUE TITLE
Document sharing computed bindings using behaviors

### ISSUE THREAD

**Issue by donwojtallo** [Polymer/docs#1223]
I think that the documentation should mention about ability of extending elements with computed binding functions. This is very helpful for creating similar behavior as filters or i18n.
See this example:

```
<dom-module id="my-element">

    <template>
        <div>{{uppercase('test')}}</div>
    </template>

    <script>
        var FiltersBehavior = {
            uppercase: function(text) {
                return text.toUpperCase();
            }
        }

        Polymer({
            is: 'my-element',
            behaviors: [FiltersBehavior]
        });
    </script>

</dom-module>
```

Also, see this conversation:
https://github.com/Polymer/polymer-expressions/issues/63#issuecomment-114538915

**Comment by wenerme** [comment]
Any progress on i18n support ? Currently we maintain zh doc [here](https://github.com/clia/docs), it's hard to track upstream change on doc without i18n support, also can not merge back to upstream.

Or we try to add i18n function in docs and make a proper pr ?

**Comment by wenerme** [comment]
BTW, we don't care i18n support for 1.0, it's easier for focus on 2.0 only.

**Comment by arthurevans** [comment]
We're not going to do any new docs for 1.x, so closing.
