### ISSUE TITLE
Clarify that event.model only includes _bound properties_ of the current scope.

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1226]
See:

https://github.com/Polymer/polymer/issues/1919

For problem description and workarounds.

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by arthurevans** [comment]
This is fixed in the 2.x docs (see https://www.polymer-project.org/2.0/docs/devguide/templates#handling-events, paragraph starting "Only bound data is available on the model object").
