### ISSUE TITLE
Document optional arg to updateStyles

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1232]
See: https://github.com/Polymer/polymer/pull/1916

**Comment by katejeffreys** [comment]
@arthurevans Is this still a thing?

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by arthurevans** [comment]
Noted in passing in the 1.x docs:

You can directly modify a Polymer element's custom property by setting key-value pairs in customStyle on the element (analogous to setting style) and then calling updateStyles. **Or you can pass a dictionary of property names and values as an argument to updateStyles.**

(emphasis added)

In 2.x, this is the only way to update custom properties, as the `customStyle` property has been removed. So this is another one we can close.
