### ISSUE TITLE
Docs info repeated in http://polymer.github.io/polymer/

### ISSUE THREAD

**Issue by horacioibrahim** [Polymer/docs#1233]
Hi guys!

A part of the docs explanation, in `...valids fields...` from `properties` definition, the text `when true configures the property to have a getter, but no setter. To set a read-only property, use the private setter method _set_<property>(value).` is repeated in the `readOnly` and `reflectToAttribute`. Is valid? See: http://polymer.github.io/polymer/

Thanks!

**Comment by arthurevans** [comment]
I'm not seeing this duplication, can you double check? This doc should only be on the readOnly property.

**Comment by horacioibrahim** [comment]
I'm also not see in doc on github. I'm seeing this only in the http://polymer.github.io/polymer/ in dropdown to select `Polymer.Base`. Please, you can see image below...

![captura de tela 2015-06-29 as 10 26 18](https://cloud.githubusercontent.com/assets/1104460/8408851/d2edbdec-1e49-11e5-852c-02fc578b1d4e.png)

**Comment by arthurevans** [comment]
That's very strange. I don't see the same thing on that page. Can you try clearing your cache (or perhaps loading the page in an Incognito window)?

**Comment by horacioibrahim** [comment]
After to clear cache in Chrome the content is same no changes. But I open in the Firefox and reflectToAttribute was different.
