### ISSUE TITLE
separate 1.0 and 0.5 search

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#1234]
Can you split the search results into 1.0 and 0.5 please, right now they are a mix of 1.0 and 0.5 results.

![image](https://cloud.githubusercontent.com/assets/863731/8398555/b3dcc30e-1df3-11e5-9f97-da64d0412c25.png)

**Comment by ebidel** [comment]
We're working on custom search that can selector 0.5 and 1.0 docs: https://github.com/Polymer/docs/pull/1213

However, it's impossible to remove the 0.5 results from search unless we remove the content. We're not ready to do that...it just needs to be ported. The 0.5 results have 1 year + of SEO :\

**Comment by gertcuykens** [comment]
hmm ok, closing this, I also can't think of any other solution then removing 0.5 completely.
