### ISSUE TITLE
Build a sample app in node server

### ISSUE THREAD

**Issue by ratneshn** [Polymer/docs#1239]

**Comment by ebidel** [comment]
Can you clarify what this is?

**Comment by ratneshn** [comment]
Hi,

I want this app (https://www.polymer-project.org/0.5/docs/start/tutorial/intro.html) to be build in node server, at it used python server.

**Comment by ebidel** [comment]
The app is entirely client side. You can use whatever server server you'd
like :)

**Comment by ratneshn** [comment]
Thanks :+1: 
But I want to use node server, and I have no idea how to integrate polymer app with it.

**Comment by ebidel** [comment]
I've used the node serve command in the past to run a node server in my
app's directory.

**Comment by ratneshn** [comment]
No, its not working giving error. :(
Error: Cannot find module 'my-project/serve'.

**Comment by ebidel** [comment]
Try https://www.npmjs.com/package/serve.

**Comment by ratneshn** [comment]
Hey thanks that worked :) 
How do you I explore Polymer more.
