### ISSUE TITLE
iOS Application with Polymer 1.0

### ISSUE THREAD

**Issue by ajit-kumar-azad** [Polymer/docs#1242]
I have created http://blogs.walkingtree.in/2015/07/03/ios-application-with-polymer-1-0/ article. Does it make sense to include it in the list of articles on the official Polymer Articles page?

**Comment by katejeffreys** [comment]
Apologies for the lack of response. I am closing as out of date; http://blogs.walkingtree.in/2015/07/03/ios-application-with-polymer-1-0/ now goes to a 404.
