### ISSUE TITLE
Error vulcanize task

### ISSUE THREAD

**Issue by richarhendricks** [Polymer/docs#1249]
when I try to give the `grunt docs` he me of this error, and followed all the steps.
![Imgur](http://i.imgur.com/jhv8FPg.png)
It will be a problem only for me or for everyone?

**Comment by julio73** [comment]
I get the same errors.

**Comment by richarhendricks** [comment]
cc @robdodson @ebidel @arthurevans

**Comment by kaycebasques** [comment]
Check out my pull request https://github.com/Polymer/docs/pull/1241.

I think the latest grunt-vulcanize and vulcanize modules break the build. When I use grunt-vulcanize 0.6 (i.e. `"grunt-vulcanize": "^0.6.4"` in `package.json` and vulcanize 0.7 (i.e. `npm -g install vulcanize@0.7`), everything quiets down.

**Comment by robdodson** [comment]
Yeah this makes sense. `grunt-vulcanize` was updated to use latest vulcanize which is for Polymer 1.0 but the site is still running Polymer 0.5

**Comment by kaycebasques** [comment]
Should be fixed now that https://github.com/Polymer/docs/pull/1241 is merged into master.
