### ISSUE TITLE
Please stop redirecting to 0.5 documentation version for www.polymer-project.org

### ISSUE THREAD

**Issue by adewinter** [Polymer/docs#1252]
Or fix the top right dropdown such that when you select "1.0" you end up in the right place and not just the home page.  It is incredibly frustrating when this happens over and over again.

**Comment by ebidel** [comment]
@robdodson can your dropdown be smarter? Redirect to the same URL under the selected version. There would be 404s though.

**Comment by robdodson** [comment]
the 404s was why I wasn't doing it actually...

**Comment by arthurevans** [comment]
TLD now redirects to 1.0. Closing.
