### ISSUE TITLE
Behaviors and order of application of lifecycle methods

### ISSUE THREAD

**Issue by rictic** [Polymer/docs#1258]
[1.0/docs/devguide/behaviors.html](/Polymer/docs/blob/master/1.0/docs/devguide/behaviors.md) says

> Lifecycle callbacks are called on the base prototype first, then for each behavior in the order given in the behaviors array.

But I'm getting reports that people are seeing behavior lifecycle callbacks run first, then lifecycle callbacks defined by an element definition. For example:

![polymer-behaviors](https://cloud.githubusercontent.com/assets/1659/8686785/354b61ec-2a3e-11e5-928d-522c9bf01c6c.png)

It's possible that this documentation is correct but a bit confusing, if `base prototype` refers to something other than the element definition.

**Comment by kevinpschaaf** [comment]
Confirm the typo in the documentation, you are correct it is "behaviors first in the order given in the behaviors array, followed by the prototype."

**Comment by kevinpschaaf** [comment]
See https://github.com/Polymer/polymer/commit/2a516619675b775f205da60c50f5b29e5bf95c1e for correct description of behavior ordering.

**Comment by arthurevans** [comment]
Fixed in https://github.com/Polymer/docs/commit/eebc5fc796c6503cb3ae01454e22921d7323f25e.
