### ISSUE TITLE
Enchancement Request : Print to pdf

### ISSUE THREAD

**Issue by devAtPolydeals** [Polymer/docs#1260]
I really prefer reading the old fashioned way on a paper, is it possible to have a Print to PDF feature whereby the entire docs will be printed on 1 page? It is really difficult to print page by page, plus there is a lot of margin space that is wasted.

**Comment by rafaelCMoura** [comment]
+1

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.
