### ISSUE TITLE
Missing github icon on the site polymer-project.org

### ISSUE THREAD

**Issue by tjsavage** [Polymer/docs#1262]
_From @besuhoff on July 9, 2015 12:50_

Ubuntu / Google Chrome Version 43.0.2357.81 (64-bit)

![selection_200](https://cloud.githubusercontent.com/assets/6132126/8595582/304dfb86-2652-11e5-947e-e90b0c50eb11.png)

_Copied from original issue: Polymer/polymer#2053_

**Comment by tjsavage** [comment]
_From @kevinpschaaf on July 9, 2015 22:10_

This issue tracker is for the core Polymer library. We'll move this to the docs tracker where we track documentation issues. Thanks

**Comment by arthurvr** [comment]
Shouldn't this issue be closed? This was fixed in https://github.com/Polymer/docs/commit/9c1e0280c2a34e8f2bc8c8fac28b7604af720180.
