### ISSUE TITLE
API reference complete?

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#1267]
http://polymer.github.io/polymer/

I am trying to get used to the API reference to look things up so I don't need to weed trough the https://www.polymer-project.org/1.0/docs/devguide/feature-overview.html every time I forget something, but is the API complete I mis things like Polymer.dom Polymer.Templatizer ?

**Comment by katejeffreys** [comment]
To help with prioritization, I will close this issue in 7 days with no docs changes unless requested otherwise. Thanks!
