### ISSUE TITLE
Html Conversion Error: Prematurely Closed Tags in Live Docs

### ISSUE THREAD

**Issue by gskielian** [Polymer/docs#1283]
In summary, there is a hyperlink error in the docs, which appears to come out from a prematurely closed anchor tag.  This might be a result of a larger bug within the code that processes the github-source to create the source on the live-site, images and links to sources below:

### live-site hyperlink error

![screen shot 2015-08-02 at 9 49 34 am](https://cloud.githubusercontent.com/assets/4149080/9027083/0fed77ba-38fc-11e5-8d16-1826c4cc33ff.png)

Direct Link to Page: https://www.polymer-project.org/0.5/docs/elements/material.html

---

#### What should be the case -- and what's in the polymer github docs:

```html
<a href="../../components/paper-elements/demo.html#paper-shadow">
<core-icon icon="arrow-forward" size="16"></core-icon> More examples</a>
```

#### What is the case -- from inspecting source code on the live site:

```html
<p>
<a href="../../components/paper-elements/demo.html#paper-shadow"></a>
</p>
<core-icon icon="arrow-forward" size="16" aria-label="arrow-forward" role="img"><svg viewBox="0 0 24 24" height="100%" width="100%" preserveAspectRatio="xMidYMid meet" fit="" style="pointer-events: none; display: block;"><g><path d="M12 4l-1.41 1.41L16.17 11H4v2h12.17l-5.58 5.59L12 20l8-8z"></path></g></svg></core-icon>
<core-icon icon="arrow-forward" size="16"></core-icon> 
<p> More examples</a></p>
```

### Direct Links to Relevant Sections of the Docs 

Direct Link to Docs-source: https://github.com/Polymer/docs/edit/master/0.5/docs/elements/material.md

The docs-source shows that the html is fine in github, and suggests a potentially larger fix is required for converting html in this repo to that within the live site, image of relevant section of docs below:

![screen shot 2015-08-02 at 9 53 07 am](https://cloud.githubusercontent.com/assets/4149080/9027099/7ede5c02-38fc-11e5-891b-fe6f3c9e6471.png)

**Comment by arthurevans** [comment]
Ah, yeah. For some reason it appears the Markdown converter terminates the previous paragraph when it hits the <core-icon> tag. Wrapping each link in a paragraph tag fixes the issue.
