### ISSUE TITLE
core-component-page.html in utf-8 encoding causes Liquid Exception error

### ISSUE THREAD

**Issue by quangld** [Polymer/docs#1284]
I couldn't access https://www.polymer-project.org/ for a couple days now.
I thought I would build it followed the instruction from the front page of
https://github.com/Polymer/docs/

when did "grunt docs"
I received this error:
Liquid Exception: "\xE2" on US-ASCII in _layouts/default.html

Adding encoding: "utf-8" to _config.yml file doesn't help

So I tracked down which files using utf-8 encoding and found out: it is core-component-page.html 
converted this file to ascii and reran "grunt docs" with no issue.

My question is: Is it safe to do so? 
Because core-component-page contains a long javascript code, which is very hard to find out why is it encoded with utf-8.

**Comment by arthurevans** [comment]
Odd. I have never seen this error. I wonder if it has something to do with your environment &/or github client config?

All the files should be UTF-8, I suspect -- the HTML Imports spec specifies UTF-8.

**Comment by arthurevans** [comment]
No further reports on this, closing.
