### ISSUE TITLE
Configuring default values location

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/docs#1286]
According to docs `Configuring default values` belongs to `Polymer mini`, but in source code it seems to be a `Polymer standard` feature

**Comment by katejeffreys** [comment]
@arthurevans Is this still a thing?

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by nazar-pc** [comment]
Doesn't really matter, modern Polymer is structured differently.
