### ISSUE TITLE
Developer Guide misinformation

### ISSUE THREAD

**Issue by Gi60s** [Polymer/docs#1287]
Reading through the 1.0 Developer Guide I found an inconsistency between instructions.

At https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#template-stamping there is a note that states: "Note: Defining an element in the main HTML document is not currently supported." If this feature is now supported this note should be removed.

At https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#main-document-definitions we are given instructions on exactly how to define an element in the main HTML. If this feature is not yet supported then a note should be added here as well that the feature is not yet supported.

I haven't tested this in all browsers, but the main HTML file does seem to support element definitions.

**Comment by robdodson** [comment]
I think (but could be wrong) that this only works in Chrome at the moment. @GoneIn20Seconds did you try in other browsers?

**Comment by GoneIn20Seconds** [comment]
What! Rob Dodson replied to my issue? How cool is that?

I just tested it in Firefox and IE as well, but it only worked in Chrome. Being such, I guess that there should be a note at https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#main-document-definitions saying that this isn't currently supported by all browsers.

**Comment by robdodson** [comment]
> What! Rob Dodson replied to my issue? How cool is that?

hehe, i lurk :)

**Comment by kaycebasques** [comment]
At the top of the main document definitions section it says:

> You should only define elements from the main document when experimenting. In production, elements should always be defined in separate files and imported into your main document.

So, the purpose of the section is "if you want to do this when developing / testing, this is how you do it, but don't do it in production." That might be too confusing. We can either remove the section and say "don't do this" or clarify the references throughout the documentation.

**Comment by GoneIn20Seconds** [comment]
I noticed that as well and took it as a best practice recommendation (which does make a ton of sense, it would be far too hard to manage your application, plus we're building reusable components here, not one time use components, but I digress).

Either way, https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#main-document-definitions should have a note that says that it isn't supported in all browsers. Without the note, someone who is learning Polymer could try to make it work and not succeed. This would cause general confusion for the learner and may even be the straw that breaks the camel's back, causing the learner to give up Polymer and instead use what they already know about other frameworks or what not.

I love jQuery and all, but I don't use it to build large apps any more. What if a learner said, I don't get Polymer, so I'm going to build a massive web app with jQuery. Yowch for them.

**Comment by arthurevans** [comment]
The code sample shown in the docs should work fine in other browsers:

http://jsbin.com/tanafi/1/edit?html,console,output

Note that this works fine for me in Safari and Firefox. (Make sure Auto-run JS is checked -- it came unchecked in my Firefox window, causing much confusion.)

Note that it is quite slow to render in Firefox. 

Kayce, can you update the note in the local DOM chapter to say something like "Elements should generally be defined outside of the main document, except for testing. For caveats about defining elements in the main document, see ___".

I don't think we need any other updates, although it might be good to do a grep through the doc site and make sure we don't refer to the main document elsewhere in the 1.0 docs.

**Comment by kaycebasques** [comment]
hallo, I did a `grep -A 5 -B 5 -r " main " 1.0/docs/* | less` to search for other relevant mentions in the document, but nothing appeared to need the fixings.

**Comment by arthurevans** [comment]
:+1: for grep fu :D
