### ISSUE TITLE
Article: Routing and Polymer Elements

### ISSUE THREAD

**Issue by Matt2012** [Polymer/docs#129]
Would love to see a write up of routing in a SPA and how that would work with polymer components. 

So we might start with a home page with some simple text in the main content pane then when you click /photos the photos grid component is loaded into the main content pane.

Next when you filter the photos the url might go to /photos?filter=country/uk/time/day/quality/high&sort=title/desc/date/asc&search=beach and we could see that that would update a data component that was bound to the photo grid component.

Then when a photo was selected we might get /photos?filter=country/uk/time/day/quality/high&sort=title/desc/date/asc&search=beach&selected=1272 which would transition from grid view to selected photo view within the same component.

Would appreciate seeing this outside a full fat framework like angular maybe just using a router library or something like marionettejs.

**Comment by arthurevans** [comment]
Ping? We have an 0.5 SPA example and PSK... Probably this request will get reincarnated with the carbon- element set.

**Comment by arthurevans** [comment]
Closing this as an issue. Plan of record is to document carbon-router when it's available.
