### ISSUE TITLE
injectBoundHTML disappeared?

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1297]
_From @apowers313 on August 12, 2015 5:22_

The [Migration Guide](https://www.polymer-project.org/1.0/docs/migration.html) and [Release Notes](https://www.polymer-project.org/1.0/docs/release-notes.html) for Polymer 1.0 don't mention that injectBoundHTML was removed but... it doesn't seem to exist in Polymer anymore.

Is that an oversight in the documentation?

_Copied from original issue: Polymer/polymer#2254_

**Comment by arthurevans** [comment]
Yes, it's an oversight.

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by arthurevans** [comment]
Probably not worth fixing at this point. Hopefully we don't have anyone left upgrading from 0.5.
