### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by LucasCaixeta** [Polymer/docs#1299]
Please,

Can anyone do a breaf tutorial about Polymer Push Notifications? (or web notifications).
I´m with difficult to find out articles about it.

Many thanks.

**Comment by ebidel** [comment]
cc @jeffposnick

**Comment by jeffposnick** [comment]
The [Push Notifications on the Open Web](http://updates.html5rocks.com/2015/03/push-notificatons-on-the-open-web) article has some general background info on service worker-based push notifications.

The [`<platinum-push-messaging>` docs](https://elements.polymer-project.org/elements/platinum-push-messaging) have some info specific to the element.

You can read through the [demo](https://github.com/PolymerElements/platinum-push-messaging/tree/master/demo)'s source code and run it locally to test it out.

I'll leave this issue open in case @wibblymat has any plans to write up an article or codelab dedicated to `<platinum-push-messaging>`.

**Comment by wibblymat** [comment]
There is nothing more planned at the moment. It's a good idea, but I don't have the spare cycles for the foreseeable future.

There is enough information already linked by @jeffposnick for you to get started for now, but I'm afraid that it's not a simple tutorial process.

**Comment by EduardoNavarro** [comment]
Hi everyone!
Im trying to get data from push notifications like says in the docs:

__The second way is to send the message data in the body of the push message from your server. In this case you do not need to configure anything in your page:__
```html
<platinum-push-messaging></platinum-push-messaging>
```

Ive been trying to listen events like "platinum-push-messaging-push" but when the event is listened i get event.detail.message empty...
Im new in polymer push world, i hope you can help me to get the payload im sending from the server. (the push sended from the server works on android where i can get the data without problems).

Thanks a lot!

**Comment by wibblymat** [comment]
@EduardoNavarro the next sentence in the docs after the section you quoted is:

**Note that this method is not currently supported by any browser**

Sadly, this is still true for now. Sorry for the confusion! Message bodies will be implemented in Chrome as soon as the details are finalized, but it will involve sharing a public key as part of the subscription details and then encrypting the message on the server before sending it to GCM.

**Comment by EduardoNavarro** [comment]
Thanks Mat!
Any eta on this? Just to know if i csn wait for this feature or workaround
this for now?

Thanks again for the info!

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by arthurevans** [comment]
This is not something we're likely to cover in the Polymer docs.
