### ISSUE TITLE
😩 Doc searching UX is frustrating.

### ISSUE THREAD

**Issue by samccone** [Polymer/docs#1301]
As a newish user to polymer I have found looking over docs to be frustrating, others on my team have also expressed this frustration. Here is the current flow that I have been seeing / experiencing. 

### User Flow

* A user newish to polymer wants to double check 2 way data binding
* ![screen shot 2015-08-17 at 9 31 55 am](https://cloud.githubusercontent.com/assets/883126/9305898/e88f6a7a-44c2-11e5-8ace-7d3500e35607.png)

##### They use the search bar

* ![screen shot 2015-08-17 at 9 32 07 am](https://cloud.githubusercontent.com/assets/883126/9305902/f1c425fe-44c2-11e5-9755-c3e5df8e72ca.png)

##### Oh a new tab... odd not in site (they think)

* ![screen shot 2015-08-17 at 9 32 14 am](https://cloud.githubusercontent.com/assets/883126/9305907/fc83aa78-44c2-11e5-8176-89acfee62284.png)

##### Lets switch to 1.0 via the dropdown

* ![screen shot 2015-08-17 at 9 33 35 am](https://cloud.githubusercontent.com/assets/883126/9305931/19dcfb88-44c3-11e5-947c-e4bf3a339efa.png)
* ![screen shot 2015-08-17 at 9 33 43 am](https://cloud.githubusercontent.com/assets/883126/9305937/22059a90-44c3-11e5-9077-2c6fbb7c0637.png)

##### Nooooo :skull: :hear_no_evil: 

----------

### Potential Fixes

1) scope the search bar per version i.e. (0.5/1.0)
2) fix 0.5 -> 1.0 redirects to go to corresponding doc pages
3) Implement an in site doc search.

Thoughts? Terrible Idea? :goat: :sparkles:

**Comment by alexpaluzzi** [comment]
I am all for anything that keeps 0.5 from popping up for me.

For a lot of people new to Polymer, they might not even notice they are reading old and completely different documentation. The way it's indexed with Google makes it that much worse.

If it were up to me, I would completely move and archive the 0.5 links and make sure it's not crawled anymore. But I'm sure someone has a reason why we can't do that. :)

In short...
+1

**Comment by samccone** [comment]
I think we can do more on this one:

Our goal should be to make finding and consuming docs sooo easy...

ideally making things like this not needed :)
https://chrome.google.com/webstore/detail/polysearch/gchibjlnlbpgcfjpbebnlecbbjndiidj
