### ISSUE TITLE
Add an authentication example

### ISSUE THREAD

**Issue by arthurvr** [Polymer/docs#1315]
See the beginning of this conversation at https://github.com/PolymerElements/polymer-starter-kit/issues/246. It was out of scope for PSK, but maybe we can do something in the docs.

// @addyosmani @robdodson @maria-le

**Comment by emersonbottero** [comment]
Can't the user authentication UX be an optional exactly like templates are for PSK?

**Comment by arthurevans** [comment]
Possible future addition to the PSK tutorials? @kaycebasques

**Comment by tur-ing** [comment]
Is there any authentication example out there? Can't imagine that there is no Polymer.js app which does not use authentication (OAuth2 for instance) ...

**Comment by TomGijselinck** [comment]
@tur-ing As mentioned in the starting conversation [https://github.com/PolymerElements/polymer-starter-kit/issues/246](https://github.com/PolymerElements/polymer-starter-kit/issues/246), robdodson used user auth (using firebase) in his [talk](https://youtu.be/1f_Tj_JnStA?t=20m3s) at the Polymer Summit 2015 in Amsterdam. 

@arthurvr: I think this closes this issue?
