### ISSUE TITLE
property names in example have '-' in them, but not quoted

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#1321]
I'm fairly sure property names containing '-' aren't going to work if they're not quoted.

<https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html>
<https://github.com/Polymer/docs/blob/dddf73e0dca955c0f9f3021e8850bcc9ed804cae/1.0/docs/devguide/registering-elements.md>

```
<script>

  Polymer({

    is: 'x-custom',

    hostAttributes: {
      string-attribute: 'Value',
      boolean-attribute: true
      tabindex: 0
    }

  });

</script>
```

**Comment by ebidel** [comment]
Yep. That's a mistake
