### ISSUE TITLE
cancelable referenced in Polymer.Base API docs

### ISSUE THREAD

**Issue by apowers313** [Polymer/docs#1329]
The [Polymer Base API](http://polymer.github.io/polymer/) `fire()` method makes reference to an event being `cancelable`. It appears that it has been killed off a few times ([1](https://github.com/Polymer/polymer/issues/275) [2](https://github.com/Polymer/polymer/issues/74) [3](https://github.com/dart-lang/sdk/issues/14169)), but I believed the docs and tried to use it... As mentioned elsewhere, it doesn't work. I'm happy to provide a test case if it needs further confirmation.

**Comment by apowers313** [comment]
`cancelable` also now appears in the [Utility functions](https://www.polymer-project.org/1.0/docs/devguide/utility-functions.html) page.

**Comment by arthurevans** [comment]
The bugs that you point to discuss cancelBubble, a long-gone Polymer event property, which as far as I can tell is not related to cancelable, which is a standard even property and determines whether you can preventDefault.

The code just passes this flag to the standard CustomEvent constructor:
https://github.com/Polymer/polymer/blob/453cae589a1d82331ade1ed53965d7819694eecb/src/standard/utils.html#L162

Do you have a simple reproduction case for what you're seeing?

**Comment by arthurevans** [comment]
Ping? Can you provide a repro case here?
