### ISSUE TITLE
Remove duplicated components

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1331]
_From @ebidel on September 2, 2015 5:2_

Googling "paper elements demo" produces https://www.polymer-project.org/1.0/components/paper-elements/demo.html#paper-checkbox, but the correct demo is https://elements.polymer-project.org/browse?package=paper-elements

This is no good and very confusing. We need to kill the components under 1.0, unless we're going to update them to 1.0.

_Copied from original issue: Polymer/polymer#2392_

**Comment by ebidel** [comment]
_From @arthurevans on September 2, 2015 5:10_

Already working on it ...

Those are the components the web site runs on so .. we can't get rid of them just yet ;-). But we can keep them from getting indexed.

**Comment by ebidel** [comment]
@arthurevans can we just make the includes reference the /0.5/ directory instead of being dynamic?

https://github.com/Polymer/docs/blob/master/_includes/head.html#L47

**Comment by arthurevans** [comment]
You know, we probably could. It would be nice to remove the extra set of components.

**Comment by arthurevans** [comment]
I think the search results are as fixed as we can get 'em, but we could still remove the duplicate components. Save a little time on updates.
