### ISSUE TITLE
Data binding works only if wrapped into tag elements

### ISSUE THREAD

**Issue by benediktr** [Polymer/docs#1335]
The tutorial [1] states, that the following will render the "owner" onto the page.

    <b>{{owner}}</b>

Well it does, but only, if any element tags are wrapped directly onto it.
I was about to go crazy, when I just tried polymer for the first time.

Documentation needs an update immediately!

[1] https://www.polymer-project.org/1.0/docs/start/quick-tour.html

**Comment by arthurevans** [comment]
No longer an issue as of 1.2.0. Closing.
