### ISSUE TITLE
Sass with deprecated external stylesheets

### ISSUE THREAD

**Issue by ahedderich** [Polymer/docs#1347]
since the external stylesheets feature
```
<link rel="import" type="css" href="my-awesome-button.css">
```
 is now deprecated, i wonder how to use sass compiled css in the new style modules probably.

**Comment by ebidel** [comment]
Short answer is that it's manual right now. You'd have to create a custom-style inside an import without the generate of your sass compilation. Since this is not a docs bug, I'm going to close. But I'll file a bug against core polymer. We really need a tool for this.

**Comment by ebidel** [comment]
Check out https://poly-style.appspot.com/demo/
