### ISSUE TITLE
https://elements.polymer-project.org/guides/flex-layout

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#1348]
Stuck in a javascript infinite loop (chrome)

https://elements.polymer-project.org/guides/flex-layout

**Comment by gertcuykens** [comment]
Thats weird it apparently sometimes get stuck, not always??? Do you see the flash the first halve a second too?

**Comment by arthurevans** [comment]
I haven't seen it get stuck in a loop, but I have seen a flash of weird content. @frankiefu it looks like the content's loading twice, like there's a race between two code paths that are both reacting to the URL change (or page load).

**Comment by arthurevans** [comment]
This issue was moved to Polymer/polymer-element-catalog#176
