### ISSUE TITLE
Migration guide omissions

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1356]
- Should mention that `template ref=` is not supported.
- fireAsync isn't supported. It may not be necessary, can be replaced with either `fire` or `this.async(function() { this.fire(); });` (I think).

**Comment by arthurevans** [comment]
See also: #1015. #1013.

**Comment by katejeffreys** [comment]
To help with prioritization and managing workload, I will close this issue with no docs changes in 7 days. To prevent this from happening, please comment within 7 days. Thanks!

**Comment by arthurevans** [comment]
These are from the 0.5-1.x migration guide. We aren't going to make any more changes to it at this point.
