### ISSUE TITLE
Compatibility page should include polyfill section first

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/docs#1360]
People are interpreting the chart on native support to mean that Polymer only supports Chrome:

https://www.polymer-project.org/1.0/resources/compatibility.html

The polyfill section should be first, and the compatibility matrix should be inline, not a link, to make it clear which browsers Polymer actually supports today.

**Comment by ebidel** [comment]
We should probably just have a single table, *Browser support* and have `*` that note native support for APIs. Let's lessen the distinction between native and polyfill and highlight where Polymer can be used. Yea?

**Comment by arthurevans** [comment]
Yea. Should we also include caveats for IE (support for templates inside tables, possibly other issues)?

**Comment by addyosmani** [comment]
I agree on including caveats for IE support as they otherwise need to dig into mailing lists and other issues to discover this.
