### ISSUE TITLE
'articles' mix polymer versions

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#1363]
<https://www.polymer-project.org/1.0/articles/>

includes articles for 0.5 too...seems confusing to me.

**Comment by arthurevans** [comment]
A lot of the content in the 0.5 articles is still applicable to 1.0 (for example, the unit testing story is about 90% the same for 1.0) so in the short term we've included all articles and tried to label them clearly & add disclaimers.

Now that Polymer Summit's over, we'll have a more concerted effort to update existing articles and/or remove the really outdated ones.

**Comment by davidmaxwaterman** [comment]
ok, fair enough. welcome to close this...
