### ISSUE TITLE
iOS Safari: Version-picker dropdown doesn't dismiss menu dropdown

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1367]
To reproduce:
1. Open www.polymer-project.org on iOS Safari.
2. Click the main menu dropdown (Polymer logo on the left).
3. Click the version dropdown. The main menu stays up and the version dropdown appears behind the main menu.

On Android, clicking the version picker dropdown dismisses the main menu dropdown, which seems correct.

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.
