### ISSUE TITLE
In Chrome for iOS, content pages redirect to home page

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1369]
Originally reported in a comment on Polymer/polymer#1692:

I'm checking in iPad 2, chrome browser version 45. Steps: click get started button in home page , slowly loads the get started page and redirects back to home page.https://www.polymer-project.org/1.0/

Verified in Chrome for iOS, cannot reproduce in Chrome for Android or iOS Safari.

**Comment by michael-the1** [comment]
Could this be the same as #1440 and #1460?

I'll see if I can still reproduce it later today.

**Comment by arthurevans** [comment]
New site does not have this issue.
