### ISSUE TITLE
Changing the url of guide should return either 404 or should redirect somewhere

### ISSUE THREAD

**Issue by chawlaaditya8** [Polymer/docs#1374]
when going through guides once changing the url to https://elements.polymer-project.org/guides/layout or https://elements.polymer-project.org/guides/ should either return 404 or redirect somewhere whereas  it shows following in chromium

![image](https://cloud.githubusercontent.com/assets/9032537/10268774/0a9b78fe-6ae1-11e5-9ff3-365b42dfb0ec.png)

and following in firefox developer edition
![image](https://cloud.githubusercontent.com/assets/9032537/10268804/b404d0c0-6ae1-11e5-9d29-63eae8250158.png)

**Comment by ebidel** [comment]
This issue was moved to Polymer/polymer-element-catalog#186
