### ISSUE TITLE
Bug in Website

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1377]
_From @navtejsohal7 on October 7, 2015 18:4_

![bug](https://cloud.githubusercontent.com/assets/13038162/10346243/1cd29a6c-6cfc-11e5-84dd-02f78e5f4765.png)
Hello 
There is issue on this link in textbox.
https://www.polymer-project.org/0.5/docs/start/creatingelements.html

_Copied from original issue: Polymer/polymer#2541_

**Comment by ebidel** [comment]
Given that this page is Polymer 0.5 (deprecated) and it's just a demo, I don't think it merits making the overflow fool-proof for all types of input. Thanks for the bug though.

**Comment by navtejsohal7** [comment]
Yeah but website need to be perfect because polymer is not a small thing now.
