### ISSUE TITLE
Official documentation should highlight that Chrome is currently using shady by default

### ISSUE THREAD

**Issue by antoniofontan** [Polymer/docs#1379]
I think we should be more explicit in the docs (as I was somehow surprised by the choice of default behavior in Chrome and the differences between shady and shadow).

For example, in the document [here](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html), the current statement:

"which is inspired by and compatible with shadow DOM."

Can be misleading given the incompatibilities between shadow and shady dom. We should add a reference to the [shadydom doc](https://www.polymer-project.org/1.0/articles/shadydom.html) for context.

I think we should also emphasize that developers should test their code in Chrome using both settings (shady and shadow). We should probably recommend to make shadow the default when the code has tested it (to take advantage of the performance gains in Chrome). 

Ideally we should also have a link to the [settings page](https://www.polymer-project.org/1.0/docs/devguide/settings.html) from the shadydom doc (and clarify that Chrome's default behavior is to use shady).

**Comment by antoniofontan** [comment]
It would also be good to provide a reference in the [shadydom](https://www.polymer-project.org/1.0/articles/shadydom.html) doc to the [dom API](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api) as a way to avoid boundary issues between light and local dom even when using shady dom. Ideally a simple example should be provided to illustrate the benefit.

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by arthurevans** [comment]
This is noted in the 1.x local DOM docs. It's not true anymore in 2.x (there are still differences between shady and shadow, but we don't use shady DOM by default anymore).
