### ISSUE TITLE
Declared properties: observing path changes and deep path observation code examples not working

### ISSUE THREAD

**Issue by pensierinmusica** [Polymer/docs#1384]
Hi,

I'm using `polymer` (v1.1.5) with `webcomponentsjs` (v0.7.14) in Chrome (v45).

Unless I'm missing something, it looks like the Polymer code examples provided in the "Declared properties" section, under  "[Observing path changes](https://www.polymer-project.org/1.0/docs/devguide/properties.html#observing-path-changes)"  and  "[Deep path observation](https://www.polymer-project.org/1.0/docs/devguide/properties.html#deep-observation)" are not working.

### Observing path changes
```js
Polymer({
  is: 'x-custom',
  properties: {
    user: Object
  },
  observers: [
    'userManagerChanged(user.manager)'
  ],
  userManagerChanged: function(user) {
    console.log('new manager name is ' + user.name);
  }
});
```

This is the result:
```js
document.querySelector('x-custom').user // -> 'undefined'
```

I tried to initialize it differently:
```js
Polymer({
  is: 'x-custom',
  properties: {
    user: {
      type: Object,
      value: function () {
        return {};
      }
    }
  },
  observers: [
    'userManagerChanged(user.manager)'
  ],
  userManagerChanged: function(user) {
    console.log('new manager name is ' + user.name);
  }
});
```

Now: 
```
// -> Uncaught TypeError: Cannot read property 'name' of undefined
```

And even like this:
```js
Polymer({
  is: 'x-custom',
  properties: {
    user: {
      type: Object,
      value: function () {
        return {manager: 'John'};
      }
    }
  },
  observers: [
    'userManagerChanged(user.manager)'
  ],
  userManagerChanged: function(user) {
    console.log('new manager name is ' + user.name);
  }
});
```

Result:
```js
// -> new manager name is undefined
document.querySelector('x-custom').user.manager // -> "John"
document.querySelector('x-custom').user.manager = 'Paul' // -> "Paul"
// document.querySelector('x-custom').user.manager // -> "Paul"
// The property value has been updated, but the change has not been observed and no callback has been called
```

The same holds true for the code examples in **"Deep path observation"**.

@ebidel, @arthurevans, @robdodson, @addyosmani could someone please take a look when you have a sec and let me know if I'm getting something wrong or the code examples need to be fixed? Thanks!

**Comment by samccone** [comment]
@pensierinmusica 

```
document.querySelector('x-custom').set('user.manager', 'Paul');
```

Deep path mutation F.U.N :)

**Comment by robdodson** [comment]
@arthurevans I looked at the example from https://www.polymer-project.org/1.0/docs/devguide/properties.html#observing-path-changes and it does seem a bit confusing. I actually tried to redo it in jsbin and wasn't able to make it go. Is `user` the correct argument to the change function or should it be `manager`?

**Comment by ebidel** [comment]
`user` should also have a default value: `{}`.

**Comment by arthurevans** [comment]
Sorry, this code example is just plain confused. As Rob pointed out, since the observer has a specific path, `user.manager`, the argument is just a single value -- `manager`. 

As @samccone noted, you need to use `this.set` -- or use a data binding -- to update the `user.manager` value.

... and as @ebidel noted, `user` should have a default value.

Put it all together and you get something like this:

http://jsbin.com/yakuza/4/edit?html,console,output

**Comment by pensierinmusica** [comment]
Awesome, thanks everyone for taking a look and helping out! I guess the docs should be updated. Do you want me to create a PR, or is the Polymer core team going to fix them? Cheers!

**Comment by arthurevans** [comment]
Likewise, the Deep Path Observation example shoudn't have `changeRecord.value.name ` unless the value of `manager` is another object with a `name` field. In other words, if `user.manager` is a string as in the previous example, it makes more sense for this to be `changeRecord.value`.

Rather than assume a completely different data model than the previous example, it probably makes sense to have an observer for `user.*` which can respond to changes to `user.name` or `user.manager`.

Thanks for letting us know, @pensierinmusica. I'll clean up these examples.

**Comment by pensierinmusica** [comment]
Thanks @arthurevans!  :)

**Comment by kaycebasques** [comment]
Hallo @pensierinmusica! I work with Arthur as a technical writer on all things Polymer.

Thank you for the EXCELLENT issue. Detailed and concise.

I want to take you up on your offer to contribute to the docs. If you want to get involved, please submit a PR fixing the code sample described in this issue. If you have the toolchain all set up for building and previewing the site, then please do so after you make your changes. If not, no problem! Just make the changes in the source and I'll make sure that the site builds correctly. 

My deadline to get this task complete is Fri Nov 13.

**Comment by kaycebasques** [comment]
hallo @robdodson @ebidel @arthurevans I propose to change this section title to "Observing object sub-properties"... much more straightforward to me.

**Comment by robdodson** [comment]
That sounds ok to me...

**Comment by arthurevans** [comment]
That's fine. "Observing sub-property changes" would be OK, too. We should keep the original anchor, though (`{#observing-path-changes}`) so we don't break any links.

**Comment by pensierinmusica** [comment]
Hi @kaycebasques, sorry for the late reply, I was traveling these days. Thanks for fixing it up! Is the updated version already live in the Polymer docs? I looked it up, but it seems that the old version is still there. Cheers  :)

**Comment by arthurevans** [comment]
We haven't redeployed the site yet. Soon!
