### ISSUE TITLE
Overriding Polymer.dom advice breaks all member assignment within a polymer element.

### ISSUE THREAD

**Issue by rohni** [Polymer/docs#1390]
On this page: 
https://www.polymer-project.org/1.0/docs/devguide/settings.html

There is this advice:
<img width="839" alt="screen shot 2015-10-21 at 10 55 07" src="https://cloud.githubusercontent.com/assets/839216/10632139/aea07158-77e2-11e5-874c-f1593159dafa.png">

So, we used this advice, and were creating pretty static components, nothing was noticed.  A few weeks later we created components that use data-binding.  The ```dom: shadow``` setting had been done weeks ago, and was following the docs so was forgotten about.

Suddenly, this showed up:
```Uncaught TypeError: Polymer.dom is not a function```

It turns out that any assignment to a member, i.e. this.set('author', {object}); or this.set('thing', 'value') produces this error, because Polymer.dom is now a function that is crucial for assignment functionality.

This is a pretty major change in the Polymer api, that needs to be updated in the docs as quickly as possible because it has caused us a lot of grief, and I can imagine it will do the same to others.

I am also wondering whether there should be a 1.1.x docs published and made default, as I am guessing the .1 version boost is where this happened.

This leads to another problem: with the new api, how do you force shadow dom to be used?

**Comment by arthurevans** [comment]
Are you inserting this script before you import `polymer.html`? If so, it should not cause the problems described here.

**Comment by ebidel** [comment]
I don't see this problem: http://jsbin.com/xoyipaxewo/edit?html,output

**Comment by arthurevans** [comment]
If you explicitly call `Polymer.dom`, still no issue: 

http://jsbin.com/sitigo/3/edit?html,console,output

If you swap the order of the script tag and the polymer library import, you'll see this issue:

http://jsbin.com/sitigo/4/edit?html,console,output

As the doc says, you need to configure the settings **before importing the Polymer library**.

**Comment by ebidel** [comment]
Going to close then based on the comments above. Please reopen if you still have issues.

**Comment by rohni** [comment]
Thanks for the feedback.  I am guessing that the configuration script was being executed after the import.  I would like to point out though that this practice, that seems to be growing (I see lessjs does the same thing), of using the same namespace for your configuration and then overriding it on import is a terrible practice.  Suddenly, time plays an important role in importing libraries, which is a really bad thing, esp. in a concurrent world.  JS does not support referential transparency or persistent data structures out of the box, but this does not mean that importing libraries should have side-effects.
Anyway, thanks again for the quick response and I'll be more careful about how and when our templates and modules load Polymer in the future.

**Comment by dengelke** [comment]
Looks like a bug related to these instructions is still around, looking at this [http://jsbin.com/sitigo/3/edit?html,console,output](http://jsbin.com/sitigo/3/edit?html,console,output) and [http://jsbin.com/xoyipaxewo/edit?html,output](http://jsbin.com/xoyipaxewo/edit?html,output) which worked previously (see @arthurevans and @ebidel previous responses) the error "TypeError: Polymer is not a function" is occurring in both when run.

**Comment by arthurevans** [comment]
Sorry, there were a couple of typos in the original jsbins that are either triggered by changes in the browser, changes in polygit, or both—they don't have anything to do with this setting. (You can verify this by commenting out the settings lines.)

The first problem is here: 

    <script src="http://polygit.org/components/webcomponentsjs/webcomponents-lite.min.js"></script>

This line is `http` but the Polymer import is `https`. This seems to trigger some kind of CORS error that's fixed if both URLs use HTTPS.

The second problem is here:

     <link rel="import" href="https://polygit.org/polymer/components/polymer/polymer.html">

The `polymer/` before `components` is not supposed to be in the URL. The first version of Polygit was more tolerant of poorly-formed URLs, but it looks like the new version doesn't like this URL. 

    <link rel="import" href="https://polygit.org/components/polymer/polymer.html">

Fix those two things, and the sample runs again:

http://jsbin.com/sitigo/7/edit?html,console,output

**Comment by jfrazzano** [comment]
Hi Arthur and Eric, quick question: is the above related to a "Polymer 
Polymer.telemetry.instanceCount++;
this.root = this;
this._doBehavior('created');
this._initFeatures();
}, 

which pulls an Uncaught TypeError: Polymer is not a function
followed periodically by Uncaught TypeError: Cannot read property 'instanceCount' of undefined

I traced back the issue in the work.  I was importing a clock api i built in Feb, which uses a prototype and a class slid in the script tag above a related behavior.  When I isolated the Polymer code, I thought at first that when I declared a new "TimeKeeper()", I simply didn't use a function to return some primitives so the instance count couldnt be done;  I then chopped the file down to one property in the behavior and a class with a constructor.  I was pulling the error plus, "TimeKeeper" not defined;  So then I loaded the stripped down proto in the head, I got a sort of render, and had the code officially called "jank" by chrome--brought my render from like 1-2 seconds to 6-7;

I then put the code in a separate "all my JS code" file, and while still a crummy run-time clock that needs to get shuffled off to a shared worker, the load was fine.  I guessed it was this same issue, but wasnt sure. Almost 40 elements from when I was working in the shady dom are having similar issues.  So, I figured I would check in, to see if you guys know if its the same load issue.  Confirmation would just help me not do something clearly dumb in the future.  

Thanks, in advance and again.  You guys have always been great and are much appreciated. It's a heck of a job and you do an amazing job and taming it.

sincerely, 

Jason

**Comment by arthurevans** [comment]
@jfrazzano I don't think your error is related to this original bug, which appeared to be a simple problem with ordering the scripts and imports in the head.  

It looks like something got left out of your message, above—I can't tell if the code you quoted was from Polymer or from your element. 

If you're seeing an issue and you  have a small repro case, I'd recommend opening a new bug and linking a JSBin or similar showing the problem.

Thanks,
Arthur

**Comment by jfrazzano** [comment]
Thanks Arthur, I appreciate the reply.  Looking at the code, and having isolated the offending portions, a bin would likely just waste your time, and make it all too painfully clear to me that it's best to just not write such "janky" code.  Chrome actually called it "janky"-- that's funny.  Have a good night, and again I appreciate your time and response.
