### ISSUE TITLE
Iron flex guide does not show code

### ISSUE THREAD

**Issue by hugelgupf** [Polymer/docs#1395]
I'm assuming that those grey boxes are not supposed to be empty:

![screen shot 2015-10-29 at 7 49 43 am](https://cloud.githubusercontent.com/assets/1994130/10821839/b60a2710-7e11-11e5-94e5-f924067dfc05.png)

Using up-to-date Chrome on OS X.

**Comment by jeffposnick** [comment]
FWIW, I was seeing this as well with Chrome 46 a few days ago, but I can't reproduce it now on the production site.

Running a dev version of the site, you can reproduce it by [removing the `<prism-highlighter>`](https://github.com/Polymer/polymer-element-catalog/blob/master/app/elements/pages/page-guide.html#L99) from the page. If you can reproduce this now, @hugelgupf, do you see any errors in the [Chrome DevTools console](https://developer.chrome.com/devtools/docs/console)?

![image](https://cloud.githubusercontent.com/assets/1749548/10827059/2c83f1d8-7e43-11e5-9622-d4ce1245517a.png)

**Comment by hugelgupf** [comment]
So first of all, I just opened it up again, and I cannot reproduce. Luckily, I still have the old tab open. The only thing in the console is this:

/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details. elements.build.js:40898

Is there something that processes the stuff in code tags to produce the highlighting that could be failing during BUILD? I've attached two screenshots comparing the broken/working state of a specific code tag, and it looks like on the broken one, the code that's supposed to be displayed is actually "executed". (Not sure I have the right word for this -- rendered?)
![screen shot 2015-10-29 at 10 56 30 am](https://cloud.githubusercontent.com/assets/1994130/10827402/002def4c-7e2c-11e5-8e82-6e1c11bedc64.png)
![screen shot 2015-10-29 at 10 56 15 am](https://cloud.githubusercontent.com/assets/1994130/10827404/0428c4dc-7e2c-11e5-9cea-9b0a7ea1904b.png)

**Comment by jeffposnick** [comment]
This portion of the `<page-guide>` [source](https://github.com/Polymer/polymer-element-catalog/blob/master/app/elements/pages/page-guide.html#L181) looks fishy to me: 

```js
var event = this.fire('syntax-highlight', {code: code});
if (event.detail.code && !els[i].highlighted) {
  els[i].highlighted = true;
  els[i].innerHTML = event.detail.code;
}
```

AFAIK, `this.fire()` doesn't have a return value, and doesn't do anything synchronous. It will raise an event, which is handled asynchronously by any event listeners. Unless I'm misreading things, that code will only work as expected if the [`syntax-highlight` event handler](https://github.com/PolymerElements/prism-element/blob/master/prism-highlighter.html#L56) has already run by the time the `if()` statement is encountered, so there's a race condition.

**Comment by arthurevans** [comment]
Yep, rendered is right. If you still have the bad tab open, can you try running this in the console?

    var h = document.querySelector('prism-highlighter');
    h.__isPolymerInstance__

If it returns `true`, it looks like the Prism highlighter element exists on the page and is upgraded, but didn't highlight (perhaps because of a timing issue). If it throws an error, the element is missing or hasn't been upgraded.

`fire` is synchronous and returns the custom event fired, so you can do things like:

    var event = this.fire('event-name');
    if (event && !event.defaultPrevented) { ... } 

Or words to that effect. See:

https://github.com/Polymer/polymer/blob/master/src/standard/utils.html#L212

But it occurs to me that if `contentChanged` is called before the prism-element's `attached` method, we'd see this issue, because it would never receive the event. I'm not sure whether that code path is possible, but it's worth investigating...

https://github.com/PolymerElements/prism-element/blob/master/prism-highlighter.html#L44

**Comment by hugelgupf** [comment]
Console output:

    > var h = document.querySelector('prism-highlighter');
    undefined
    > h.__isPolymerInstance__
    true

(Sorry I can't be of more help, hadn't done web dev in ages before starting with polymer.)

**Comment by jeffposnick** [comment]
Huh, I wouldn't have thought the underlying `dispatchEvent()` was synchronous, but yep, [you're right](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) @arthurevans. Sorry for the red herring!

**Comment by arthurevans** [comment]
No, that's plenty to go on. I believe it must be a timing issue. 

@jeffposnick I know, right? Need to open a bug to make that clear in the docs.

**Comment by arthurevans** [comment]
@frankiefu @blasten Weird intermittent catalog bug -- could this be a timing issue?

**Comment by arthurevans** [comment]
This issue was moved to Polymer/polymer-element-catalog#207
