### ISSUE TITLE
Port Material Design with Polymer article to 1.0

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1407]
Original (0.5 version) is here:

https://polymer-project.org/0.5/docs/elements/material.html

Notes: the current version has very brief overview of the various form elements (inputs, checkboxes, radio buttons), but doesn't talk about using them in a form, which is a source of confusion to many. `iron-form` and the (non-Polymer) `ajax-form` element can be helpful here. But validating forms can be confusing. This may merit a separate section. (In the future, form and input validation may merit a  separate guide, but it the short term we should at least throw out a sign post outlining general concepts and pointing towards the correct API docs.)

Also, the options for inputs are much more complicated now, with the  `paper-input-container` and friends. Input validation is also a little can of worms that should be touched on. (May be able to point to some of the API docs here rather than documenting everything.)

@notwaldorf is our local form and input expert. 

There are also a host of special-purpose Gold element inputs (which don't have to be described in detail here, probably, but should probably get a quick shout-out).

**Comment by arthurevans** [comment]
See also: #674, #675.

**Comment by katejeffreys** [comment]
Does this still need done?

**Comment by arthurevans** [comment]
I don't think this is in scope anymore. The elements are off on their own now (and have better API docs these days which hopefully cover use cases better). Related issues can be closed as well.
