### ISSUE TITLE
Properties: subproperties of readOnly props are not read only

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1412]
http://jsbin.com/cefupujuje/edit?html,output

You can change a subproperty of a `readOnly` object. We should not this unless it's a bug.

@kevinpschaaf this is a semantic question. I can see both ways (we allow or reject the set).

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.
