### ISSUE TITLE
Tiny addition: Compound binding to attribute value a little bit of a gotcha

### ISSUE THREAD

**Issue by tjsavage** [Polymer/docs#1413]
I understand why this is the case, but compound bindings to attribute values can be a gotcha. For example, I would naively expect this to work:

```
<dom-module id="test-compound-style">
    <template>
      <div style="color:[[color]]">Hi there, I should be red.</div>
    </template>

    <script>
      Polymer({
        is: 'test-compound-style',
        ready: function() {
          this.color = "red";
        }
      })
    </script>
  </dom-module>
```

The `style="color:[[color]]"` doesn't jump out as a binding to me, and so I don't think to add `$` to make it the correct: `style$="color:[[color]]"`. The docs correctly show an example in the Compound Bindings section that does this, but I was thinking it might be good to just explicitly call this out, that you need the `$` if you're doing a compound binding to an attribute value.

**Comment by ebidel** [comment]
Compound bindings aside, isn't this just because style is special? It's a
native property/attr.

https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#native-binding

**Comment by katejeffreys** [comment]
To help with prioritization I will close this issue within 7 days unless requested otherwise. Thanks

**Comment by arthurevans** [comment]
Yeah, I think we can close.
