### ISSUE TITLE
Update data binding docs for index/key changes to `set`, `notifySplices`, etc.

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1418]
See: https://github.com/Polymer/polymer/pull/2513/files

**Comment by kaycebasques** [comment]
- [ ] document `notifySplices`

**Comment by kaycebasques** [comment]
There's a few tasks wrapped up here...

* create docs for `notifySplices`
* create docs for using `#` to denote keys
* update `get`, `set`, `notifyPath`, all other public APIs that accept paths (?) to say that they now accept keys or indices
* figure out which other public APIs accept paths

**Comment by kaycebasques** [comment]
I don't know if I'll be able to handle this, but I've started looking into all this goodness.

**Comment by kaycebasques** [comment]
using `#` to denote keys is documented in https://github.com/Polymer/docs/pull/1457

**Comment by kaycebasques** [comment]
`notifySplices` documented in #1515

**Comment by kaycebasques** [comment]
@arthurevans the scope for the rest of this issue is hazy... I think it can be closed

**Comment by arthurevans** [comment]
Works for me. Any further changes will roll into the restructuring of the data system docs I'm working on now. Thanks!
