### ISSUE TITLE
Remove old branches

### ISSUE THREAD

**Issue by abdonrd** [Polymer/docs#1421]
I think that we can remove the old [branches](https://github.com/Polymer/docs/branches/all):

`revert-1272-esprehn-patch-1` (already merged)
`default-value` (already merged)
`1.2.0` (already merged)
`docs-1368` (already merged)
`post-summit` (already merged)
`110` (already merged)
`livestream-swap`
`revert-1346-patch-2`
`fix-webcomponents_stack.svg` (already merged)
`livestream` (already closed)
`0.8->1.0_and_implicit_change` (already merged)
`ebidel-patch-3` (already merged)
`shared-style` (already merged)
`0.5-pin` (already merged)
`summit-site`
`summit-ie-fix` (already merged)
`summit` (already closed)
`esprehn-patch-1` (already merged)
`ebidel-patch-1` (already merged)
`docs-1205` (already merged)
`custom-search`
`style` (already merged)
`post10-updates` (already merged)
`fixlink` (already merged)
`one-dot-merge` (already merged)
`observers-array` (already merged)
`apidocs_strawman` (already closed)
`menu-fix` (already merged)
`docs-1058` (already merged)
`0.9` (already merged)
`revert-1048-patch-1` (already merged)
`arthurevans-patch-1` (already closed)
`docs-989` (already merged)
`rezip` (already merged)
`element-redirect2`
`docs-837`
`ajaxify`
`mobile`

**Comment by arthurevans** [comment]
Good idea. Folks, I deleted most of the merged ones -- @ebidel @robdodson want to take a look at https://github.com/Polymer/docs/branches/all and see if you have any branches on there you're done with?

**Comment by abdonrd** [comment]
Nice @arthurevans! :smile:

**Comment by ebidel** [comment]
Got rid of mine.

**Comment by arthurevans** [comment]
Hey @robdodson I think the only stale ones we have left are some old branches of yours (mostly related to the PS site). Can you delete any we don't need?

**Comment by robdodson** [comment]
deleted em all!

**Comment by arthurevans** [comment]
Old branches deleted. Check! Like a breath of fresh air.

**Comment by abdonrd** [comment]
Nice work! Thanks @arthurevans! :)
