### ISSUE TITLE
weird view (iframe in iframe in iframe) on platinum-push-messaging page

### ISSUE THREAD

**Issue by VikramTiwari** [Polymer/docs#1425]
Page URL: https://elements.polymer-project.org/elements/platinum-push-messaging?view=demo:demo/&active=platinum-push-messaging

How to replicate:
1. go to https://elements.polymer-project.org/elements/platinum-push-messaging
2. switch to demo
3. the error gives option to go back to home page
4. on clicking home page, another instance of the same page opens up in that inner frame.
5. If you have larger screen you can keep doing it till you run out of screen space and css decides to take responsive actions

![screen shot 2015-11-11 at 18 14 34](https://cloud.githubusercontent.com/assets/1330677/11108932/4a94b2a4-88a0-11e5-9e9c-e7ba3b7dd977.png)

**Comment by arthurevans** [comment]
This issue was moved to Polymer/polymer-element-catalog#216
