### ISSUE TITLE
Behavior should be clear about how properties, observers are handled

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1426]
This is not spelled out in the current docs:

https://www.polymer-project.org/1.0/docs/devguide/behaviors.html

The current docs discuss lifecycle methods and non-lifecycle methods, but don't talk about how properties, listeners, and observers are handled.

See, for example: 

https://github.com/Polymer/polymer/issues/2371

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.
