### ISSUE TITLE
Documentation for array indexes and `Polymer.Collection`

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1427]
_From @David-Mulder on November 12, 2015 20:49_

So... after having fought with this A LOT I am just going to put a request for documentation out here:

 - What's the difference between `array.n` and `array.#m`? (I get this part, but as far as I know this isn't documented anywhere)
 - If I have `n`, how do I get `#m`? (Provided that my understanding is correct that `#m` is constant regardless of array manipulation)
 - Maybe some generic advice on when to use what and how.

_Copied from original issue: Polymer/polymer#2725_

**Comment by arthurevans** [comment]
:+1:

**Comment by robdodson** [comment]
I was actually just talking with kevin about this.

Polymer converts array.1 to array.#1 so it can have a sort of immutable
reference back to the object. That way if you move the object in the array,
array.#1 will still refer to the same item (whereas array.1 may now point
to something else).

**Comment by arthurevans** [comment]
... And I believe the answer to the second question is:

    var item = array[n];
    var key = Polymer.Collection.get(array).getKey(item);

But you should be able to call set or notify using the index and have Polymer do the right thing.

**Comment by David-Mulder** [comment]
@arthurevans Ah, it seems I actually got pretty close then. And you need it quite quickly when you're working with `Templatizer` and arrays.

**Comment by solozobov** [comment]
Seems that documentation appeared here https://www.polymer-project.org/1.0/docs/devguide/data-system#paths-to-array-items
