### ISSUE TITLE
Local DOM styling doc should cover shadow DOM styling basics.

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1438]
_From @fozziethebeat on November 18, 2015 18:10_

I'd like to specify a rule within a custom element that depends on the state of a top level element, such as body or html.  So something like this:

```
<style>
  html[dir="rtl"] #someSubElement {
  ....
  }
</style>
```

However, when doing this, polymer renames the styles for my custom element to be something like

```
html[dir="rtl"].my-custom-element #someSubElement.my-custom-element { ... }
```

Which prevents the rule from ever applying.

Is there any way to scope only part of the CSS rule to the custom element?  Otherwise this requires tagging each potential element that needs RTL information with a RTL class, which is a lot less elegant.

_Copied from original issue: Polymer/polymer#3016_

**Comment by arthurevans** [comment]
That's what the `:host-context` selector is for:

    :host-context(html[rtl]) { 
      ...
    }

**Comment by arthurevans** [comment]
_From @fozziethebeat on November 18, 2015 23:40_

That's awesome and just what I needed!

Can that be added to the basic [Styling local DOM](https://www.polymer-project.org/1.0/docs/devguide/styling.html) guide?  I discovered it's in Eric's post about [shadow dom](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/) which i never got to reading.

**Comment by arthurevans** [comment]
Absolutely should be there. Let's just move this bug over to the docs repo.

**Comment by mgiuffrida** [comment]
Ping! I only discovered this awesome feature while searching for style bugs on Polymer/polymer.

**Comment by arthurevans** [comment]
We should add a quick reference covering all of the shadow DOM specific CSS selectors, along with any Polymer/shady DOM specific caveats.

**Comment by arthurevans** [comment]
Also: the fact that inheritance is not blocked by shadow DOM is quite confusing to new users. 

We should explain that. (And why it's not such a bad thing.)

**Comment by joryphillips** [comment]
I second Arthur's Feb 10 comment. There's not much context for what :root and :host do and mean when you arrive at the [Styling](https://www.polymer-project.org/1.0/docs/devguide/styling.html) guide, and this is a bit of a barrier.

**Comment by mgiuffrida** [comment]
for some more context, I think I heard that :host-context is being deprecated. there's also a bug in :host in the shady DOM shim you might hit if you're playing with :host (Polymer/polymer#3610)
