### ISSUE TITLE
'Learn more' link on Polymer home page briefly loads tutorial page then reloads home page 

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1440]
_From @spoogle on November 21, 2015 19:36_

On chrome most recent, iOS 9.1, iPhone 5S, hitting the 'Learn more' link on Polymer home page briefly loads a page which starts loading 'Introducing Polymer 1.0' but does not fully load it and then it reloads the Polymer home page.

_Copied from original issue: Polymer/polymer#3069_

**Comment by arthurevans** [comment]
Not an issue with the new site.
