### ISSUE TITLE
Checkboxes on browser compatibility page shouldn't be toggleable

### ISSUE THREAD

**Issue by tjsavage** [Polymer/docs#1443]
https://www.polymer-project.org/1.0/resources/compatibility.html#other-features

**Comment by ebidel** [comment]
There's not toggleable for me? The checkboxes have `pointer-events: none` on them, so they shouldn't be. What browser are you seeing this in?

**Comment by robdodson** [comment]
You can still toggle them on/off using the keyboard. Though, thanks to
the egregious a11y of pre 1.0 elements, you can't actually tell if they're
focused so maybe you wouldn't think to toggle them? yay? :D

**Comment by ebidel** [comment]
Lol, I certainly didn't. We could disable them and fix the styling to not be grey.

**Comment by tjsavage** [comment]
Weird, I was seeing this in Chrome but can no longer repro. Closing here now, small issue.
