### ISSUE TITLE
hashbang line in routing.html is working inconsistently with firefox

### ISSUE THREAD

**Issue by dumbfred** [Polymer/docs#1447]

**Comment by arthurevans** [comment]
Can you add more details? What is this in reference to?

**Comment by surajwebworld** [comment]
I want swipe navigation drawer (finger swipe like goole play store)  can u any 1 help me plz i request you.

**Comment by robdodson** [comment]
@surajwebworld your comment isn't related to this thread, and you're spamming our issue trackers with the same question. Please stop.

**Comment by surajwebworld** [comment]
I am very sorry  i am trying since 4 month this swipe navigation drawer html ans scss i didn't find any solution.  I thought at list u people help me.  Sory again
