### ISSUE TITLE
Reword section on binding to native attribute using `$=`

### ISSUE THREAD

**Issue by indolering** [Polymer/docs#1448]
I just wasted a day chasing down a bug in how IE/Edge handled a binding to a numeric input field (`<input type="number" value="[[value]]">`) and I was told to use `value$="[[value]]"` instead.  However, the documentation is very confusing:

> There are **a handful** of extremely common native element attributes which can also be modified as properties. Due to cross-browser limitations with the ability to place binding braces {{...}} **in some** of these attribute values, as well as the fact that **some of these attributes** map to differently named JavaScript properties, it is recommended to always use attribute binding (using $=) when binding dynamic values **to these specific attributes**, rather than binding to their property names.

The phrasing makes it sound as if you only need to worry about the attributes listed, but that list doesn't include `value`.  Was the mistake omitting a `value` or are you supposed to use `$=` for all native attributes?

**Comment by indolering** [comment]
Cross referencing [Polylint ticket](https://github.com/PolymerLabs/polylint/issues/19) on overusing `$=`.

**Comment by indolering** [comment]
The documentation [also includes an example](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#two-way-native) of binding to `<input value="{{value}}">` sans `$`.

**Comment by arthurevans** [comment]
Following up on the other bug, but I believe the doc is right, and the information you got about using `$=` with `value` was incorrect.

**Comment by indolering** [comment]
> Following up on the other bug, but I believe the doc is right, and the information you got about using $= with value was incorrect.

There doesn't seem to be consensus on this point:

> Concluding: to prevent any exception from happening, use value$ (and for all other native attributes).

The documentation should at least state that value$ is required when specifying an input's type.

**Comment by arthurevans** [comment]
@indolering I was wrong, this is a funky edge case with IE on inputs with type set (at least to numeric).

I'd recommend using `iron-input` which gives you two-way binding, rather than `value$=`, which feels like a hack. Waiting for some clarification on the other issue, then I'll update the docs.

**Comment by indolering** [comment]
> I was wrong, this is a funky edge case with IE on inputs with type set (at least to numeric).

Yeah, we should just wait until that other discussion gets resolved.

> I'd recommend using iron-input which gives you two-way binding, rather than value$=, which feels like a hack. Waiting for some clarification on the other issue, then I'll update the docs.

I only need one-way binding and I would prefer to not import yet-another-element.  I'm already at 200+K even when minified and compressed.

**Comment by indolering** [comment]
That other discussion has been resolved.  For now we need to update the docs to mention that data binding to native input elements with a number type requires the use of `value$=` and only 1-way binding is supported:

 `<input type="number" value$=[[param]]>`

`iron-input` [will not support a numeric input type](https://github.com/PolymerElements/iron-input/issues/67) we are likely going to have to wait for a new `iron-input-number` element.

**Comment by katejeffreys** [comment]
This has been done: https://www.polymer-project.org/2.0/docs/devguide/data-binding#attribute-binding
