### ISSUE TITLE
is redefining `createdCallback` really the same as redefining `callback()`?

### ISSUE THREAD

**Issue by mercmobily** [Polymer/docs#1455]
In the [docs](https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#lifecycle-callbacks), I read:

> You can fallback to using the low-level methods if you prefer (in other words, you can simply implement createdCallback in your prototype).

Are you sure that's the case? A Polymer's element would normally have, a its `attachedCalback()`
    
    function() {
      if (this._readied) {
        this._beforeAttached();
        baseAttachedCallback.call(this);
      } else {
        this._attachedPending = true;
      }
    }

If I rewrite this, I would lose the `_beforeAttached()` as well as the check on `this._readied`. Is it really safe to rewrite this function, as stated in the documentation? If so, what are the "practical" differences between the two? (I followed what happens in Polymer's `attachedCallback()` and a few things seem to be happening, especially waiting for the element to be styled...

**Comment by arthurevans** [comment]
Yes, I think this doc is a vestige of a much earlier version of the library. @sjmiles @sorvell is @mercmobily right in thinking redefining the native callbacks (like createdCallback) will break the Polymer-specific functionality? I think so.

**Comment by arthurevans** [comment]
Testing says yes: redefining `createdCallback` breaks just about everything.

**Comment by mercmobily** [comment]
Sorry Arthur, I should have done testing and mentioned that in the first place...

**Comment by mercmobily** [comment]
Hi,

Humble comment: I would add a sentence warning people against implementing
the callbacks directly, explaining that Polymer uses them. I would also
specify which ones polymer actually redefines, and explain that in the
future it might use the other ones too so it's safer to stick to the calls
without "Callback"...

Merc.

ᐧ
