### ISSUE TITLE
Documentation for `preserve-content`?

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1462]
_From @pkaske on August 22, 2015 13:0_

I scratched my head for quite some time till I found out about the `preserve-content` attribute on  templates to keep them untouched by polymer.
Is this somewhere in the docs? I couldn't find it. If it's missing, it's maybe something worth mentioning :wink: 

_Copied from original issue: Polymer/polymer#2346_

**Comment by arthurevans** [comment]
_From @Sleeckx on August 26, 2015 14:45_

+1

Would like to know if this feature is here to stay as well.

**Comment by arthurevans** [comment]
@kevinpschaaf Is this OK to document? If so, going to move it to the docs repo.

**Comment by arthurevans** [comment]
_From @dlasky on December 10, 2015 22:42_

we would like to use this as well if its safe to do so

**Comment by arthurevans** [comment]
_From @kevinpschaaf on December 11, 2015 1:1_

Yep, let's document.

Adding `preserve-content` to a template nested within a Polymer element's top-level template will:
* prevent bindings from being parsed (and removed) from the template
* prevent special handling of nested template's `content` fragment; specifically, the `content` fragment of a nested template is normally cached by Polymer and cleared, to be handed back to the template (as `_content`) prior to `ready` time.  This is done for a number of reasons including performance (avoids the cost of unnecessarily cloning elements in nested template contents) and to avoid `HTMLTemplateElement` bugs on certain platform/versions (older Chrome versions upgraded elements in nested templates when cloning outer templates, and Safari failed to deep-clone nested template contents).

**Comment by mgiuffrida** [comment]
:+1: for documentation

**Comment by arthurevans** [comment]
Was not sure where to put this. I guess we can add it to the local DOM doc. Maybe here https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#template-stamping or more likely as a new section near the end of the doc.

**Comment by mgiuffrida** [comment]
@arthurevans That's the section I checked first. It says:

> Polymer will automatically clone this template’s contents into the element’s local DOM.

which is only 100% true if `preserve-content` is specified, so that seems like an appropriate place to document it.

**Comment by erichmx** [comment]
Definitely worth documenting, it took me 3 hours to finally find it in https://github.com/Polymer/polymer/blob/2.0-preview/src/template/annotations.html

**Comment by bedeoverend** [comment]
Also really keen on having this documented - both for 1.x and 2. Worth noting that I came across the issue during trying to wrangle with Templatizer, so might be worth adding a mention in those API docs.
