### ISSUE TITLE
Typo in Custom CSS properties section

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1465]
_From @rajikaimal on December 5, 2015 11:11_

Typo in the example section of Custom CSS properties, 

https://www.polymerproject.org/1.0/docs/devguide/styling.html#xscope-styling-details

Issue is within script tag, properties object.

_Copied from original issue: Polymer/polymer#3165_

**Comment by rajikaimal** [comment]
Great :+1:  :dancers:
