### ISSUE TITLE
Support Symbol type attributes

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1469]
_From @panuhorsmalahti on December 14, 2015 14:23_

Documentation doesn't mention if `Symbol` is a supported type for an attribute.

_Copied from original issue: Polymer/polymer#3198_

**Comment by ebidel** [comment]
Properties can be of any type, but `Symbol` can't be [de]serialized when using an attribute for initialization or during attribute reflection.

From the docs:
> The type system includes support for Boolean and Number values, Object and Array values expressed as JSON, or Date objects expressed as any Date-parsable string representation.

The docs are unclear that properties can be any JS type (including new ES6 features). I'm going to move this over there so we get it documented :)

**Comment by ebidel** [comment]
cc @arthurevans @kaycebasques

**Comment by arthurevans** [comment]
Do you mean:

1) although we only deserialize String, Boolean, Number, Object, Array and Date values, properties can be any javascript type?

2) we can deserialize some new ES6 types that we don't list?

Thanks,
Arthur

**Comment by katejeffreys** [comment]
To help with prioritization I will close this issue within 7 days unless requested otherwise. Thanks
