### ISSUE TITLE
Getting started without node etc.

### ISSUE THREAD

**Issue by tjsavage** [Polymer/docs#1470]
_From @grokys on December 16, 2015 13:44_

I have a designer colleague who wants to try out Polymer but the "Getting Started" section dives in pretty deep for him: installing node, bower, gulp and the getting the Polymer Starter Kit etc.

He wants to just download the .zip file and paste some .html to get him started. I imagine this would be common among designers. Should a small tutorial such as this be added to the "Getting Started" section? I can submit a PR if so.

In the meantime, I have created a .jsbin for him, but the roboto font isn't being applied. What am I missing? http://jsbin.com/pofatasoji/1/edit?html,output

_Copied from original issue: Polymer/polymer#3209_

**Comment by tjsavage** [comment]
_From @MeTaNoV on December 16, 2015 15:18_

Maybe he can check out the PSK light version here: https://github.com/polymerelements/polymer-starter-kit/releases/tag/v1.2.1

**Comment by tjsavage** [comment]
_From @miztroh on December 16, 2015 15:20_

@grokys Even if there was a simple zip download of Polymer and all the elements you want to use, your friend would still have to run a web server to use them.  HTML Imports don't work on file:// pages.  He'd could run a node server, or a LAMP stack, or the Chrome Dev Editor which has its own built-in server.

**Comment by tjsavage** [comment]
Moving this to the docs repo for better visibility.

At least for downloading elements without bower, the [Polymer Element Catalog](https://elements.polymer-project.org/) lets you add individual elements to a collection (by clicking the star on each element, either from the list view or on the element documentation page), and then download the entire collection as a zip file. The feature isn't terribly discoverable so we're working on a refresh of the catalog.

**Comment by grokys** [comment]
Hmm, I wasn't aware that HTML imports don't work on file:// pages. That certainly complicates things.

Maybe just providing the HTML for a fully functional jsbin would be a decent place to get started for someone who's not a developer? I tried, but I was unable to get a jsbin with proper styling, and this is as someone who's already written a reasonably complex Polymer app:

http://jsbin.com/pofatasoji/1/edit?html,output

What do I need to do to get proper styling on that?

**Comment by ebidel** [comment]
You can style it like any other element, using CSS. If you need to use paper-styles
variables, use `<style is="custom-style>`: http://jsbin.com/nataqo/edit?html,output

Also, be sure to load the polyfill with a script tag and not an import: 
`<script src="webcomponentsjs/webcomponents-lite.min.js"></script>`

For more, see:
https://elements.polymer-project.org/elements/paper-button#styling

**Comment by miztroh** [comment]
If you're not getting the font you're expecting, you can import that too.

http://jsbin.com/hequwicuca/edit?html,output

**Comment by robdodson** [comment]
@miztroh I think you have to make sure to use https with polygit.

https://jsbin.com/xaheha/1/edit?html,output

**Comment by robdodson** [comment]
or maybe i just set jsbin to always load over https in my profile settings :P

**Comment by grokys** [comment]
Ah ok, I didn't appreciate that `paper-styles` doesn't actually style the font - I assumed that was what typography.html did as it includes the line:

https://github.com/PolymerElements/paper-styles/blob/master/typography.html#L20

**Comment by grokys** [comment]
The tool that @jongeho1 pointed me to has got my colleague started. It might be worth linking to it somewhere in the "Getting Started" documentation: 

https://chrome.google.com/webstore/detail/chrome-dev-editor-develop/pnoffddplpippgcfjdhbmhkofpnaalpg

**Comment by MeTaNoV** [comment]
@grokys this might also be useful: https://codelabs.developers.google.com/polymer-summit

**Comment by arthurevans** [comment]
For learning, there's a new [Build your first element tutorial](https://www.polymer-project.org/1.0/docs/start/first-element/intro.html), which can be done entirely online using Plunker. Longer term, we're planning to add more interactive elements to the site.

However, for the use case described, maybe a 1.x version of designer is the ultimate solution. Not sure what the timeframe is on that, however. @justinfagnani ?

**Comment by BulletAnt** [comment]
@grokys 

I think that what you were looking for was something like that : https://www.youtube.com/watch?v=Ho_p4yVDTWU.

But now I think the only way to get the same basic content is like mentioned before through the light version of the PSK : https://github.com/PolymerElements/polymer-starter-kit.

Note that the CORS' "import local file" problem will occurs if your are not using a web server. An alternative (on Chrome and for testing/dev only) could be to use some flags to disable some security mechanism of your browser itself : http://codedevstuff.blogspot.com/2014/10/use-chrome-for-development-and-allow.html

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by arthurevans** [comment]
The 1.x version of the element tutorial uses Plunker so you can go through the tutorial with or without installing software. We could do that for the 2.x versions as well.

**Comment by arthurevans** [comment]
We're working on a plan to make it easier to preview stuff online, using a live editor on the page instead of having to download stuff or click through to plunker. 

We don't have any plans to deliver a zip file download, however.
