### ISSUE TITLE
Design Pattern: Designing custom element which houses only properties and no template at all

### ISSUE THREAD

**Issue by rajat1saxena** [Polymer/docs#1472]

**Comment by arthurevans** [comment]
Is this a request for documentation?

**Comment by rajat1saxena** [comment]
Yes

**Comment by katejeffreys** [comment]
To help with prioritization, I will close this issue in 7 days with no docs changes unless requested otherwise. Thanks!

**Comment by arthurevans** [comment]
This was a little vague in 1.x. Documented explicitly for 2.0: https://www.polymer-project.org/2.0/docs/devguide/dom-template#elements-with-no-shadow-dom
