### ISSUE TITLE
Date component supported by Polymer

### ISSUE THREAD

**Issue by ldtung** [Polymer/docs#1477]
Hi guys

I'm working with Polymer 1.0 but can't find any Date picker component.
Do we plan to have it in future or any alternative solution?

Thanks in advance
Tung

**Comment by ldtung** [comment]
I moved this issue to Polymer/polymer

**Comment by surajwebworld** [comment]
I want swipe navigation drawer (finger swipe like goole play store)  can u any 1 help me plz i request you.
