### ISSUE TITLE
https://elements.polymer-project.org/elements/iron-ajax#response

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#1484]
https://elements.polymer-project.org/elements/iron-ajax#response

Documents for events should mention the stuff they shuffle into `detail` for example `detail.xhr.response`

![image](https://cloud.githubusercontent.com/assets/863731/12118155/307c60ce-b3c5-11e5-8d4d-c1c5c0b642c3.png)

PS and remove the returns part 

``` Returns {url: string, method: (string|undefined), async: (boolean|undefined), body: (ArrayBuffer|ArrayBufferView|Blob|Document|FormData|null|string|undefined|Object), headers: (Object|undefined), handleAs: (string|undefined), jsonPrefix: (string|undefined), withCredentials: (boolean|undefined)} ```
 
The signature is good enough, no need to clutter the docs, just do this

```toRequestOptions() ➙ {url: string, method: (string|undefined), async: (boolean|undefined), body: (ArrayBuffer|ArrayBufferView|Blob|Document|FormData|null|string|undefined|Object), headers: (Object|undefined), handleAs: (string|undefined), jsonPrefix: (string|undefined), withCredentials: (boolean|undefined)}```

**Comment by ebidel** [comment]
This issue was moved to Polymer/polymer-element-catalog#233
