### ISSUE TITLE
Binding to text content

### ISSUE THREAD

**Issue by pensierinmusica** [Polymer/docs#1489]
Hi,

Why the code exmaple in the [binding to text content](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#binding-to-text-content) section has not been updated according to: https://github.com/Polymer/polymer/commit/b1c1b35 ?

Thanks!

**Comment by robdodson** [comment]
Just an oversight I think. Are you interested in doing a pull request to update it? I can walk you through the process if you'd like

**Comment by RyanWhite04** [comment]
Hi,
If Alessandro isn't interested in doing a pull request to update it, I
would be happy to. If I can get walked through the process.
It sounds fun.

**Comment by robdodson** [comment]
@RyanWhite04 @pensierinmusica ok if either of you wishes to work on it the file to edit is located here: https://github.com/Polymer/docs/blob/master/1.0/docs/devguide/data-binding.md

You'd just need to fork the repo by clicking the 'Fork' button in the top right of the github page, then edit that file, and push the change to your fork. After you've pushed the change, if you visit the page for your fork on github, it should show a little green button asking if you want to do a pull request. Let me know if you have any issue!

**Comment by RyanWhite04** [comment]
@robdodson 
I made the pull request, but my editor removed the space from the end of some of the lines.
Let me know if this is an issue, and i'll figure out how to stop my editor making silly assumptions and submit another pull request.
Thanks for letting me help out :)

**Comment by pensierinmusica** [comment]
Hi @robdodson and @RyanWhite04, thanks for fixing this. I'd been very happy to do it myself, or help out, but today it's been a busy day and just saw the msg. Let me know if I can do anything else, cheers!

**Comment by robdodson** [comment]
No worries @pensierinmusica! Thanks for reporting the issue :)

Closing as fixed by #1490
