### ISSUE TITLE
How to properly notify data changes between siblings in polymer

### ISSUE THREAD

**Issue by capitanbatata** [Polymer/docs#1498]
I did not find in the documents a proper way of solving the problem I describe below:
    http://stackoverflow.com/questions/34786904/how-to-properly-notify-data-changes-between-siblings-in-polymer

Maybe I'm missing something, but even if this is the case I wanted to point out that this aspect is confusing as soon as you start doing non-trivial data-binding in polymer.

**Comment by katejeffreys** [comment]
To help with prioritization, I will close this issue in 7 days with no docs changes unless requested otherwise. Thanks!
