### ISSUE TITLE
template dom-repeat: mention delay, targetFramerate, etc

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1503]
https://www.polymer-project.org/1.0/docs/devguide/templates.html doesn't mention the perf props `delay`, `intialCount`, `renderedItemCount`, `targetFramerate` etc.

http://polymer.github.io/polymer/

**Comment by addyosmani** [comment]
I had no idea those even existed. If they're sticking around would definitely be worth documenting.

**Comment by kaycebasques** [comment]
relevant properties: 

* [delay](https://www.polymer-project.org/1.0/api/#dom-repeat:property-delay)
* [initialCount](https://www.polymer-project.org/1.0/api/#dom-repeat:property-initialCount)
* [renderedItemCount](https://www.polymer-project.org/1.0/api/#dom-repeat:property-renderedItemCount)
* [targetFramerate](https://www.polymer-project.org/1.0/api/#dom-repeat:property-targetFramerate)
