### ISSUE TITLE
replace() of elements in tests breaks pattern of $$(element-name)

### ISSUE THREAD

**Issue by dagitses** [Polymer/docs#1505]
Example:

```
<dom-module is="whatever">
  <template>
    <paper-button></paper-button>
  </template>
  <script>
    Polymer({
      ready() {
        console.log(this.$$('paper-button'))
      },
    })
  </script>
</dom-module>
```

If in the test I say `replace('paper-button').with('fake-paper-button')`, then `$$` won't be able to find the paper-button child.
1. Is `$$('paper-button')` an anti-pattern?
2. I can use an ID to workaround this behavior: is that my best option? It is unfortunate to have to change my code for compatibility with a test, especially if 1) is a perfectly valid pattern.

Note that an alternative to faking that I employed before seeing the new "test your elements" page was to just redefine the element as the first thing in the test, before its official definition is seen. This ended up working just fine, except for a big ugly error logged to console when the official element is loaded.

For example:
    <link rel="import" href="deps/polymer/polymer.html">

```
<script>
  Polymer({is: 'paper-button'})
</script>

<!-- import element to test: it will use the fake paper-button defined above instead of the real deal -->
```

**Comment by robdodson** [comment]
@cdata

**Comment by arthurevans** [comment]
Ping @cdata @kaycebasques ... Thoughts on this? I think many of our tests use IDs rather than `$$`, but I'm not sure, not having any experience with `replace`.

It seems like, at the minimum, we should probably add a note to the section on using mock elements, noting that this will break code that relies on `this.$$`, `querySelector`, etc., which select on the replaced element name rather than an ID or class...

(Of course, this applies to element code as well as test code.)

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by arthurevans** [comment]
Let's keep this as an open issue, as it's a general best practices question that would apply equally to 1.x and 2.x testing.

@cdata @notwaldorf @sorvell @justinfagnani thoughts on this?

I'm thinking that `this.$$('paper-button')` seems like an anti-pattern in your element code, and you should probably use IDs or something else, the easier to replace an element with a mock. But I haven't played with mocks much. 

(And as the OP said, registering a mock before the real element is an alternative, although it's an all or nothing alternative—you can't replace a single instance of an element.)

**Comment by justinfagnani** [comment]
I'm not sure what we can do here. replace() necessarily changes the element name, if you're testing with replace() _and_ using $$, then you're not building your element to be testable via replace(). A workaround is to not hard-code the element name, but use a global/static variable that the test sets along with the replace() call.
