### ISSUE TITLE
iron-icon Demo page redirecting problem

### ISSUE THREAD

**Issue by Hunsin** [Polymer/docs#1513]
Hi, I'm not sure if its ok to issue here?
https://elements.polymer-project.org/elements/iron-icon?view=demo:demo/
When I click on "\<iron-icons\> demo" link, the new whole page loaded in the iframe, causing duplicated drawer shown on screen...
![screenshot2](https://cloud.githubusercontent.com/assets/6940170/12542280/ed77945a-c35b-11e5-9632-9eb1eac0a32c.PNG)

Same page on the other hand,  ```cart-icon[fade-out].page-element { opacity: 0;}``` makes "My Collection" button disappeared??
![screenshot1](https://cloud.githubusercontent.com/assets/6940170/12542421/f5c20134-c35d-11e5-9649-ae7f33a5d050.PNG)

**Comment by arthurevans** [comment]
This issue was moved to Polymer/polymer-element-catalog#237
