### ISSUE TITLE
Remove mention of using `a.b` syntax in `listeners`?

### ISSUE THREAD

**Issue by kaycebasques** [Polymer/docs#1516]
> You can also add an event listener to any element in the `this.$ collection` using the syntax `nodeId.eventName`.

https://www.polymer-project.org/1.0/docs/devguide/events.html#event-listeners

It looks like that syntax is a [target for deprecation](https://github.com/Polymer/polymer/blob/master/src/standard/events.html#L58).

**Comment by mercmobily** [comment]
Before removing it, I would make sure it will be deprecated -- and how. I don't think having `listeners` without `a.b` makes all that much sense. I am curious to see what Steve says...

**Comment by katejeffreys** [comment]
To help with prioritization, I will close this issue in 7 days with no docs changes unless requested otherwise. Thanks!

**Comment by mercmobily** [comment]
Quick questions:

1) Was this deprecated in Polymer 2? If so, I couldn't see a note about it in the Upgrade guide: https://www.polymer-project.org/2.0/docs/upgrade

2) OR is the syntax actually still available? If so, there is no mention on it in the official Polymer 2 documentation: https://www.polymer-project.org/2.0/docs/devguide/events (while there IS in the old docs)

I think either (1) (fixing upgrade guide)  or (2) (documentation) should be addressed.

Merc.

**Comment by arthurevans** [comment]
It's just a bullet point in the "removed APIs" section.

https://www.polymer-project.org/2.0/docs/upgrade#removed-apis

**Comment by mercmobily** [comment]
Sorry Arthur, I was looking for the string "event" and missed it!
