### ISSUE TITLE
build warnings / errors when modules / plugins not found?

### ISSUE THREAD

**Issue by kaycebasques** [Polymer/docs#1520]
Is there a way to get the build to fail when a module / plugin (not sure what the correct term is here) is not found?

I was just writing some docs and inserted `{{site.project_tite}}` (should have been `{{site.project_title}}`). Would have failed silently had I not caught it while manually reviewing the local preview.

**Comment by arthurevans** [comment]
It doesn't look like there's an easy way to do this. It sounds like it may be on the roadmap for Liquid 3, but we're using 2.6.2 in the current site. It should be possible in Django, however, which we were looking at for our next-gen site.
