### ISSUE TITLE
The x-custom example element in the styling chapter is wrong and doesn't work with previous my-toolbar

### ISSUE THREAD

**Issue by mercmobily** [Polymer/docs#1532]
The current x-custom element is at the moment:

```
<dom-module id="x-custom">

  <template>

    <style>
      :host {
        --my-toolbar-color: red;
      }
    </style>

    <my-toolbar>My awesome app</my-toolbar>
    <button on-tap="changeTheme">Change theme</button>

  </template>

  <script>
    Polymer({
      is: 'x-custom',
      changeTheme: function() {
        this.customStyle['--my-toolbar-color'] = 'blue';
        this.updateStyles();
      }
    });
  </script>

</dom-module>
```

The documentation doesn't explain which version of my-toolbar should be used. Most readers will work out that it's the first version (although it should be specified).

```
<dom-module id="my-toolbar">

  <template>

    <style>
      :host {
        padding: 4px;
        background-color: gray;
      }
      .title {
        color: var(--my-toolbar-title-color);
      }
    </style>

    <span class="title">{{title}}</span>

  </template>

  <script>
    Polymer({
      is: 'my-toolbar',
      properties: {
        title: String
      }
    });
  </script>

</dom-module>
```

However, as it is in the docs `x-custom` won't work because:

1) The local DOM needs to be <my-toolbar title="..."> since my-toolbar expects the `title` attribute and does binding

2) The custom property is actually called `--my-toolbar-title-color` and not `--my-toolbar-color`. So the correct `x-custom` that works is:

```
<dom-module id="x-custom">

  <template>

    <style>
      :host {
        --my-toolbar-title-color: red;
      }
    </style>

    <my-toolbar title="My awesome app"></my-toolbar>
    <button on-tap="changeTheme">Change theme</button>

  </template>

  <script>
    Polymer({
      is: 'x-custom',
      changeTheme: function() {
        this.customStyle['--my-toolbar-title-color'] = 'blue';
        this.updateStyles();
      }
    });
  </script>

</dom-module>
```

I would:

1) Explain which version of `my-toolbar` this widget will work on (the attribute version, first one in the doc, rather than the mixin one)

2) Replace the current (broken) `x-custom` widget with working one.

I am surprised nobody else has reported this -- anybody reading the documentation and actually running the example code (as we should all do) would have spotted this!

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by arthurevans** [comment]
Still true in the 1.x docs. I don't think this is still true in the new 2.x styling docs.

**Comment by mercmobily** [comment]
OK, considering it fixed.
