### ISSUE TITLE
The examples in events.html, gestures section, don't do anything with this.message

### ISSUE THREAD

**Issue by mercmobily** [Polymer/docs#1539]
Hi,

Have a look at the code example here: https://www.polymer-project.org/1.0/docs/devguide/events.html#gestures

The example currently sets this.message, but never does anything with it (!). Either we use `console.log`, or a `message` property that gets bound to the template.

If you go for the second choice, here is the code I propose. If it looks good to you, I will create a PR. If I am missing something, please say so :dancer: 

````
<dom-module id="drag-me">

  <template>

    <style>
      #dragme {
        width: 50px;
        height: 50px;
        background: gray;
      }
    </style>

    <div id="dragme" on-track="handleTrack"></div>
    <p>{{message}}</p>

  </template>

  <script>

    Polymer({

      is: 'drag-me',
      properties: {
        message: String
      },
      
      handleTrack: function(e) {
        switch(e.detail.state) {
          case 'start':
            this.message = 'Tracking started!';
            break;
          case 'track':
            this.message = 'Tracking in progress... ' +
              e.detail.x + ', ' + e.detail.y;
            break;
          case 'end':
            this.message = 'Tracking ended!';
            break;
        }
      }

    });

  </script>

</dom-module>

**Comment by arthurevans** [comment]
Hi Merc,

Yep, you're right. This is actually a formatting bug. If you edit that section, you'll see the text looks like this:

        <div id="dragme">{{message}}</div>

However, these brackets get eaten by Jekyll. Wherever we include bindings
in code examples in the site, we need to escape them like this:

        <div id="dragme">{%raw%}{{message}}{%endraw%}</div>

Can you do a PR?

**Comment by mercmobily** [comment]
Hi,

I was about to do a PR but then noticed that you have already made the change?
No need for a PR right?

Merc.

**Comment by arthurevans** [comment]
Hey Merc. Yeah, @lozandier beat you to it :D ...

**Comment by mercmobily** [comment]
That is SO not fair! I was asleep, I am in AUSTRALIA!!! :D
