### ISSUE TITLE
Small additions to the behaviors chapter 

### ISSUE THREAD

**Issue by mercmobily** [Polymer/docs#1544]
Three small additions to the chapter:

1)
It's very neatly explained that:

> For lifecycle events, the lifecycle callback is called for each behavior in the order given in the behaviors array, followed by the callback on the prototype.
> 
> Any non-lifecycle functions on the behavior object are mixed into the base prototype, unless the prototype already defines a function of the same name. If multiple behaviors define the same function, the last behavior in the behaviors array takes precedence over other behaviors.

What about other non-Polymer **objects** added to the behavior?  

And what about  `hostAttributes`, `properties`, `observers`, `listeners`?  My understanding is that they are not mixed in to the object: they are dealt with by Polymer sort of "by hand", on a case-by-case basis. But... are they? Should we say here "Polymer will treat properties in the `listeners` object  found in behaviors as if they were in the element itself". Or something like this...  To explain that Polymer actually actively goes through the behaviours array when the object is created.

2)
[DELETED]

3)
In the doc, you write:

> Behaviors created by the Polymer team are added to the Polymer object.

Can you give us some examples/links? They are rather obscure like this. I wonder if this is leftover from the 0.5 days?

4)
In the doc, you write:

> As with the element’s behaviors array, the rightmost behavior takes precedence over behaviors earlier in the array. In this case, anything defined in NewBehaviorImpl takes precedence over anything defined in OldBehavior.

My issue here is that the sentence " anything defined in NewBehaviorImpl takes precedence over anything defined in OldBehavior." is only kind-of true: the way behaviors are overridden is a little more complex than that (lifecycles calles are called in order, non-lifecycle calls are overridden by the latest behaviour, and Polymer-specific objects are dealt with... blah blah).

I think it would be better to explain that:

"Assigning a composite behavior to an element is the equivalent of assigning to the element the single behaviours that make up the composite one, in the same order"

Or something along those lines.   

5)
In the section "Performing work at registration time". You lost me here. Completely. The first problem is that I don't know the `iron-a11y-keys-behavior` element _at all_. [The documentation of it](https://github.com/PolymerElements/iron-a11y-keys-behavior)  tells me that:

> Use the keyBindings prototype property to express what combination of keys will trigger the event to fire.

OK, so this means that I will simply add a `keyBindings` attribute to my element. Fine.
But then...

>  A single element could potentially have multiple keyBindings objects, one from its own prototype and several inherited from behaviors.

...?!? So, I can set keyBindings in behaviours as well...? It's not documented in `iron-a11y-keys-behavior` at alThe actual code:

```
   _collectKeyBindings: function() {
        var keyBindings = this.behaviors.map(function(behavior) {
          return behavior.keyBindings;
        });
```

Actually _actively_ look into the `behavior` array. So, this behaviour effectively look into the `behaviors` array looking for `keyBindings`. Shouldn't this be documented in `iron-a11y-keys-behavior`?

I think this section should be much clearer: are you writing this as an example of a behaviour that adds a feature to the `behaviours` array itself? Is it possible to show a simpler example? And, should the  fact that `keyBindings` can be set in `behaviors` be documented?

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by mercmobily** [comment]
Docs have been rewritten, closing.
