### ISSUE TITLE
Dom-if and dom-repeat documentation

### ISSUE THREAD

**Issue by ellenaua** [Polymer/docs#1548]
Description of "dom-if" and "dom-repeat" is missing in developer documentation, or I just cannot find it? 
If it's missing, then I propose to add it. 
Into which article it's better to add it, "local dom" is OK? 
https://github.com/Polymer/docs/blob/master/1.0/docs/devguide/local-dom.md

**Comment by MeTaNoV** [comment]
https://www.polymer-project.org/1.0/docs/devguide/templates.html

**Comment by ellenaua** [comment]
Found it =) thx

**Comment by MeTaNoV** [comment]
ne za chto!
