### ISSUE TITLE
paper-header-panel demo in the guideline isn't working

### ISSUE THREAD

**Issue by blasten** [Polymer/docs#1552]
The demo https://elements.polymer-project.org/guides/assets/tall-header.html isn't currently working.  I believe it needs to import `classes/iron-flex-layout.html`

**Comment by arthurevans** [comment]
I think these are the samples from your guide. They should be updated for the new `iron-flex-layout-classes.html` import: https://elements.polymer-project.org/guides/flex-layout

**Comment by katejeffreys** [comment]
Superseded by webcomponents.org
