### ISSUE TITLE
Should include some guidance against dynamically generating templates

### ISSUE THREAD

**Issue by tjsavage** [Polymer/docs#1555]
Dynamically generating templates for Polymer elements on the server, especially if the dynamically generated template uses user-provided data inside of a binding, can open up potential XSS holes.

For example, if on the server a template is generated for a Polymer element that looks something like this:

```
<template>
  <div><%= request.query.val %></div>
</template>
```

Even if the user-provided `request.query.val` is HTML-encoded, a value of something like:

`{{insertAdjacentHTML('beforebegin','<audio src="foo" onerror="alert(1)"></audio>')}}`

Would be an example of an XSS vulnerability.

We should add a few lines that specifically recommend against dynamically generating templates on the server - perhaps somewhere around here:

https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#template-stamping

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.
