### ISSUE TITLE
quick tour doesn't explain how to install iron-input into bower

### ISSUE THREAD

**Issue by azakus** [Polymer/docs#1559]
_From @hanwen on February 25, 2016 10:56_

 https://www.polymer-project.org/1.0/docs/start/getting-the-code.html says "For this reason we recommend starting with Bower if possible."

and https://www.polymer-project.org/1.0/docs/start/quick-tour.html has examples with bower_components hrefs, but the example "editable-name-tag" uses iron-input, and that is not installed by default. This is especially confounding because there is no error message; the widget just doesn't behave as expected. 

I finally figured it out, and I could work out what to do using https://elements.polymer-project.org/guides/using-elements#installing-with-bower, but Getting started should include a note.

_Copied from original issue: Polymer/polymer#3471_

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.
