### ISSUE TITLE
Deprecated components used in 1.0 docs

### ISSUE THREAD

**Issue by mjames-upc** [Polymer/docs#1565]
I find it curious that documentation about Polymer 1.0 uses 0.5-specific component. [docs/1.0/elements/docs-menu.html](https://github.com/Polymer/docs/blob/master/1.0/elements/docs-menu.html): core-menu/core-submenu

From https://github.com/Polymer/core-menu

> This element is compatible with Polymer 0.5 and lower only, and will be deprecated.

**Comment by robdodson** [comment]
Yep we're working on completely redesigning the site with 1.0 stuff
