### ISSUE TITLE
Komponenten zeigen gelöschte Seiten

### ISSUE THREAD

**Issue by doitlikeaninja** [Polymer/docs#1576]
Die Komponenten zeigen Relationen zu gelöschten Seiten ...

![image](https://cloud.githubusercontent.com/assets/1805182/13455305/ca2b5658-e05c-11e5-93ed-206c561dd854.png)

**Comment by robdodson** [comment]
This... looks like Twitter Bootstrap. Translating your comment "The components show relationships to deleted pages") I'm not sure how that applies to our docs...

**Comment by doitlikeaninja** [comment]
Oh sorry, tired posted in the wrong repository. Big sorry for that!!!
