### ISSUE TITLE
Style guide not consistent with flex-layout guide

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1579]
_From @gertcuykens on March 3, 2016 19:22_

https://www.polymer-project.org/1.0/docs/devguide/styling.html
`Polymer uses Shadow DOM styling rules for providing scoped styling of the element’s local DOM. Scoped styles should be provided via <style> tags placed **inside** the element’s local DOM <template>.`

https://elements.polymer-project.org/guides/flex-layout

That seems like outside to me :p

_Copied from original issue: Polymer/polymer#3493_

**Comment by katejeffreys** [comment]
Fixed by https://github.com/Polymer/polymer-element-catalog/commit/e2b19b696850606109d9256fa31ffdad0cc2691b
