### ISSUE TITLE
Wait time units

### ISSUE THREAD

**Issue by redbassett** [Polymer/docs#1580]
In the page for [utility functions](https://github.com/Polymer/docs/blob/master/1.0/docs/devguide/utility-functions.md), multiple methods have a `wait` argument, however the associated `wait time` in the description for those methods doesn't include a unit of time. Does a `wait time` of `1` mean 1 second or 1 millisecond?

**Comment by robdodson** [comment]
1 millisecond. If you're interested in opening a PR to add a description for the unit of time we can help you with that

**Comment by redbassett** [comment]
(Rhetorical question at the end there.)

Unless anyone else really wants to jump on that, I'll look into a PR when I get a chance!

**Comment by arthurevans** [comment]
That would be cool. Long term we should do something more useful with that chapter, which was originally added before we had any API docs.

Ideally these should now link to the API docs. For example, a link to the API docs for `listen` should look like this:

    [`listen`](/{% polymer_version_dir %}/api/#Polymer.Base:method-listen){:target="api"}

**Comment by katejeffreys** [comment]
Page no longer exists
