### ISSUE TITLE
API Docs: Change section Listbox to visible navigation

### ISSUE THREAD

**Issue by kbenjamin** [Polymer/docs#1585]
Until Polycasts 43, I hadn't realized there was more than one section in the [API docs](https://www.polymer-project.org/1.0/api/). 

Please put some simpler navigation in place than a pull-down listbox. Simple links would be fine as there are only 8 choices.

At minimum, please style the listbox such that there is more than a small triangle as evidence that there might be more choices. Colors, borders, something!

**Comment by arthurevans** [comment]
This issue was moved to PolymerElements/iron-component-page#96
