### ISSUE TITLE
Registration chapter should mention upgrades & lazy registration

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1587]
I started writing a thing:
### Element upgrades

If the browser parses an element instance before the element name has been
registered, the element is created as an instance of `HTMLElement` (or in the
case of type-extension elements, as an  instance of whatever native class is
being extended). When the element name is registered, the browser _upgrades_
existing instances of the element, giving them the correct prototype chains and
invoking their lifecycle callbacks.

Should also probably discuss using this for performance, and how you need to 
style the un-upgraded elements as regular HTML elements or otherwise prevent FOUC.

See also the notes on lazy registration in the release notes.

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by arthurevans** [comment]
2.x docs discuss upgrades, and lazy registration is not a thing in 2.x. I think in as much as this applies to 1.x, we can close it as will-not-fix.
