### ISSUE TITLE
Property naming conventions are not obvious in docs.

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#1589]
_From @zhaoz on March 16, 2016 1:22_

The docs do not mention property naming conventions and requirements for properties.

We have broken on things such as naming a property 'FPS', this is not allowed but it is not obvious to all developers.

It would be valuable to have this mentioned in the docs on polymer-project.org

_Copied from original issue: Polymer/polymer#3511_

**Comment by ebidel** [comment]
_From @TimvdLippe on March 21, 2016 17:8_

The property name `FPS` is actually allowed, but the implementation broke the code. https://github.com/Polymer/polymer/pull/3501 fixed that. Other than that, any docs updates are @arthurevans ' duty at https://github.com/Polymer/docs

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.
