### ISSUE TITLE
no Doc for strip-whitespace

### ISSUE THREAD

**Issue by MeTaNoV** [Polymer/docs#1593]
just stumble upon it in some code, and after some search (https://groups.google.com/forum/#!topic/polymer-dev/uo4HiOJJ0gw), found the reason. 
I think it would be nice to have a word on it somewhere since this is an optIn optimization.

**Comment by arthurevans** [comment]
Weird. It's documented here:

https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#strip-whitespace

But as you said, it's not showing up in site search for me, either. It's comparatively new, so perhaps the crawler just hasn't revisited this page yet.

**Comment by MeTaNoV** [comment]
oh yeah... sorry to have missed it... I though it would appear as you said in the search result! Thanks for pointing out!
