### ISSUE TITLE
www.polymer-project.org/1.0/api/ takes 13 sec to load

### ISSUE THREAD

**Issue by dman777** [Polymer/docs#1600]
www.polymer-project.org/1.0/api/ takes 13 sec to load. Could a spinner be used or somehow optimize this page loading times?

**Comment by arthurevans** [comment]
Yeah, we should be able to speed this up a lot. At the moment, it's building the docs on the fly every time you load. If you leave an API docs tab open, the site will just switch to the selected API in the open tab, which is much faster. This is a hack, but it's available now.

We are working on a larger update to the site, and hopefully can roll this fix in when we do.

**Comment by dman777** [comment]
:+1: Sweet, thanks! :)

**Comment by arthurevans** [comment]
Fixed in the new site version.
