### ISSUE TITLE
"Local DOM Basics and API" needs to better explain the basics

### ISSUE THREAD

**Issue by c1051** [Polymer/docs#1606]
"Local DOM Basics and API" needs to better explain the differences between Local vs Light vs Shadow vs Shady vs the document’s DOM. Although these are introduced as concepts, the differences between them are not clear. After reading through the doc several times, and referring back to it several more times, I found it not helpful in constructing a mental model to help me write code. I ended up coding by trial and error, and this is not a good way to work. These differences are critical, yet are covered by only 3 short paragraphs. (At this point, although I now have several complex Polymer elements working, I still don't think I could write the docs.)

Questions the intro should cover:
- Given an arbitrary element, which DOM is it in? Which CSS rules apply?
- When to use Polymer.dom()? When not to? Why?
- How will child elements in the document's DOM interact with my Polymer element?

I suggest expanding the section considerably and that diagrams might be useful.

**Comment by arthurevans** [comment]
Yes, we need to add a local DOM concepts doc. The existing docs assumed a familiarity with shadow DOM that most people just don't have. And unfortunately, the sources we used to link out to are either out of date (HTML5Rocks articles) or they've been updated to the shadow DOM v1 spec that we don't support yet (W3C).

**Comment by katejeffreys** [comment]
To help with prioritization and managing workload, I will close this issue with no docs changes in 7 days. To prevent this from happening, please comment within 7 days. Thanks!

**Comment by c1051** [comment]
I think the issue should remain open. A quick summary of the issues and
definitions of terms would be invaluable. There is no need to
reproduce the HTML5Rocks
articles.

**Comment by katejeffreys** [comment]
Thanks for the input! I will leave it open and see what I can do.

**Comment by arthurevans** [comment]
@c1051 have you looked at the 2.0 shadow DOM concepts doc? It's oriented to shadow DOM v1, but goes into much more depth than the 1.x docs... Wondering if that has what you're looking for.

**Comment by c1051** [comment]
Yes, that looks good, thanks. First time I've seen that doc as I'm still on
1.x.

**Comment by katejeffreys** [comment]
Thanks both. @c1051 I did not realize that was the doc you wanted, sorry.

Is this issue now resolved for you?

**Comment by c1051** [comment]
For me, yes, thanks.

I think it would be useful for others still on 1.x to add a note to the 1.x
Local DOM Basics and API page that this new doc is available with
significantly more information.
