### ISSUE TITLE
Iron flex-layout documentation has empty sections

### ISSUE THREAD

**Issue by powdercloud** [Polymer/docs#1608]
https://elements.polymer-project.org/guides/flex-layout

It looks like something went wrong here, I see several empty sections. E.g., there's a gray empty section after "Then include the module(s) that you need:". Thanks much for looking into it.

**Comment by powdercloud** [comment]
Weird, this went away after reloading. Perhaps a corrupt cache or similar, or it got fixed. Closing - sorry about bothering anyone here.

**Comment by arthurevans** [comment]
Sorry about that--this is a known but transient timing issue that we've had a hard time reproducing consistently. Can you let us know what browser and OS you saw it on?

Thanks!

**Comment by powdercloud** [comment]
This was Chrome 49.0.2623.87 (Official Build) (64-bit) on my developer workstation running Goobuntu.

**Comment by powdercloud** [comment]
Just saw it again in 50.0.2661.86 (Official Build) (64-bit).
