### ISSUE TITLE
undocumented: `fullbleed` requires `iron-positioning` style module

### ISSUE THREAD

**Issue by tony19** [Polymer/docs#1610]
The [docs for **Full Bleed**](https://elements.polymer-project.org/guides/flex-layout#full-bleed-lt-body-gt-) do not state that the `iron-positioning` style module is required, making it difficult to determine how to use it. I'd submit a pull request, but I can't find the source for that page. I was able to find one incorrect example in the [Migration Guide](https://github.com/Polymer/docs/commit/f73b1a88a28491f6c64304fd3c9a823356cf1d9e?diff=unified#diff-40fb74a27ef06c86d2f8816e0f9a0a6bR799), where `iron-flex-alignment` is specified instead of `iron-positioning`.

**Comment by tony19** [comment]
@arthurevans Where can I find the source for the [layout guide](https://elements.polymer-project.org/guides/flex-layout#full-bleed-lt-body-gt-)?

**Comment by arthurevans** [comment]
@tony19 you can find it at https://github.com/Polymer/polymer-element-catalog/blob/master/guides/flex-layout.md

Thanks!

**Comment by tony19** [comment]
Closed as part of #1611. The layout guide will be fixed in https://github.com/Polymer/polymer-element-catalog/issues/273.
