### ISSUE TITLE
Request: Use Cases list for each feature

### ISSUE THREAD

**Issue by myuseringithub** [Polymer/docs#1612]
The documentation should give more Use Cases for implementing diffrent available functions. List of use cases for each feature which are explained briefly seperately.
E.g. what is the use case for the custom constructor "factoryImpl" ? Why not configure element using ready function instead ?

**Comment by katejeffreys** [comment]
To help with prioritization and managing workload, I will close this issue with no docs changes in 7 days. To prevent this from happening, please comment within 7 days. Thanks!
