### ISSUE TITLE
[new site] "Edit on Github" link 404s; double check they point to the right repo when public

### ISSUE THREAD

**Issue by alancutter** [Polymer/docs#1622]
The docs have an "Edit on Github" link that goes to a non-existent project.
Example docs page: https://www.polymer-project.org/1.0/docs/devguide/events
Corresponding broken link: https://github.com/Polymer/docs2/edit/master/app/1.0/docs/devguide/events.md

**Comment by arthurevans** [comment]
Sorry about that. We need to merge the new site into master. It's going to take a day or two to fix. Please stand by!

**Comment by dandv** [comment]
Seeing the same error at https://www.polymer-project.org/1.0/start/psk/deploy

**Comment by alancutter** [comment]
I recommend removing the links until they're ready to serve publicly.

**Comment by notwaldorf** [comment]
(updating the description to match taylor's)
