### ISSUE TITLE
No reference for Polymer's Event object

### ISSUE THREAD

**Issue by alancutter** [Polymer/docs#1623]
The [events](https://www.polymer-project.org/1.0/docs/devguide/events) documentation describes how to listen and fire events but says nothing about what event handlers receive.
A reference for the interface Polymer event objects implement would be very helpful.

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.
