### ISSUE TITLE
Feature overview line length is too long

### ISSUE THREAD

**Issue by ericjim** [Polymer/docs#1624]
Refer to the [`Feature overview`](https://www.polymer-project.org/1.0/docs/devguide/feature-overview), the line length of the documentation is really long on my 15in MacBook Pro. Similarly, if you look at [`Register an element`](https://www.polymer-project.org/1.0/docs/devguide/registering-elements), you'll notice that the line length is shorter given the presence of the `Table of contents`; thereby improving readability.

I propose we add additional margin to the right-hand side of the content area to decrease the line length of the [`Feature overview`](https://www.polymer-project.org/1.0/docs/devguide/feature-overview) page.

(Btw, Love the new design 👍 )

**Comment by ericjim** [comment]
[`Gesture events`](https://www.polymer-project.org/1.0/docs/devguide/gesture-events) seems to have long lines as well.

**Comment by notwaldorf** [comment]
Ah yeah, this happens because all the other pages have a 300px table of contents on the side, and those ones don't. My bad, fixing!

(Thanks!)
