### ISSUE TITLE
Multi-paragraph cells in borderless table are not user friendly

### ISSUE THREAD

**Issue by tony19** [Polymer/docs#1626]
The borderless tables make multi-paragraph cells difficult to understand. For example, in this screenshot of the [Lifecycle callbacks docs](https://www.polymer-project.org/1.0/docs/devguide/registering-elements#lifecycle-callbacks), it's hard to tell where the documentation for each callback begins or ends.

![screen shot 2016-05-22 at 4 48 34 pm](https://cloud.githubusercontent.com/assets/26580/15456682/137c7ede-203d-11e6-8548-955667430b6a.png)

This could be improved with some CSS, such as:

```css
table td {
  border-top: 1px solid lightgray;
  vertical-align: top;
}
```

which is shown in this screenshot:

![screen shot 2016-05-22 at 4 53 25 pm](https://cloud.githubusercontent.com/assets/26580/15456699/d03ff1cc-203d-11e6-9c58-d066d684c465.png)

**Comment by tony19** [comment]
I found the [styles for `td`](https://github.com/Polymer/docs/blob/master/sass/site2.scss#L105-L110), but given that it already has `vertical-align: top` and that the `grunt`-generated site doesn't resemble today's revamped site, I'm guessing this is the wrong file. Maybe I'm on the wrong branch, or I'm using the wrong `grunt` command.

How do I generate the new docs site?

**Comment by arthurevans** [comment]
/cc: @notwaldorf seems like a good suggestion to me.

@tony19 we need to fix up a few more things then the revamped site will be merged in as the master branch here.

**Comment by notwaldorf** [comment]
Yup, agreed! Will make this change, thanks!

**Comment by abdonrd** [comment]
@arthurevans where is the new docs branch?

**Comment by notwaldorf** [comment]
The new docs site is still in a private repo (just because we're figuring out how to merge the previous site/current site's issues and history) -- hopefully this will be sorted out soon.
