### ISSUE TITLE
[new site] All the blog posts has the same title

### ISSUE THREAD

**Issue by abdonrd** [Polymer/docs#1632]
The News section always has the same title metatag: **News - Polymer Project**.

<img width="740" alt="screen shot 2016-05-28 at 01 38 38" src="https://cloud.githubusercontent.com/assets/1007051/15623522/f5f82a34-2474-11e6-9fae-1b2d375fc18d.png">

I think it will have the post title.

**Comment by abdonrd** [comment]
Big problem sharing the links:

<img width="544" alt="screen shot 2016-05-28 at 01 39 59" src="https://cloud.githubusercontent.com/assets/1007051/15623541/243454f4-2475-11e6-9ac4-4fa2d2694e84.png">

**Comment by notwaldorf** [comment]
Oh argh, you're totally right. Thanks, will fix.

**Comment by abdonrd** [comment]
@arthurevans you haven't done the deploy, right?

**Comment by arthurevans** [comment]
@abdonrd That's right. It'll get fixed the next time we push the site—probably in the next day or two. Hoping to get a few more fixes in before we push again.

**Comment by abdonrd** [comment]
Got it! Thanks @arthurevans! 😃
