### ISSUE TITLE
download tab disappear if too many elements are selected

### ISSUE THREAD

**Issue by ventrebleu** [Polymer/docs#1650]
Hello!

On https://elements.polymer-project.org/browse?package=paper-elements if you select too many elements (so there're more than the viewport can display), the Download tab disappear. 
![v3svsczizpp](https://cloud.githubusercontent.com/assets/2122637/15877593/a5e9c8f6-2cc9-11e6-81c5-e058fe95c99e.png)

**Comment by arthurevans** [comment]
This issue was moved to Polymer/polymer-element-catalog#280
