### ISSUE TITLE
properties are shown as functions

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/docs#1654]
for example, `domHost` is a getter:
https://github.com/Polymer/polymer/blob/edb59eb6283074ce54f374b30b884c9f9fcf9f5f/src/mini/shady.html#L101

but is described as a `domHost()` rather than `domHost` under Properties:
https://www.polymer-project.org/1.0/docs/api/Polymer.Base#property-domHost

Is this conventional? I see that and think it's a function (since I don't immediately see the Properties header), so I would expect it to be named `domHost`.

**Comment by arthurevans** [comment]
Sorry, it's a shadow DOM styling issue, believe it or not: https://github.com/PolymerElements/iron-doc-viewer/issues/88

**Comment by mgiuffrida** [comment]
Hah, that's awesome. Closing, then.
