### ISSUE TITLE
Demo code trip-up

### ISSUE THREAD

**Issue by kevinSuttle** [Polymer/docs#1662]
Following the demo tutorial here: https://www.polymer-project.org/1.0/start/first-element/intro

The CLI reports that PolyServe is running at
`http://localhost:8080/components/icon-toggle/`

<img width="853" alt="screen shot 2016-06-21 at 10 30 05 am" src="https://cloud.githubusercontent.com/assets/95672/16233149/5e5a70e4-379b-11e6-867c-bd9c92b5c0b5.png">

but opening that up, or any permutation of the URL doesn't render. Just a `not found`. 

<img width="432" alt="screen shot 2016-06-21 at 10 30 15 am" src="https://cloud.githubusercontent.com/assets/95672/16233161/68af04ce-379b-11e6-9c1f-fc85019e0b66.png">

<img width="588" alt="screen shot 2016-06-21 at 10 28 34 am" src="https://cloud.githubusercontent.com/assets/95672/16233067/07611a72-379b-11e6-9140-129ec0a0a411.png">

There are no `npm` or `bower install` steps, so that's not it. ¯_(ツ)_/¯

Er, so this `localhost:8080/components/icon-toggle/demo/` works, as mentioned in the docs, https://www.polymer-project.org/1.0/start/first-element/intro#run-the-demo, but it's confusing for the CLI to not match.

**Comment by arthurevans** [comment]
Hm. Unfortunately, the CLI can't guess what you want to see... But it occurs to me that we could add an `index.html` with a redirect to the demo file... Hopefully without causing too much confusion elsewhere.

**Comment by katejeffreys** [comment]
To help me prioritize and manage issues in the repo, I'll close this issue with no docs changes in 7 days. To prevent this, please comment within 7 days.

**Comment by arthurevans** [comment]
I think we can close this. Some folks encountered this problem in 1.x (not finding the /demo/ URL). The 2.x tutorial fixes this by adding a redirect in the root, so clicking on the CLI's reusable component URL redirects to the right place.
