### ISSUE TITLE
Please clarify @type declaration in docs

### ISSUE THREAD

**Issue by phidias51** [Polymer/docs#1672]
In the section entitled **Tools/Document your elements** it's not clear how you would document an attribute which has validation constraints. In the example below, we have an attribute called language which is a String. Suppose that language could be constrained to one of the following values: 'Java', 'JavaScript', 'Groovy', 'Python'. How would you indicate this?

```
/**
 * Metadata describing what has been made awesome on the page.
 *
 * @type {{elements: Array<HTMLElement>, level: number, language: String}}
 */
```

Is there a way of documenting each attribute separately? Something like:

```
@type {{
   elements: Array<HTMLElement>  - an array of HTMLElement objects,
   level: Number - the level of in the array,
   language: String - one of the following values  'Java', 'JavaScript', 'Groovy', 'Python'
}}
```

**Comment by arthurevans** [comment]
I don't think you can at present. There's a typedef feature in JSDoc that allows you to define a pseudo type (for example, an object with named properties), but hydrolysis doesn't support it yet. There's an open issue for that here:

https://github.com/Polymer/hydrolysis/issues/133

**Comment by jcuratolo** [comment]
Does this fit your needs?

`/**
 * Assign the project to an employee.
 * @param {Object} employee - The employee who is responsible for the project.
 * @param {string} employee.name - The name of the employee.
 * @param {string} employee.department - The employee's department.
 */
Project.prototype.assign = function(employee) {
    // ...
};`

[reference](http://usejsdoc.org/tags-param.html)
