### ISSUE TITLE
redirect to www. subdomain 

### ISSUE THREAD

**Issue by the872** [Polymer/docs#1680]
when you try to go on https://polymer-project.org it does not redirect you to https://www.polymer-project.org and just shows an empty page

**Comment by FluorescentHallucinogen** [comment]
IMO, redirecting from https://www.polymer-project.org to https://polymer-project.org would be more correct decision.

http://polymer-project.org (without "s") works fine. Seems you also need to update SSL sertificate from www.polymer-project.org to *.polymer-project.org.

**Comment by ebidel** [comment]
We've looked into this before. This is an issue with gae. For some reason certs do not work with the naked domain. It's best to just type in the domain and have the browser redirect properly. Not much we can do to fix this one so going to close.

**Comment by FluorescentHallucinogen** [comment]
@ebidel, is it possible to deploy it to Firebase instead of Google App Engine?

https://elements.polymer-project.org is hosted on Firebase.

**Comment by ebidel** [comment]
No. We have a server component now

**Comment by FluorescentHallucinogen** [comment]
@ebidel, but any plans to move hosting to Firebase in the near future?

**Comment by ebidel** [comment]
No plans.
