### ISSUE TITLE
"listeners" doesn't support listening by id for dynamically created elements

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/docs#1689]
According to @azakus in https://github.com/Polymer/polymer/issues/1506#issuecomment-175850553:

> For the `listeners` case, it is not supported to listen by id for dynamically created elements, including those created by `dom-if`. Instead, you should put your handler directly on the node you need to listen on.

The error message when trying to do so is unhelpful:

```
Uncaught TypeError: Invalid value used as weak map key
```

This should be documented  at https://www.polymer-project.org/1.0/docs/devguide/events.

**Comment by arthurevans** [comment]
Seems like we could use a better error message here.

**Comment by katejeffreys** [comment]
To help with prioritization I will close this issue within 7 days unless requested otherwise. Thanks

**Comment by arthurevans** [comment]
My PR to provide a better error message for Polymer 1.x was never merged, and the ability to specify an ID in the listeners object is removed in Polymer 2.x (legacy elements). So I think this can be closed.

**Comment by dman777** [comment]
Still using Polymer 1 here at my job.... this would of been useful in documentation
