### ISSUE TITLE
paper-draw-toggle=true, not in the docs

### ISSUE THREAD

**Issue by lingtalfi** [Polymer/docs#1711]
Watching this polycast:
https://www.youtube.com/watch?v=Iq8TdPJSQMI&list=PLOU2XLYxmsII5c3Mgw6fNYCzaWrsM3sMN&index=45

Rob mentions the fancy/helper core-drawer-toggle attribute.
Looking at the paper-icon-button docs: 
https://elements.polymer-project.org/elements/paper-icon-button

I see no mention of this attribute.
However, I tested paper-drawer-toggle="true" and it worked.

I think this should be either put in the doc, unless it's a deprecated feature (which I hope is not)

**Comment by robdodson** [comment]
Hey Ling, glad you liked the video! I think that attribute is actually part
of paper-drawer-panel and can be applied to any child element

**Comment by lingtalfi** [comment]
right, thank you.
