### ISSUE TITLE
deprecate polymer starter kit page and redirect to the new starter guide

### ISSUE THREAD

**Issue by saturnism** [Polymer/docs#1716]
Polymer Starter Kit page is still showing up on the top of search results when searching for getting started w/ Polymer.
https://www.polymer-project.org/1.0/start/first-element/intro

The starter kit zip file doesn't have all the necessary files, and  I _just_ found out this is no longer the way to do things. Please deprecate and redirect.

**Comment by arthurevans** [comment]
Do you mean the PSK doc:

https://www.polymer-project.org/1.0/start/psk/set-up

You're right, that shouldn't be showing up anymore. I'll add a redirect.

The link you included, "Build your first element," should still be working:

https://www.polymer-project.org/1.0/start/first-element/intro

**Comment by robdodson** [comment]
FWIW we're about to ship the updated Polymer Starter Kit which will be the
basis for building an app. Literally shipping it all out today and pushing
new docs hopefully

**Comment by arthurevans** [comment]
@robdodson I think we're going to retain the newer tutorial, though. The problem is that we left the old (/psk/) and the new (/toolbox/) tutorials live side-by-side for some reason. So we need to update the tutorial, and redirect the older links to avoid sending people into limbo from the search results.

**Comment by saturnism** [comment]
Yeah. I definitely sent me into a limbo :(

**Comment by arthurevans** [comment]
Sorry about that! The older `/1.0/start/psk/` URLs should now redirect to the `/1.0/start/toolbox/` URLs, which are current. If you have any problems with the current tutorials (Build an Element and Build an App), please let me know!
