### ISSUE TITLE
cannot found doc on isAttached property

### ISSUE THREAD

**Issue by lingtalfi** [Polymer/docs#1721]
In the source code of the app-drawer element,  the isAttached property is used.

```js
// line 236 if app-drawer.html
      observers: [
        'resetLayout(position, isAttached)',
        '_resetPosition(align, isAttached)'
      ],
```

Cannot found that property/attribute in the doc.
I searched that page: https://www.polymer-project.org/1.0/docs/devguide/observers, and googled it too.

Maybe it's not intended to be used by developers?
But if it is, it should be documented.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/polymer#3956
