### ISSUE TITLE
RSS feed for news/updates

### ISSUE THREAD

**Issue by inspector71** [Polymer/docs#1725]
Perhaps a good article for the Polymer blog would be how to create an RSS feed and support open standards. The best thing about such an article? You could eat your own dog food! 

In other words, where's the RSS feed on the Polymer site?

**Comment by ebidel** [comment]
I'm not sure "how to create an RSS feed" is in scope for an article. There's already a ton of info on the web.

We should probably have an RSS feed for the news/updates pages though.

**Comment by katejeffreys** [comment]
Closing. Duplicate: #2253
