### ISSUE TITLE
docs seem to suggest use of /deep/ and ::shadow

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#1745]
https://www.polymer-project.org/1.0/docs/api/custom-style

```
Shadow DOM-specific /deep/ and ::shadow combinators will be shimmed on browsers without non-native Shadow DOM.
```

```
    /* Can use /deep/ and ::shadow combinators */
    body /deep/ .my-special-view::shadow #thing-inside {
      background: yellow;
    }
```

The above page suggests use of /deep/ and ::shadow, while I am advised those features are deprecated.

Could it be made a little clearer if developers should use these features or not? The way I read it, it seems like Polymer is shimming their behaviour, rather than it being implemented in the browser (as in the v0.5 days).

**Comment by arthurevans** [comment]
The lines in the example can just be removed. The line in the list, being technically correct, could be left in but qualified as, "For backwards compatibility, the deprecated shadow DOM `/deep/` and `::shadow` combinators will be shimmed ..."

@katejeffreys another one you could take.
