### ISSUE TITLE
Request for left side bar to stay independent of main scroll area

### ISSUE THREAD

**Issue by dman777** [Polymer/docs#1751]
I don't recall this being the behavior on the old website....

On the new doc website - this a request to not have the left side bar glued to the main content area. If I scroll down the main content area, the left side scroll scrolls also because it is a part of the main content area. It's not part of the main content area, and when I scroll down the main content area I would like to save my place on the left side bar.  To loose my place on the left scroll bar and have to scroll back to where I was is bad user experience. 

In addition, there is inconsistency with this behavior on the new doc website. The left side is correctly a separate entity, with it's own scroll bar, until you click on one of the left items and the main content populates. This behavior of the side bar becoming a non separate entity and one page with the main content is in consistent behavior. Just before a selection, the left side bar had it's own Y scroll bar and was not glue to the main content scroll area. This inconsistency leads to more of a unusual and confusing feel for user experience.

**Comment by katejeffreys** [comment]
To help with prioritization, I will close this issue in 7 days with no docs changes unless requested otherwise. Thanks!
