### ISSUE TITLE
Broken link to Polymer Summit on Polymer 2.0 Preview page

### ISSUE THREAD

**Issue by d-reinhold** [Polymer/docs#1753]
Steps to reproduce:

1. Visit https://www.polymer-project.org/1.0/blog/2016-09-09-polymer-2.0.
2. Scroll to the bottom of the blog post and click the Polymer Summit link.
3. The following error occurs: `Uncaught TypeError: Cannot read property 'firstChild' of null`
4. Refresh the page to see the summit post.
5. Clicking the back button at this point leads to a broken url.

See attached .gif

![polymer-web-bug](https://cloud.githubusercontent.com/assets/815285/18760463/0173547c-80b6-11e6-9add-d279240632eb.gif)

**Comment by arthurevans** [comment]
Hey Kate. This would be a good first PR.

**Comment by arthurevans** [comment]
Fixed in #1759.
