### ISSUE TITLE
firebase.json rewrite property is wrong for polymer

### ISSUE THREAD

**Issue by tepk** [Polymer/docs#1755]
Here https://www.polymer-project.org/1.0/start/toolbox/deploy
in the docs it says the correct way to configure firebase.json to host from firebase:

```
"rewrites": [ {
  "source": "**/!{*.*}",
  "destination": "/index.html"
} ]
```

but it does not work, and you will see 404 for any route other than root. Correct way is:

```
"rewrites": [ {
  "source": "**/!(*.*)",
  "destination": "/index.html"
} ]
```

**Comment by iSuslov** [comment]
+1
simple firebase.json should look like this:

```json
{
  "database": {
    "rules": "database.rules.json"
  },
  "hosting": {
    "public": "public",
    "rewrites": [ {
      "source": "**/!(*.js|*.html|*.css|*.json|*.svg|*.png|*.jpg|*.jpeg)",
      "destination": "/index.html"
    } ]
  }
}
```

don't do wildcard if you for example serialize google map `lat`/`lng` into url or any other value with the dot.

**Comment by abdonrd** [comment]
cc @robdodson @arthurevans

**Comment by robdodson** [comment]
@iSuslov hm why do you exclude `.html` from the `source` property?

**Comment by robdodson** [comment]
ah nvm, I bet it's for html imports

**Comment by robdodson** [comment]
@iSuslov @tepk would either of you be interested in opening a PR for this?

**Comment by iSuslov** [comment]
@robdodson Hi Rob, sure I will make this soon

**Comment by robdodson** [comment]
I went ahead and added a PR for this cuz it was pretty easy and I was already fixing up something else related to firebase https://github.com/Polymer/docs/pull/1815

**Comment by mikcaweb** [comment]
This solved my problem, firebase rewrite rules, two thumbs up! Thank You @iSuslov
