### ISSUE TITLE
Dead link on events page

### ISSUE THREAD

**Issue by nicolethenerd** [Polymer/docs#1765]
See https://www.polymer-project.org/1.0/docs/devguide/events#property-changes. The link to "change notification events" points at https://www.polymer-project.org/1.0/docs/devguide/events#change-events - there is nothing with the #change-events id on this page, and this link does nothing.

**Comment by arthurevans** [comment]
Thanks for the report. The link should be data-system#change-events:

https://www.polymer-project.org/1.0/docs/devguide/data-system#change-events

**Comment by TimvdLippe** [comment]
This has regressed in the 2.0 version: https://www.polymer-project.org/2.0/docs/devguide/events#property-changes links to https://www.polymer-project.org/2.0/docs/devguide/events#change-events
