### ISSUE TITLE
Broken images in docs

### ISSUE THREAD

**Issue by kevinSuttle** [Polymer/docs#1781]
https://www.polymer-project.org/1.0/start/toolbox/create-a-page: 
missing: https://www.polymer-project.org/images/1.0/toolbox/app-drawer-template-newview.png

(Maybe a code rendering issue here as well in the https://www.polymer-project.org/1.0/start/toolbox/create-a-page#add-the-page-element-to-your-app section)

https://www.polymer-project.org/1.0/start/toolbox/set-up:
missing https://www.polymer-project.org/images/1.0/toolbox/app-drawer-template.png

**Comment by arthurevans** [comment]
Sorry about that. Same cause as #1783. Should be sorted out now. Please let us know if you still see anything wrong there.

**Comment by kevinSuttle** [comment]
Thanks!
