### ISSUE TITLE
Replace app-drawer-template with starter-kit

### ISSUE THREAD

**Issue by web-padawan** [Polymer/docs#1783]
This should be done [here](https://www.polymer-project.org/1.0/start/toolbox/set-up#initialize-your-project), as mentioned by [this comment](https://github.com/Polymer/polymer-cli/issues/167#issuecomment-251932556).

**Comment by wim82** [comment]
Wanted to mention this too.. i noticed this problem when following the app tutorial. Currentl you get a "no template found error"

**Comment by arthurevans** [comment]
Sorry about that. Accidentally merged some old stuff back in. Should be fixed now.

**Comment by maddyjolly2112** [comment]
I tried using polymer init starter-kit but it gives me following error :

`
error:   Could not download release from PolymerElements/polymer-starter-kit
error:   Uncaught exception: connect ECONNREFUSED 192.30.253.117:443
error:   Error: connect ECONNREFUSED 192.30.253.117:443
    at __dirname.sendError (D:\Users\mandeep_sin\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.j
s:819:19)
    at D:\Users\USER\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:830:29
    at callCallback (D:\Users\USER\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\index.js:694:1
7)
    at ClientRequest.<anonymous> (D:\Users\USER\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\github\lib\i
ndex.js:772:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)`

But help me where i am going wrong, i am behind a proxy, so let me know if it is due to proxy and how to set the same.

**Comment by web-padawan** [comment]
@maddyjolly2112 you're rightt, this is due to proxy. See [this comment](https://github.com/npm/npm/issues/9401#issuecomment-134569585) for settings.

**Comment by maddyjolly2112** [comment]
yeah i tried this,

npm config set registry http://registry.npmjs.org/
npm config set proxy "http://username:password@proxyserver:8080/"
npm config set https-proxy "http://username:password@proxyserver:8080/"
npm config set strict-ssl false
npm config set prefix "D:\Users\USER\AppData\Roaming\npm"

It is working fine where i want **npm install** , it downloads all the dependencies but when i used it for **polymer init starter-kit** it gives the above error.

**Comment by web-padawan** [comment]
Looks like you also need to pass your proxy settings to `bower`, see [here](http://stackoverflow.com/questions/18359887/bower-proxy-configuration) for details.

**Comment by maddyjolly2112** [comment]
Hi I tried,

`{
	"proxy":"http://username:password@proxy:8080/",
	"https-proxy":"http://username:password@proxy:8080/",
	"no-proxy":"http://username:password@proxy:8080/",
	"strict-ssl": false
}
`

in the **.bowerrc** file present in user.

Can you please let me know where i am going wrong.

**Comment by fredtma** [comment]
Has this been resolved?
Both .bowerrc and .npmrc have the proxy settings but still `polymer init` failing
