### ISSUE TITLE
Broken links to updates and livestream on summit 2016 page

### ISSUE THREAD

**Issue by web-devel** [Polymer/docs#1793]
https://www.polymer-project.org/summit/
_Stay in the loop_ & _Get updates about the 2016 summit and livestream_ buttons produce **403 Forbidden**

**Comment by robdodson** [comment]
@web-devel this seems to work for me. can you try again?

**Comment by web-devel** [comment]
@robdodson after some research I discovered that it does not work from Russia at all (tried several machines/ISPs). Are there any geo ip filtration? :)

**Comment by robdodson** [comment]
hm not that I know of. @tjsavage ?

**Comment by tjsavage** [comment]
Not that I know of either.
