### ISSUE TITLE
Lack of documentation on how to run Polymer 2.0 preview

### ISSUE THREAD

**Issue by caraya** [Polymer/docs#1805]
The readme in the Polymer 2.0 repository only refers to Polymer installation

``` bash
bower install polymer/polymer#2.0-preview
```

Docs need a list of the Polymer elements that have been upgraded and how to install those elements. Otherwise it'll lead to confusion. 

If it's ok, I can start writing the page.

**Comment by arthurevans** [comment]
@caraya Good point. I'm going to make some changes to the preview docs.

https://www.polymer-project.org/2.0/docs/upgrade#installing

... should also mention elements.

https://www.polymer-project.org/2.0/docs/about_20#polymer-element-availability

... should point to install, and also mention Polymer behaviors.

I don't have a list of which elements have been upgraded, but we could discuss adding that.

**Comment by arthurevans** [comment]
Some updates here: https://www.polymer-project.org/2.0/docs/about_20#installing

Oh, yeah. I moved the installation section. Also a new behaviors section under:

https://www.polymer-project.org/2.0/docs/about_20#polymer-element-availability

Hope that helps a bit as a stopgap measure.
