### ISSUE TITLE
polymon-egg not found ?

### ISSUE THREAD

**Issue by zhoukekestar** [Polymer/docs#1816]
Error occured when i run `bower install`
* Lastest code on master branch
* bower version: 1.7.9
* node version: 6.3.0
* npm version: 3.10.5
```bash
bower polymon-egg#*                             ECMDERR Failed to execute "git ls-remote --tags --heads git@github.com:polymerelements/polymon-egg.git", exit code of #128 Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts. Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.
```
And i can't find any repo about this on [polymerelements](https://github.com/PolymerElements?utf8=%E2%9C%93&query=polymon).  Any suggestions ?

Thanks.

**Comment by clia** [comment]
You can temporarily comment the polymon-egg line in the bower.json file.
