### ISSUE TITLE
About 2.0 - Polymer specific ready callback confusing or wrong

### ISSUE THREAD

**Issue by jongeho1** [Polymer/docs#1829]
Hi there,

```ready (Polymer specific)```	

```Polymer longer guarantees that the initial light DOM distribution is complete before ready is called.```

https://github.com/Polymer/docs/blame/master/app/2.0/docs/about_20.md#L105

Is this guaranteed or not? 

My brain saw the word "no" before longer but realized it wasn't there after I read it twice. It might be a good idea to add the word "no" or omit the word "longer" when this question has an answer.

Cheers!

**Comment by arthurevans** [comment]
Thanks @jongeho1—good catch. And your brain was right to read a "no" there because that's exactly what it should say.

**Comment by jongeho1** [comment]
Thank you for confirming!
