### ISSUE TITLE
registering elements docs statement could be clearer

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#1830]
in :

https://github.com/Polymer/docs/blob/3c368149d2e7ba35613fe28f8f8105a3d8f1f234/app/1.0/docs/devguide/registering-elements.md

it has a line :

```
Implement ready when it's necessary to manipulate an element's local DOM when the element is constructed.
```

which could be clearer. It's the multiple 'when's that are difficult to parse - perhaps `during element construction`.

**Comment by davidmaxwaterman** [comment]
This statement :

```
Polymer guarantees that local DOM children have their ready callback called before their parent's; however, it cannot guarantee the same thing for the attached callback. This is one fundamental difference between native behavior and polyfill behavior.
```

is unclear (to me). The `ready` callback is called before the `attached`, and all children's `ready` callbacks are called before the parent's `ready`, so how can the `attached` callback be called before the any child's `ready` is called.

While writing, it occurs to me that it means that it isn't guaranteed that the child's `attached` callbacks are called before the parent's `attached` callbacks. I'll leave this here in case it is determined that it could be made clearer.

**Comment by katejeffreys** [comment]
I agree, "This is one fundamental difference between native behavior and polyfill behavior" could be elaborated on. 

@arthurevans Are you able to briefly clarify regarding the polyfill behaviour? I can update the docs.
