### ISSUE TITLE
demos don't support use of dom=shadow

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#1831]
1. go to https://elements.polymer-project.org/elements/app-layout?view=demo:app-header-layout/demo/footer.html&active=app-header-layout
1. attempt to add dom=shadow to URL to force native shadow dom
1. navigating removes the dom=shadow
1. edit the iframe to add dom=shadow and it works

suggestion - a toggle button to add dom=shadow to the iframe URL, or have javascript duplicate any dom=shadow in the main URL to the iframe's URL (former seems more user-friendly).

**Comment by katejeffreys** [comment]
@samuelli Can you comment on this re: www.webcomponents.org?

**Comment by samuelli** [comment]
This is pretty Polymer specific. I think moving forward, shadow DOM is default anyway, so this shouldn't be as much of an issue. @davidmaxwaterman: is this still an issue?

**Comment by davidmaxwaterman** [comment]
It is still an issue since I'm still using Polymer 1.X and shadow-dom, but I accept it will become less so as we move forward. Also accept a decision to not change it, if that is the way it goes. Your call.

**Comment by samuelli** [comment]
Given that the Polymer 2 demos are using shadow DOM by default, I think this is too low on our priority list to fix.

Thanks for understanding @davidmaxwaterman!
