### ISSUE TITLE
app.yaml not in dist/

### ISSUE THREAD

**Issue by kevindecapite** [Polymer/docs#1837]
When I run dev_appserver.py dist/ I get the following:

`google.appengine.tools.devappserver2.errors.AppConfigNotFoundError: "dist/" is a directory but does not contain app.yaml or app.yml`

If I copy app.yaml from the repo root into dist/ and try again I get:

`INFO     2016-12-02 04:21:11,581 devappserver2.py:769] Skipping SDK update check.
INFO     2016-12-02 04:21:11,669 api_server.py:205] Starting API server at: http://localhost:57283
INFO     2016-12-02 04:21:11,678 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2016-12-02 04:21:11,680 admin_server.py:116] Starting admin server at: http://localhost:8000`

But when I open my browser to http://localhost:8080 I get a 500 server error. I also see in my terminal window output this error:

`ImportError: No module named server`

I *am* able to navigate to http://localhost:8000, however, which is the admin server.

**Comment by arthurevans** [comment]
Apologies for the slow response. I think this is related to a build issue caused by a bad dependency. Try re-running the bower install and gulp steps and see if it generates the correct dist/ folder for you.
