### ISSUE TITLE
Error vulcanized

### ISSUE THREAD

**Issue by jrobayna** [Polymer/docs#1844]
Hi, I have a problem with vulcanize.
To run it: in the directory where my application is -> vulcanize index.html -o index.vulcanized.html gives me the following error:

{Error: ENOENT: no such file or directory, open 'D: \ POLYMER \ ultimo_poly \ src \ app.html'
   Errno: -4058,
   Code: 'ENOENT',
   Syscall: 'open',
   Path: 'D: \\ POLYMER \\ ultimo_poly \\ src \\ app.html'}
  I have followed several threads where something is said about this problem but I can not solve it.
I have:
Windows 10 64 bit
Polymer bower, Nodejs, Git ...
Can you help me, please?

**Comment by katejeffreys** [comment]
Hi, sorry for the delayed response. I am not sure if this is a documentation issue. If you still have problems, could you please visit our Tools channel in Slack? https://polymer.slack.com/messages/C2NH75P0D/details/
