### ISSUE TITLE
Error during npm install

### ISSUE THREAD

**Issue by picwellwisher12pk** [Polymer/docs#1849]
$ npm install

> PolymerDocs@1.0.0 postinstall C:\xampp\htdocs\Libraries\HTMLCSS\polymer\docs
> bower install; gulp

Usage:

    bower <command> [<args>] [<options>]
Commands:

    cache                   Manage bower cache
    help                    Display help information about Bower
    home                    Opens a package homepage into your favorite browser
    info                    Info of a particular package
    init                    Interactively create a bower.json file
    install                 Install a package locally
    link                    Symlink a package folder
    list                    List local packages - and possible updates
    login                   Authenticate with GitHub and store credentials
    lookup                  Look up a single package URL by name
    prune                   Removes local extraneous packages
    register                Register a package
    search                  Search for packages by name
    update                  Update a local package
    uninstall               Remove a local package
    unregister              Remove a package from the registry
    version                 Bump a package version
Options:

    -f, --force             Makes various commands more forceful
    -j, --json              Output consumable JSON
    -l, --loglevel          What level of logs to report
    -o, --offline           Do not hit the network
    -q, --quiet             Only output important information
    -s, --silent            Do not output anything, besides errors
    -V, --verbose           Makes output more verbose
    --allow-root            Allows running commands as root
    -v, --version           Output Bower version
    --no-color              Disable colors
See 'bower help <command>' for more information on a specific command.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Libraries\HTMLCSS\polymer\docs\node_modules\bin-build\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Libraries\HTMLCSS\polymer\docs\node_modules\bin-version-check\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Libraries\HTMLCSS\polymer\docs\node_modules\buffer-to-vinyl\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Libraries\HTMLCSS\polymer\docs\node_modules\caw\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Libraries\HTMLCSS\polymer\docs\node_modules\collect-json\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Libraries\HTMLCSS\polymer\docs\node_modules\decompress\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\Libraries\HTMLCSS\polymer\docs\node_modules\decompress-tar\package.json'
....

**Comment by picwellwisher12pk** [comment]
with bower install gulp I get 
bower                     invalid-meta for:C:\xampp\htdocs\Libraries\HTMLCSS\polymer\docs\bower.json
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower polymon-egg#*         not-cached git@github.com:polymerelements/polymon-egg.git#*
bower polymon-egg#*            resolve git@github.com:polymerelements/polymon-egg.git#*
bower app-layout#^0.0.14        cached https://github.com/PolymerLabs/app-layout.git#0.0.14
bower app-layout#^0.0.14      validate 0.0.14 against https://github.com/PolymerLabs/app-layout.git#^0.0.14
bower iron-elements#^1.0.4      cached https://github.com/PolymerElements/iron-elements.git#1.0.10
bower iron-elements#^1.0.4    validate 1.0.10 against https://github.com/PolymerElements/iron-elements.git#^1.0.4
bower paper-elements#^1.0.5     cached https://github.com/PolymerElements/paper-elements.git#1.0.7
bower paper-elements#^1.0.5   validate 1.0.7 against https://github.com/PolymerElements/paper-elements.git#^1.0.5
bower prism-element#^1.0.0      cached https://github.com/PolymerElements/prism-element.git#1.2.0
bower prism-element#^1.0.0    validate 1.2.0 against https://github.com/PolymerElements/prism-element.git#^1.0.0
bower google-youtube#^1.2.1     cached https://github.com/GoogleWebComponents/google-youtube.git#1.2.1
bower google-youtube#^1.2.1   validate 1.2.1 against https://github.com/GoogleWebComponents/google-youtube.git#^1.2.1
bower google-map#^1.1.10        cached https://github.com/GoogleWebComponents/google-map.git#1.1.14
bower google-map#^1.1.10      validate 1.1.14 against https://github.com/GoogleWebComponents/google-map.git#^1.1.10
bower firebase-element#^1.0.12  cached https://github.com/PolymerElements/firebase-element.git#1.0.16
bower firebase-element#^1.0.12         validate 1.0.16 against https://github.com/PolymerElements/firebase-element.git#^1.0.12
bower app-route#^0.9.0                   cached https://github.com/PolymerElements/app-route.git#0.9.3
bower app-route#^0.9.0                 validate 0.9.3 against https://github.com/PolymerElements/app-route.git#^0.9.0
bower gulp#*                             cached https://github.com/gulpjs/gulp.git#3.9.1
bower gulp#*                           validate 3.9.1 against https://github.com/gulpjs/gulp.git#*
bower iron-list#^1.0.0               not-cached https://github.com/PolymerElements/iron-list.git#^1.0.0
bower iron-list#^1.0.0                  resolve https://github.com/PolymerElements/iron-list.git#^1.0.0
bower iron-overlay-behavior#^1.0.0   not-cached https://github.com/PolymerElements/iron-overlay-behavior.git#^1.0.0
bower iron-overlay-behavior#^1.0.0      resolve https://github.com/PolymerElements/iron-overlay-behavior.git#^1.0.0
bower iron-selector#^1.0.0           not-cached https://github.com/PolymerElements/iron-selector.git#^1.0.0
bower iron-selector#^1.0.0              resolve https://github.com/PolymerElements/iron-selector.git#^1.0.0

......
......

invalid-meta for:C:\Users\AMIRHA~1\AppData\Local\Temp\AMIRHAMEED-PC-AmirHameed\bower\6ac9fb6e69374501bea0bcad9749c0a7-18944-CrwQLW\bower.json
bower polymer#^1.5.0                           invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["polymer.html","polymer-mini.html","polymer-micro.html"]
bower polymer#^1.5.0                               resolved https://github.com/Polymer/polymer.git#1.7.1
bower polymon-egg#*                                 ECMDERR Failed to execute "git ls-remote --tags --heads git@github.com:polymerelements/polymon-egg.git", exit code of #128 Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts. ERROR: Repository not found. fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

Additional error details:
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by arthurevans** [comment]
I'm not sure about the npm errors here, but we've just made a fix that should clear up the fatal bower error here.

**Comment by katejeffreys** [comment]
Closing this. Please re-open if it is not resolved.
