### ISSUE TITLE
Image and text inconsistency at https://www.polymer-project.org/1.0/start/toolbox/create-a-page

### ISSUE THREAD

**Issue by berabhishek** [Polymer/docs#1850]
The URL just before the "**Register the Page for the build**" says _localhost:8080/new-view ._
whereas the following image shows the URL _localhost:8080/newview_ 
Image link: https://www.polymer-project.org/images/1.0/toolbox/starter-kit-newview.png

**Comment by katejeffreys** [comment]
#1869

**Comment by katejeffreys** [comment]
Thanks! Done.
