### ISSUE TITLE
Polymer website not rendering in Firefox 50.1.0

### ISSUE THREAD

**Issue by brylie** [Polymer/docs#1851]
The [Polymer](https://polymer-project.org) website is not rendering with Firefox 50.1.0. This issue was originally reported in the [polymer/polymer repository](https://github.com/Polymer/polymer/issues/4236)

# Console error
There is an error in the browser console:

```
"No Google Maps API Key or Client ID specified. See https://developers.google.com/maps/documentation/javascript/get-api-key for instructions to get started with a key or client id."  index.js:16:25183

"Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys"  util.js:211:33
```
![peek 2016-12-29 13-04](https://cloud.githubusercontent.com/assets/17307/21542590/8765b58a-cdc7-11e6-9fe5-a13af363c633.gif)

**Comment by brylie** [comment]
@ebidel I disabled the `dom.webcomponents.enabled` flag, and now the site renders. If I recall, I enabled the flag previously, so that webcomponent libraries would work without a polyfill. Is this no longer recommended?

**Comment by ebidel** [comment]
Their implementation is quite old and buggy. FF still requires the polyfill.
