### ISSUE TITLE
Reuse Polymer 1.0 Custom Elements into polymer 2 preview

### ISSUE THREAD

**Issue by NaqashPixy** [Polymer/docs#1853]
Hi, 
How can i add polymer 1.0 elements in my project which is in polymer 2 preview

**Comment by katejeffreys** [comment]
Info on this is in development - for now, if you are having issues, another reply to a similar issue suggests checking that you have included the v1 polyfills.

**Comment by katejeffreys** [comment]
https://www.polymer-project.org/2.0/docs/upgrade
