### ISSUE TITLE
Need some guidance on creating/converting 1.0 components to hybrid mode

### ISSUE THREAD

**Issue by gechols** [Polymer/docs#1868]
I want to include/use a component from 1.0 in my 2.0 project and I'm getting an error "ShadyCSS is not defined". I don't know what changes I need to make to get the 1.0 web component to run as a hybrid component. Is there already something that we can have a pointer to in the upgrade document?

**Comment by arthurevans** [comment]
I'm working on that, don't have anything to share at the moment beyond what's currently in the upgrade document. Are you including the v1 polyfills?

**Comment by katejeffreys** [comment]
#1853 looks like the same question

**Comment by gechols** [comment]
If you are referring to the webcomponents-lite.js file from the v2.0 preview then yes I'm loading it. I have created a very rudimentary (practically empty) test case for hybrid testing and it seems to work fine. The component I was trying it against at first was more complex - vaadin-grid. Since I'm working in a 2.0 project I wanted to be able to use a 1.0 component (until they get their 2.0 component ready).

**Comment by arthurevans** [comment]
@gechols I don't think vaadin-grid is a hybrid element currently. Even the 2.0 prerelease version in github is a Polymer 1.x element, not a hybrid element.

**Comment by katejeffreys** [comment]
https://www.polymer-project.org/2.0/docs/upgrade
