### ISSUE TITLE
Explain how to cross-link elements that may be upgraded before their target is parsed

### ISSUE THREAD

**Issue by jyasskin** [Polymer/docs#188]
Say I have a custom element that refers to another element:

```HTML
<my-elem ref="foo"></my-elem>
<div id="foo"></div>
```

I'd like to resolve that reference in my element's upgrade code. However, the 'created' event may fire before the whole document is parsed, which would cause `document.getElementById(this.ref)` to return `null`. On the other hand, I don't see any guarantee that 'created' does fire before `DOMContentLoaded`, so if I naïvely delay the link resolution to that event, my resolution might never fire at all. The solution is probably to use a library that abstracts this, but the documentation should explain it either way.

**Comment by arthurevans** [comment]
Closing 0.5 issues.
