### ISSUE TITLE
TOC visually overlapping content on many docs page at desktop screen widths

### ISSUE THREAD

**Issue by rictic** [Polymer/docs#1880]
e.g. at
https://www.polymer-project.org/1.0/docs/devguide/registering-elements#ready-method

I'm seeing:
![image](https://cloud.githubusercontent.com/assets/1659/23044030/54f2ca90-f453-11e6-94b7-0a9f30dc15c7.png)

I'm only seeing this in Chrome, not Safari or Firefox. Using Chrome 57 (beta channel).

**Comment by rictic** [comment]
Chrome 58 (Canary) is fine. Hm.

**Comment by notwaldorf** [comment]
Seems to be fixed in 57.0.2987.54! 👏 the lords of chrome.

**Comment by arthurevans** [comment]
"Lords of Chrome" should totally be a motorcycle gang. A W3C-standards-driving, C++-hacking motorcycle gang.
