### ISSUE TITLE
Document element.onMutation

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#190]
https://github.com/Polymer/polymer/blob/master/src/instance/base.js#L163:L170

Used to observe once:

```
this.onMutation(document, function(observer, mutations) {
    mutations.forEach(function(record) {
      console.log(record.addedNodes)
    }.bind(this));
});
```

**Comment by RenaudF** [comment]
Hi guys, is it legit to use `onMutation` to observe changes made by a template update? It doesn't seem to work for me.
