### ISSUE TITLE
Demo-tabs and plunker buttons disappear on refresh

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#1901]
Post-perf work, these elements show up on initial load, but disappear on refresh:

https://2-0-staging-dot-polymer-project.appspot.com/2.0/docs/devguide/quick-tour

**Comment by arthurevans** [comment]
Hep hep o plz hep

**Comment by notwaldorf** [comment]
Argh, it seems like the import isn't there. Will take a look asap
