### ISSUE TITLE
Polymer 2: Quick-tour: mistake in code example

### ISSUE THREAD

**Issue by mkutny** [Polymer/docs#1940]
In the "Declare a property" section the code in "configurable-name-tag.html" does not include `static get properties()` and therefore example on the page renders with a mistake (Daniel is not substituted by Scott).

Although, the code n the corresponding Plunker's bin is correct.

**Comment by katejeffreys** [comment]
Issues with these code samples have been resolved, unless I'm mistaken - in which case please re-open
