### ISSUE TITLE
Issues in Polymer 2 docs

### ISSUE THREAD

**Issue by teslor** [Polymer/docs#1947]
1)
https://www.polymer-project.org/2.0/docs/devguide/properties#notify
As I understand this text "External scripts can also listen for events (such as first-name-changed) directly using addEventListener", it is not true, since "Change notification events don't bubble" (as said here - https://www.polymer-project.org/2.0/docs/devguide/data-system#data-flow)

2)
https://www.polymer-project.org/2.0/docs/devguide/custom-css-properties#style-api
I think instead of "ShadyCSS.getComputedStyleValue('--something');" the code "ShadyCSS.getComputedStyleValue(this, '--something');" should be.

**Comment by arthurevans** [comment]
Point 1—it's true these events don't bubble; but external scripts can listen for property change events by adding an event listener directly to the element that generates the event. I've added a note to this effect in #2350.

Point 2—absolutely correct, and this is now fixed on the website.
