### ISSUE TITLE
"sa--- title:" in 2.0 Docs header

### ISSUE THREAD

**Issue by manor** [Polymer/docs#1974]
![wat](https://cloud.githubusercontent.com/assets/596326/24262164/9bca7624-0fcf-11e7-9187-fe30bef73814.png)

**Comment by notwaldorf** [comment]
I can't repro this on master -- maybe it's a bad deploy, or it was fixed afterwards?

**Comment by katejeffreys** [comment]
Weird! I'll check it out. Thanks for raising this!


​

On Fri, Mar 24, 2017 at 6:35 AM, Monica Dinculescu <notifications@github.com

**Comment by katejeffreys** [comment]
Oh, just saw Monica's message. I guess it's been fixed, maybe we just need
to redeploy?

**Comment by arthurevans** [comment]
Fixed version is deployed, closing.
