### ISSUE TITLE
Declare != Declared

### ISSUE THREAD

**Issue by manor** [Polymer/docs#1977]
![declare](https://cloud.githubusercontent.com/assets/596326/24302844/65124056-108a-11e7-85ca-4f64270e8cc2.png)

Found on this page: [Custom elements: properties](https://www.polymer-project.org/2.0/docs/devguide/properties)
How can these get out of sync? Are they not auto-generated by some workflow?

**Comment by arthurevans** [comment]
They are not. You may notice that in many cases the left-nav uses an abbreviated version of the title  for brevity. But in this case, it's just an error :D
