### ISSUE TITLE
Search is not version specific

### ISSUE THREAD

**Issue by jsilvermist** [Polymer/docs#1981]
When looking at the 2.0 docs and using search, it brings up 1.0 docs results.

**Comment by arthurevans** [comment]
I've updated the search engine so it returns both 1.0 and 2.0 results, but we need to (at least) mark the search results so the version is obvious. 

We could probably also filter the search results. CSE provides an easy way to do that, but it has a limited lifetime (so we'll probably need to reinvent the wheel in a year).

@notwaldorf What do you think about tagging search results? We could either show the full URL after the title (like https://developers.google.com/s/results/?q=polymer), or we could show a version number.

**Comment by arthurevans** [comment]
Also, it appears that somewhere along the line, multi-word search broke. So if  you type "css mixins" into the search field, sometimes it comes up with blank search results (and no search term in the URL). "css+mixins" works fine.  I think we just need to URL escape the search term.
