### ISSUE TITLE
Typo on Custom Elements PAge

### ISSUE THREAD

**Issue by drewbard** [Polymer/docs#1993]
#### The wording was wrong for this sentence
> "The custom element spec provides a set of callbacks called "custom element reactions" that allow you to run user code **is** response to certain lifecycle changes."

#### It should be
>"The custom element spec provides a set of callbacks called "custom element reactions" that allow you to run user code **in** response to certain lifecycle changes."

**Comment by arthurevans** [comment]
Fixed by #1994.
