### ISSUE TITLE
Upgrade Guide Broken Link

### ISSUE THREAD

**Issue by d4l3k** [Polymer/docs#1996]
On the upgrade guide, under "Import optional features" the link to "Gesture support." goes to https://www.polymer-project.org/2.0/docs/gesture-events which doesn't exist and should be https://www.polymer-project.org/2.0/docs/devguide/gesture-events .

**Comment by katejeffreys** [comment]
This appears to be resolved, although I can't identify when the change was made. Anyway it's working now.
