### ISSUE TITLE
Docs for Behaviors?

### ISSUE THREAD

**Issue by terrybleger** [Polymer/docs#2005]
The only resource that I found about behaviors was only from Polycast. I don't know why there was no official documentation about it for v1.0 and v2.0.

**Comment by arthurevans** [comment]
1.0 docs for behaviors are here:

https://www.polymer-project.org/1.0/docs/devguide/behaviors

You can use behaviors the same way in 2.0 hybrid mode elements. 

There's also a discussion of how you can use hybrid behaviors with a 2.0 class style element:

https://www.polymer-project.org/2.0/docs/upgrade#mixins

Hope that helps.
