### ISSUE TITLE
New build guide

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#2010]
Replace the old Optimize for Production doc. Kate already has an outline for this.

**Comment by katejeffreys** [comment]
https://github.com/Polymer/docs/tree/new-build-guide

**Comment by katejeffreys** [comment]
From https://github.com/Polymer/docs/issues/2011

- [ ] replace mention of webcomponents-es5-loader.js with custom-elements-es5-adapter.js [[or whatever we end up calling it.]]

- [ ] mention that build --js-compile injects the adapter

- [ ] Separate the “multiple builds” copy into a new section/sub-section
