### ISSUE TITLE
API doc not scrolling to members correctly

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#2024]
For example, navigating to:

https://www.polymer-project.org/2.0/docs/api/elements/Polymer.DomRepeat#method-render

Doesn't scroll down to the render method. Could've sworn this used to work; not sure when we broke it. It worked correctly in the previous incarnation of the site which used the vanilla iron-component-page:

https://docs-05-dot-polymer-project.appspot.com/1.0/api/#dom-repeat:method-render

Anyway, somewhere along the road it broke and now we have a bunch of links that don't work as they should.

**Comment by arthurevans** [comment]
Currently, `iron-doc-viewer` is set up expecting `iron-component-page` to call `scrollToAnchor` on it: https://github.com/PolymerElements/iron-doc-viewer/blob/master/iron-doc-viewer.html#L212

Since we don't have an `iron-component-page`, we're outta luck here.

With the current setup I think either the `pw-shell` has to reach in and tickle the `iron-doc-viewer`, or `iron-doc-viewer` needs to be changed to scroll to anchor after it loads everything. Which seems a little ugly, but maybe it could be an optional thing enabled by setting a prop on the viewer.

**Comment by justinfagnani** [comment]
@arthurevans, @aomarks is going to look at doc-viewer issues now. Anchoring definitely got ripped out in my update.

**Comment by arthurevans** [comment]
Awesome. FWIW, I'm pretty sure you didn't break it on the site--we just missed this in the site revamp as far as I can tell. (Which is bizarre, because I'd've sworn I'd tested this many times...)

**Comment by aomarks** [comment]
Fixed on `analyzer-2.0`.
