### ISSUE TITLE
Exemples using binding to a `name` property are confusing

### ISSUE THREAD

**Issue by Zecat** [Polymer/docs#2032]
In https://www.polymer-project.org/2.0/docs/devguide/data-binding#property-binding

The given examples using a `name` property are confusing because for input elements - native or implementing iron-form-element-behavior - that we want to be submitted by a native form / iron-form require target attribute binding.

```html
<form>
  <input name$="[[name"]]>
</form>
```

**Comment by notwaldorf** [comment]
Not sure I understand; dor `input`, `name` is a reflected property, so `input name=[[name]]` should work fine. Here's an example: http://jsbin.com/jirosul/edit?html,output
