### ISSUE TITLE
Unclear documentation on "Data system concepts"

### ISSUE THREAD

**Issue by dr-jerry** [Polymer/docs#2034]
I´m in the process of getting to know Polymer as fast as possible, using the docs as reference. I found the following unclear in the documentation. It would make it clearer for me to add some explanation and extra examples on the documentation quoted below.

(1) <quote>The <name-card> element has a name property that refers to a JavaScript object</quote>) I don't see this property anywhere defined. Does it refer to name-card's first word? would the element <foo-bar> have property foo?
Furthermore a few lines below:
<quote>If a <name-card> has the following object for its name property:</quote>. I do understand the javascript object with its "first" and "last" properties. But I do not understand how to assign the name property in the <name-card> element to the disclosed Javascript object.

**Comment by arthurevans** [comment]
Thanks. Yes, that initial example should have the property either declared (in a `properties` object) or initialized in the constructor to make it clearer.
