### ISSUE TITLE
Code background inconsistent

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#2055]
Some codeblocks have a gray background, while others have a white background.

I think the ones that don't have a language specified get tagged `<code class="hljs">` and these are getting colored properly.

But where we include a language, like this:

```
    ```html
```

It comes out as:

```
<pre>
  <code class="language-html">
```

And the result is :cry:.

**Comment by arthurevans** [comment]
OK, so this is _not_ fixed. On first load, a page looks fine, but if you follow a link to another page, the code highlighting is wack. Reloading the page fixes it. @notwaldorf @keanulee really need some help here. I suspect it's related to the lazy loading stuff, but 😖?

**Comment by notwaldorf** [comment]
looking
