### ISSUE TITLE
First access to search page yields blank page

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#2057]
Refreshing solves this issue.

**Comment by bicknellr** [comment]
It seems like the first time you search you'll be sent to `/search/` and see the bug. Successful searches have a query string: `/search/?q=test`.

**Comment by arthurevans** [comment]
Yeah, I think it's related to routing and the way we handle the search terms. Failed requests log this message:

```
pw-shell.html:formatted:11187 Uncaught TypeError: Cannot read property 'match' of undefined
    at HTMLElement._handleSearchResponse (pw-shell.html:formatted:11187)
    at HTMLElement.s (pw-shell.html:formatted:4248)
    at HTMLElement.fire (pw-shell.html:formatted:4818)
    at HTMLElement._handleResponse (pw-shell.html:formatted:9405)
    at <anonymous>
```

That's because the query string is missing... Or maybe the query string missing is just another symptom of the same thing.
