### ISSUE TITLE
`polymer serve` on Build an element tutorial repo gives the wrong URL

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#2080]
_From @wmginsberg on April 28, 2017 18:5_

### Description
While doing the Build an element tutorial, I ran polymer serve and noticed that the URL suggested from the CLI was leading to a Not Found page. The URL sent out was http://127.0.0.1:8081/components/icon-toggle/  so I tried http://127.0.0.1:8081/components/icon-toggle/demo and it worked. Unsure if this is a CLI issue or a github repo/starter code issue. 

### Versions & Environment
- Polymer CLI: 0.18.1
- node: v6.4.0
- Operating System: macOS Sierra 10.12.4

#### Expected Results
I can see the demo code from the returned URL 

#### Actual Results
I receive a Not Found error page when trying to see demo code

_Copied from original issue: Polymer/polymer-cli#705_

**Comment by arthurevans** [comment]
_From @wmginsberg on April 28, 2017 18:7_

There is a note in the tutorial later on but it's farther down and I didn't see it til I kept going 

"If this text doesn’t appear, make sure you’re looking at the the demo folder itself, or at demo/index.html, not at toggle-icon.html or toggle-icon-demo.html."

**Comment by arthurevans** [comment]
_From @justinfagnani on May 3, 2017 22:10_

I think this should be a docs issue. We point to the root of the component folder, and yes, there's no guarantee that there's something loadable there.

**Comment by arthurevans** [comment]
Hm. We could add an index or something that just redirects to the /demo/ directory, but I think that would be confusing since it's not a standard part of an element project.

Aha! How about if we add an `index.html` that mentions the name of the project, and tells people that they if they're doing the tutorial they probably want to be looking at the demo directory?

**Comment by arthurevans** [comment]
Hey Kate. If you add an `index.html` file at the top-level of the project, you can add a link to the demo file, something like this: 

```
<html>
<head>
<title>Build your first element tutorial project</title>
<style>
  body { font-family: sans-serif; }
</style>
</head>
<body>
  <p>If you're testing your element, you probably want to
        look at the <a href="/components/icon-toggle/demo/">Demo</a>.</p>
        <p>You can find the tutorial associated with this project at
        <a href="https://www.polymer-project.org/2.0/start/first-element/intro">Build your
                                        first Polymer element on polymer-project.org.</a>
</body>
</html>
```

You can probably come up with better wording. Also I realized that there's the possibility that someone could just open this file from the file system, so it'd be good to mention that it needs to be served through `polymer serve` for the demo to work...

Covering several corner cases here, but this would reduce a number of user errors where they open the wrong thing, or miss the note about which path to open.

Alternately, we could set up this to simply redirect to the demo:

```
<!DOCTYPE HTML>
 
<meta charset="UTF-8">
<meta http-equiv="refresh" content="1; url=/components/icon-toggle/demo/">
 
<script>
  window.location.href = "/components/icon-toggle/demo/"
</script>
```

Big plus: can just use `polymer serve --open` and get automatically directed to the demo.

Big minus: no other element project will work like this, and people will be puzzled when they create their next element and `polymer serve --open` doesn't show them the demo (or anything else, given the current state of `iron-component-page`.

**Comment by arthurevans** [comment]
Wait, never mind. They've changed what the init element template does, so we should just copy the file from there (which redirects):

```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="refresh" content="0;url=demo/" />
    <title>test-init</title>
  </head>
  <body>
    <!--
        ELEMENT API DOCUMENTATION SUPPORT COMING SOON
        Visit demo/index.html to see live examples of your element running.
        This page will automatically redirect you there when run in the browser
        with `polymer serve`.
      -->
  </body>
</html>
```

And we can change the tutorial to use `polymer serve --open`. Pure win.

**Comment by katejeffreys** [comment]
Even better!

**Comment by katejeffreys** [comment]
@arthurevans  Can you link me to where you got the above html?

**Comment by jsilvermist** [comment]
@katejeffreys [Polymer/polymer-cli polymer-2-element index.html](https://github.com/Polymer/polymer-cli/blob/master/src/init/element/templates/polymer-2.x/index.html)

**Comment by katejeffreys** [comment]
https://github.com/PolymerLabs/polymer-2-first-element/pull/4
