### ISSUE TITLE
Out-of-date docs: `polymer build` no longer generates bundled and unbundled builds by default

### ISSUE THREAD

**Issue by keanulee** [Polymer/docs#2089]
https://github.com/Polymer/docs/blob/master/app/2.0/toolbox/server.md#build-output

(Ran into this when someone privately messaged me asking me about this.)

Now, you need to specify custom builds using polymer.json.

**Comment by katejeffreys** [comment]
Addressed in this PR: https://github.com/Polymer/docs/pull/2047/files
