### ISSUE TITLE
API Tab

### ISSUE THREAD

**Issue by e111077** [Polymer/docs#2090]
It would be really helpful to add an API tab at the top that just points to the API reference page. Sometimes I just want to get to the API which requires 2 clicks from polymer-project.org

**Comment by katejeffreys** [comment]
Thanks for this. We have thought about this in the past and it's good to have this input on a user's preference and reported usability. I am going to close this issue because that decision will be incorporated when we revisit the site structure in coming weeks.

**Comment by katejeffreys** [comment]
@wmginsberg

**Comment by arthurevans** [comment]
Yeah, +1 on this. But as @katejeffreys said, it requires a restructuring of the existing site, so it's got to go into the big pot of Things We Want.
