### ISSUE TITLE
document mutation observer patterns/best practices?

### ISSUE THREAD

**Issue by jmesserly** [Polymer/docs#212]
There has been a decent amount of discussion on polymer-dev about using mutation observers instead of other ways of using the DOM (e.g. why enteredView/leftView shouldn't be events, why MutationObservers work for seeing `<template if>` expand). Perhaps we can expand on http://www.polymer-project.org/platform/mutation-observers.html to include this information?

Thanks to @adambender for noticing this!

**Comment by arthurevans** [comment]
Crickets. I think the new observeNodes feature (documented) probably eliminates the need to do most  MO stuff in Polymer (it uses MOs under the hood, but is distribution-aware). Thoughts?

**Comment by ebidel** [comment]
Yea, let's close.
