### ISSUE TITLE
Code highlighter doesnt work

### ISSUE THREAD

**Issue by abdonrd** [Polymer/docs#2129]
I take a screenshot:

<img width="693" alt="screen shot 2017-05-15 at 3 18 36 pm" src="https://cloud.githubusercontent.com/assets/1007051/26081893/d2efd096-3981-11e7-8f1d-e27669bdb7c8.png">

**Comment by abdonrd** [comment]
Ping to @arthurevans :)

**Comment by arthurevans** [comment]
Ping @notwaldorf This was never all that reliable, but it appears with recent changes we've broken it entirely. We should probably just figure out how to highlight these pages at build time like the rest of the docs...

**Comment by notwaldorf** [comment]
Uhhhhhh this is true, it doesn't seem to work.

**Comment by notwaldorf** [comment]
Dunno what's up. Nothing seems to have changed, stuff doesn't seem to highlight. @keanulee, you've spent some time 👁 the gulp file -- do you know how we can server-side highlight the `index.html`?

**Comment by arthurevans** [comment]
I did a trial balloon here (#2159), but it's mangling boolean attributes so it's Not Ready For Prime Time. Suggestions welcome.

**Comment by abdonrd** [comment]
Any news? 😄
