### ISSUE TITLE
iron-a11y-keys element not listed as an available 2.0 element in "Whats New in 2.0", but it is

### ISSUE THREAD

**Issue by akc42** [Polymer/docs#2146]
I was following the 2.0 upgrade guide to see what to put in my bower.json file for 2.0, which then pointed me at "Whats new in 2.0" page where there is a list of supported elements.  `iron-a11y-keys-behavior` is listed, but the simple element which uses that behavior wasn't.  Since I use the actual element I followed checked the repository for it, and there is a 2.0 release for it

**Comment by akc42** [comment]
I also found that `iron-form-element-behavior` is also missing, but a 2.0.0 version exists in the repository

**Comment by katejeffreys** [comment]
https://github.com/Polymer/docs/pull/2156

Thanks!
