### ISSUE TITLE
Moving to yarn and webpack

### ISSUE THREAD

**Issue by johnthad** [Polymer/docs#2151]
When I upgraded `polymer-cli` from 0.18.1 to 1.0.2, the first thing I saw was this warning:
```
$ npm install -g polymer-cli
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend 
 yarn and webpack for new front-end projects! Please read our blog for more.
```
I cannot find this blog entry at https://www.polymer-project.org/blog/ 

What's the story?

**Comment by jsilvermist** [comment]
That deprecation is for bower, for the full story see:
https://bower.io
OR
https://bower.io/blog/
OR
https://twitter.com/bower

**Comment by web-padawan** [comment]
Webpack has nothing to do with HTML imports yet, and is unlikely to be. I think we are stuck with `polymer-bundler` unless Polymer 3 adopts ES modules instead.

**Comment by katejeffreys** [comment]
@johnthad, thanks for the heads-up. @jsilvermist, thanks for the info. I will add a note to the Polymer CLI install docs.
