### ISSUE TITLE
Wrong import on upgrade guide for Polymer.RenderStatus.afterNextRender?

### ISSUE THREAD

**Issue by KevinAsher** [Polymer/docs#2212]
At the [polymer 2.0 upgrade guide](https://www.polymer-project.org/2.0/docs/upgrade), it says:

> If you're loading the polymer-element.html import, you need to import Polymer.RenderStatus separately. 
`<link rel="import" href="/bower_components/polymer/lib/utils/flattened-nodes-observer.html">`

Shouldn't it be `<link rel="import" href="/bower_components/polymer/lib/utils/render-status.html">
`  instead?

**Comment by arthurevans** [comment]
Yes, yes it should. @katejeffreys could you take this one?
