### ISSUE TITLE
Binding to array elements

### ISSUE THREAD

**Issue by coreyfarrell** [Polymer/docs#2228]
[Data binding](https://www.polymer-project.org/2.0/docs/devguide/data-binding#array-binding) docs says not to use `<span>{{array.0}}</span>`.  This actually works.  Is this a bug in polymer or in the documentation?  Is there some limitation to array element binding in this form?

**Comment by katejeffreys** [comment]
It does not work for me, unless I have misunderstood :). Here is a plunk of it not working.

http://plnkr.co/edit/7HCCj8iANU5d63Earw5T?p=preview

Can you show me your code, and how it works?

**Comment by coreyfarrell** [comment]
I've updated your plunk.. you can't set `this.prop1[0] = 'newval';`, you have to use `this.set()`.  It is the same for arrays as it is for objects, see https://www.polymer-project.org/2.0/docs/devguide/data-binding#path-binding

I've forked your plunk and modified to show it functioning: http://plnkr.co/edit/OYEbSSBboJuAnRw6IS1i?p=preview

**Comment by katejeffreys** [comment]
Thanks! This is cool! I will check in with the engineers and update docs accordingly.

**Comment by katejeffreys** [comment]
@arthurevans Can you check this out and LMK who can verify what the behavior should be?

**Comment by arthurevans** [comment]
The docs are correct—you shouldn't use that format. It's true that it will work in some cases. However, the way the binding is set up, it doesn't track any array mutations. Here's an updated version of the plunker showing an array mutation. As you can see, while a full replacement of the array gets reflected, an array mutation that reorders the array doesn't get reflected by the static `array.0` style bindings, but does get reflected in a dom-repeat (or the computed binding shown in that section of the docs).

http://plnkr.co/edit/fObsK9cPWCIIFB6AYSBB?p=preview

**Comment by katejeffreys** [comment]
Looking through old issues, I found this: #1461

@arthurevans Is that the same issue, or is it related?

**Comment by arthurevans** [comment]
Short answer: not really. I followed up over there with more details on that issue.
