### ISSUE TITLE
`Dom-module` documentation issue

### ISSUE THREAD

**Issue by galanovnick** [Polymer/docs#2236]
In the [dom-module](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.DomModule) documentation we have example with the `import` command. `Import` is presented as a method of the instance but it seems like it's a static method.

Plese, check this out and consider to change `document.createElement('dom-module').import` to `Polymer.DomModule.import`.

**Comment by katejeffreys** [comment]
@arthurevans Can you comment on this?

**Comment by arthurevans** [comment]
Seems correct—I wonder if @sorvell or @kevinpschaaf can comment if there's any reason it should stay the way it is.

These API docs are built from the Polymer source, so I'll move it over there.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/polymer#4740
