### ISSUE TITLE
No docs on annotations, like: @polymerMixin

### ISSUE THREAD

**Issue by vedtam** [Polymer/docs#2241]
Hi,

Please consider adding some documentation about annotations like the: `@polymerMixin`. Right now I couldn't find any mention about it after receiving several warnings:

```
const DatastoreMixin = (superClass) => class extends superClass {
                                                         ~~~~~~~~~~
src/mixins/datastore-mixin.html(1,57) warning [unknown-superclass] - Unable to resolve superclass superClass
```

during the build process.

Thanks!

**Comment by chiefcll** [comment]
👍

**Comment by JohnRiv** [comment]
Furthermore, it appears the annotations changed from Polymer 2.0.1 to 2.0.2: https://github.com/Polymer/polymer/commit/f7e8021e

**Comment by arthurevans** [comment]
Mixin annotations are now documented: https://www.polymer-project.org/2.0/docs/tools/documentation#class-mixins
