### ISSUE TITLE
Update Polymer/docs code to Polymer 2.x

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [Polymer/docs#2242]

**Comment by FluorescentHallucinogen** [comment]
Also currently `Polymer/docs` using the old and/or deprecated versions of dependencies such as `app-layout#^0.0.14` and `firebase-element#^1.0.12`.

**Comment by katejeffreys** [comment]
This is outside our bandwidth at the moment. Open to the community for action.

**Comment by arthurevans** [comment]
We've upgraded the dependencies to the latest versions compatible with Polymer 1.x. As @katejeffreys don't have any immediate plans to port to 2.x. I might take that up after the Summit.

**Comment by arthurevans** [comment]
I believe @keanulee is already working on this. Yay!
