### ISSUE TITLE
templates.md typo and quibble.

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#2244]
```
<template is="dom-repeat" items={{items}} mutable-data> ... </template>
```

items attribute needs quotes.

```
You can also set a debounce time that must pass before a filter or sort function is re-run by setting the delay property.
```

This doesn't seem to tell the same story as the API:
https://www.polymer-project.org/2.0/docs/api/elements/Polymer.DomRepeat#property-delay

Notably, if the filter is dynamically generated, and the filter changes rapidly (ie as the user types), this delay has no effect. It only applies to changes in the template items data. Please correct me if I'm wrong.

**Comment by katejeffreys** [comment]
#2261 corrects the typo, thanks.

Regarding the second part of this, I don't follow. Reading the API docs and the devguide page, I interpret them as saying the same thing:

API Docs: 

>When using a filter or sort function, the delay property determines a debounce time after a change to observed item properties that must pass before the filter or sort is re-run. 

devguide page:

>You can also set a debounce time that must pass before a filter or sort function is re-run by setting the delay property.

Could you explain a bit more to help me get it? Maybe if you have a code sample where the delay has no effect?

**Comment by davidmaxwaterman** [comment]
Well, I'm not sure really. I imagine I'm really just saying that, if the filter is dynamically generated, then the delay doesn't stop it being generated for every change in the dependency. IE,

```
<input value="{{_filterText}}">
<template ... filter="[[_generateFilter(_filterText)]]"
```

adding `delay` makes no difference. Very likely, this is because it isn't related to the dom-repeat element, but to the binding system. I implemented `Polymer.debounce()` in the `_generateFilter()` to have the same effect as I was expecting from the `delay` setting.

I think I was just mistaken. I was confusing the debouncing of changes to the item properties (which delay does) with the debouncing of changes to the dependency of the filter generating function (which I need to implement myself).

**Comment by katejeffreys** [comment]
Adding @arthurevans in case he can illuminate further.

**Comment by katejeffreys** [comment]
Ok... It sounds like you are saying this is no longer an issue so I will close it at the end of the week, unless you request otherwise, @davidmaxwaterman.
