### ISSUE TITLE
Give a full app example from front to end in polymer 2.0 doc, ex, a blog example

### ISSUE THREAD

**Issue by spyhole** [Polymer/docs#2250]

**Comment by web-padawan** [comment]
BTW what about mentioning [Polymer Hacker News](https://github.com/Polymer/hn-polymer-2) and describing some of the best practices used there?

**Comment by katejeffreys** [comment]
We have the 2.0 Shop app: https://github.com/Polymer/shop

Documentation is here: https://www.polymer-project.org/2.0/toolbox/case-study

This PR updates the code samples in the documentation to use the 2.0 syntax found in the app: #2263

**Comment by spyhole** [comment]
@katejeffreys and @web-padawan thanks
