### ISSUE TITLE
[IMPORTANT] Can't change the documentation version

### ISSUE THREAD

**Issue by limonte** [Polymer/docs#2257]
Version selector dropdown doesn't work in Chrome 59, both Linux and macOS:

![recorded](https://user-images.githubusercontent.com/6059356/28366339-ed047400-6c94-11e7-8553-58a2fc11ffb6.gif)

**Comment by arthurevans** [comment]
Version selector should be fixed now. You may need to refresh the page.

**Comment by limonte** [comment]
Fixed, thanks.
