### ISSUE TITLE
[CRITICAL] Documentation doesn't work in Firefox

### ISSUE THREAD

**Issue by limonte** [Polymer/docs#2258]
Currently documentation (e.g https://www.polymer-project.org/2.0/docs/upgrade) doesn't work in Firefox, both in Linux and macOS

Just empty white screen is shown, no errors in console.

**Comment by web-padawan** [comment]
I confirm the white screen, while seeing following error: 
```
SyntaxError: ':not([style-scope]):not(.style-scope):host,html:not([style-scope]):not(.style-scope)' is not a valid selector  pw-shell.html-2.js:1

hostAndRootPropertiesForScope/</< https://www.polymer-project.org/elements/pw-shell.html-2.js:1:60031
	whenHostOrRootRule https://www.polymer-project.org/elements/pw-shell.html-2.js:1:59816
	hostAndRootPropertiesForScope/< https://www.polymer-project.org/elements/pw-shell.html-2.js:1:59972
	C https://www.polymer-project.org/elements/pw-shell.html-2.js:1:42219
	forEachRule https://www.polymer-project.org/elements/pw-shell.html-2.js:1:42492
	forEachRule https://www.polymer-project.org/elements/pw-shell.html-2.js:1:42653
	forEachRuleInStyle https://www.polymer-project.org/elements/pw-shell.html-2.js:1:42255
	forActiveRulesInStyles https://www.polymer-project.org/elements/pw-shell.html-2.js:1:41877
	hostAndRootPropertiesForScope https://www.polymer-project.org/elements/pw-shell.html-2.js:1:59923
	get _styleProperties https://www.polymer-project.org/elements/pw-shell.html-2.js:1:63759
	_updateStyleProperties https://www.polymer-project.org/elements/pw-shell.html-2.js:1:65939
	_beforeAttached https://www.polymer-project.org/elements/pw-shell.html-2.js:1:65703
	attachedCallback https://www.polymer-project.org/elements/pw-shell.html-1.js:1:3176
	s https://www.polymer-project.org/bower_components/webcomponentsjs/webcomponents-lite.min.js:12:91
	a

```

Looks like this is related to the one of the recent changes related to `forEachRule`. 
/cc @azakus for that.

**Comment by felixzapata** [comment]
the same error to me

![captura de pantalla 2017-07-19 a las 15 17 28](https://user-images.githubusercontent.com/997038/28368699-92b0ff2c-6c95-11e7-82bc-37009b20da35.png)

And I do not know if it is related with this issue but in Chrome, you can't select now the version inside the documentation.

![captura de pantalla 2017-07-19 a las 15 16 19](https://user-images.githubusercontent.com/997038/28368723-aac8d274-6c95-11e7-9562-a7005cda611e.png)

**Comment by DiegoCardoso** [comment]
When I opened the link on Firefox, it didn't work, but when I opened the project homepage  (https://www.polymer-project.org/) and navigated to the docs, it worked.

@felixzapata about the second issue, @limonte opened one here already: https://github.com/Polymer/docs/issues/2257

**Comment by web-padawan** [comment]
Just realized that docs are still using `1.9.2`, and looks like it has already been fixed.

**Comment by azakus** [comment]
Should be fixed with Polymer 1.9.3.

**Comment by keanulee** [comment]
May require to refresh the page again so that the service worker gets a chance to precache the latest version.

**Comment by limonte** [comment]
Thanks, confirm that everything work fine now :+1:
