### ISSUE TITLE
Typo at the upgrade guide for async

### ISSUE THREAD

**Issue by KevinAsher** [Polymer/docs#2273]
At [https://www.polymer-project.org/2.0/docs/upgrade#async](https://www.polymer-project.org/2.0/docs/upgrade#async) it shows the following code snippet

`// in JS, execute someMethod with microtask timing` 
`Polymer.Async.microtask.run(() => this.someMethod());`

`microtask` should actually be `microTask`, as it is implemented [here](https://github.com/Polymer/polymer/blob/master/lib/utils/async.html#L169)

**Comment by hunex91** [comment]
I just wanted to report this type too :) Glad I checked first.
