### ISSUE TITLE
New blog entries don't show up on homepage

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#2278]
When you have an active serviceworker and we add a new blog entry, the new entry shows up on the Blog page, but not at the bottom of the homepage.

I think we need to add `app/blog.yaml` and `app/authors.yaml` to the dependencies list for the homepage: https://github.com/Polymer/docs/blob/master/gulpfile.js#L126

**Comment by arthurevans** [comment]
@keanulee WDYT?

**Comment by keanulee** [comment]
Yup, that sounds like the correct fix.
