### ISSUE TITLE
Styling elements before they're defined (was: unresolved)

### ISSUE THREAD

**Issue by nicolasr75** [Polymer/docs#2297]
It would be nice to have some documentation about **unresolved** and its use in Polymer. I stumbled across this because someone on stackoverflow pointed me to the shop demo app which uses it. I was unable to find any 2.x documentation although some existed for 0.5 https://docs-05-dot-polymer-project.appspot.com/0.5/docs/polymer/styling.html#fouc-prevention.
It is unclear for new users like me how much I should be concerned about this and whether this is still supported in 2.x.

**Comment by arthurevans** [comment]
The custom elements v1 spec includes the `:defined` pseudoclass, so theoretically you can style not-yet-defined elements using `:not(:defined)`. However, it appears that this isn't supported in the polyfill.

This section mentions `:defined`, and should be updated to say that the polyfill doesn't support it.

https://www.polymer-project.org/2.0/docs/devguide/custom-elements#element-upgrades

We should add a section to the styling doc explaining how to style undefined elements. The usual workaround here is to add an `unresolved` attribute to the element in markup, like this:

https://github.com/Polymer/news/blob/master/index.html#L73

Then style the unresolved element, like this:

https://github.com/Polymer/news/blob/master/index.html#L36

And finally, remove the `unresolved` attribute in the element's `ready` callback (or elsewhere, but `ready` makes sense):

https://github.com/Polymer/news/blob/master/src/news-app.html#L210

**Comment by arthurevans** [comment]
Documented here: https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-undefined-elements
