### ISSUE TITLE
mixin example missing semicolon

### ISSUE THREAD

**Issue by robrez** [Polymer/docs#2305]
The 1.0 -> 2.0 migration guide has a code snippet defining a style mixin. I noticed it was missing a `;` and wasn't sure if v2.0 intentionally dropped the semi-colon v1.0 required or if this was a typo:

```
    html {
      --my-mixin: {
        color: blue;
      }
    }
```

https://www.polymer-project.org/2.0/docs/upgrade#class-based-elements-import-the-css-mixin-shim

**Comment by jsilvermist** [comment]
I believe according to the spec there's supposed to be a semicolon at the end the same as any other property, and my editor marks this as incorrect syntax without a semicolon, so probably a typo.
