### ISSUE TITLE
Intermittent load failures

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#2319]
When I navigate to the site via a link, I sometimes get a loading error like this:

This site can’t be reached

The webpage at https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED

This appears to be related to the service worker. Simply reloading the page doesn't help. Empty cache+hard reload seems to fix it. And if I load it in an incognito window, it works fine.

**Comment by arthurevans** [comment]
Sending to @keanulee who touched the SW last :D

**Comment by keanulee** [comment]
Can't seem to reproduce - I load https://www.polymer-project.org in an incognito window (to get a fresh SW), open a new incognito tab (which shares the same SW), then https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements loads fine.

**Comment by arthurevans** [comment]
So, I'm _only_ seeing this in windows that have been open for a long time, and opening them in an incognito tab fixes the problem. There's nothing specific to the URL—I've gotten this error for all kinds of different pages on the site.

I've recently found this message logged, apparently in conjunction with the 

The FetchEvent for "https://www.polymer-project.org/2.0/docs/devguide/custom-elements" resulted in a network error response: an object that was not a Response was passed to respondWith().
Promise resolved (async)
r @ service-worker.js:formatted:541
Navigated to data:text/html,chromewebdata

Don't know what's up here, but I'm getting it a _lot_.
