### ISSUE TITLE
Publish new element

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/docs#2332]
_From @avizcaino on June 23, 2017 6:46_

### Description

Hi!, is there any documentation/guidelines on how to publish a Polymer 2 element such it was on Polymer 1 [here](https://www.polymer-project.org/1.0/docs/tools/reusable-elements)? I've been searching and couldn't find anything.

Also the documentation tools for Polymer-CLI are not published yet [here](https://www.polymer-project.org/2.0/docs/tools/documentation).

### Versions & Environment

- Polymer CLI: 1.2.0
- node: 6.9.2
- Operating System: macOS

#### Steps to Reproduce
Not needed.

#### Expected Results
Similar tools as the provided ones on Polymer 1 [here](https://www.polymer-project.org/1.0/docs/tools/reusable-elements#publishing-a-demo-and-landing-page-for-your-element)

#### Actual Results
No documentation or similar tools found for Polymer 2

_Copied from original issue: Polymer/polymer-cli#808_

**Comment by arthurevans** [comment]
We should probably add a pointer to the webcomponents.org page on publishing elements (https://www.webcomponents.org/publish).

Maybe also add instructions for hosting docs locally on github pages? Steps are a little different. And/or link to Monica's indycatalog (https://github.com/PolymerLabs/indie-catalog).

**Comment by arthurevans** [comment]
Related: #1762. But because we need to build the analysis file and include dependencies, using gh-pages branch is probably preferable to cluttering up the installable package with those things. So we should probably close that one.
