### ISSUE TITLE
"Change notification events" section cut short

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#2344]
https://www.polymer-project.org/1.0/docs/devguide/data-system#data-flow-objects-arrays

"
For an array mutation, the detail.path field is an array mutation path, such as "myArray.splices", and the detail.value
"

That sentence needs finishing - it surely requires significant detail, or a reference to where that detail is elsewhere.

**Comment by katejeffreys** [comment]
KJ to update with this from Arthur

It should say that the detail.value field is a change record, like the one described here: https://www.polymer-project.org/2.0/docs/devguide/observers#array-observation


[11:38] 
It might also be worth noting that when you mutate an array, it frequently generates two change events (`.splices` and if the length changed, `.length` as well).

**Comment by katejeffreys** [comment]
Also needs done in 2.0 docs
[] done in 1.0
[] done in 2.0

**Comment by davidmaxwaterman** [comment]
> It might also be worth noting that when you mutate an array, it frequently generates two change events (.splices and if the length changed, .length as well).

AHA! I was wondering about that. Great to know that isn't an error and something I need to avoid.

Thanks for fixing this and adding that 'juicy titbit' ;)
