### ISSUE TITLE
Gesture events recommended or not ?

### ISSUE THREAD

**Issue by plequang** [Polymer/docs#2352]
It's not clear if gesture events are recommended or not.

In https://www.polymer-project.org/2.0/docs/devguide/gesture-events, it is written 
> Polymer provides optional support for custom "gesture" events for certain user interactions. These events fire consistently on both touch and mouse environments, so we recommend using these events instead of their mouse- or touch-specific event counterparts. 

But in a recent PR (#2283), tip about using `tap`  rather the `click` was removed from the documentation.

Also, this issue https://github.com/PolymerElements/app-layout/issues/465 recommends using native `click`.

As gesture events are an option in Polymer 2.x,  maybe they should not be recommended in the documentation.

**Comment by arthurevans** [comment]
You're right, this should be clarified. 

The `tap` event is included for backwards compatibility, but it's no longer required in modern mobile browsers, which have eliminated the problematic `click` delay. We should note this in the docs and tell people to just use `click` instead.

I believe the `up`, `down` and `track` events are still useful for creating cross-device gesture handling, but I think @azakus can confirm.
