### ISSUE TITLE
Links to protected API's do not work

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/docs#2357]
Opening https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-_parseBindings does not scroll the `_parseBindings` method into view. It would be nice that, if it determines that the method is defined as protected, the protected API is automatically opened and scrolled into.

**Comment by keanulee** [comment]
(Hi @TimvdLippe!)

Duplicate of https://github.com/PolymerElements/iron-doc-viewer/issues/153
