### ISSUE TITLE
Batch changes section no longer exists

### ISSUE THREAD

**Issue by justincy** [Polymer/docs#2360]
In the [Work with arrays](https://github.com/Polymer/docs/blob/4090e015f222b6848d7dd46ea31867bd55d1c9ce/app/2.0/docs/devguide/model-data.md) section, the second paragraph says

> ...as described in [Batch changes to an object or array](https://github.com/Polymer/docs/blob/4090e015f222b6848d7dd46ea31867bd55d1c9ce/app/2.0/docs/devguide/model-data.md#work-with-arrays-work-with-arrays).

The batch changes sections doesn't appear to exist anymore so the link is broken.

**Comment by arthurevans** [comment]
Good catch, thanks. We removed that section but missed the link. We should remove the link.

If you need this feature, you can do batch changes to an object or array if you're using the MutableData mixin (https://www.polymer-project.org/2.0/docs/devguide/data-system#mutable-data).

(You could also do a deep clone of the object or array, mutate it, and then reassign the updated object to the property.)
