### ISSUE TITLE
Demos broken in routing blog post

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#2363]
These samples used to work, now they're broken:

https://www.polymer-project.org/blog/routing.html

(Currently showing part of the site instead of the demo... Maybe an error with the python server, service worker, or the url-space-regex in the router ...)

Also, ran across an old link to this URL, which should be redirecting to the URL above, but wasn't:

https://www.polymer-project.org/1.0/articles/routing.html

**Comment by arthurevans** [comment]
cc: @keanulee in case he's feeling bored on a Friday :D

**Comment by keanulee** [comment]
Root cause is that #2232 loads the shell for all routes, even /blog/routing/demo*.html which do not follow that page structure. I'm working on moving those demos off to JSBin, but they need to be updated/fixed.

AFAICT the redirect for https://www.polymer-project.org/1.0/articles/routing.html is working.

**Comment by arthurevans** [comment]
@keanulee How come our homepage and Try Polymer demos work OK, but these don't?

BTW, turns out the issue for the other URL is that we have a link from another blog post using the older URL, and since it has an ".html" on the end it's escaping the redirect. Or maybe just because we don't handle redirects for internal links. Anyway, fixable in source.

**Comment by keanulee** [comment]
So any URL with "samples" won't serve the shell:
https://github.com/Polymer/docs/blob/master/gulpfile.js#L101

Side note - no idea why "samples" uses `pwShellSWHandler` - it could just be `networkFirst`
https://github.com/Polymer/docs/blob/master/gulpfile.js#L175

Maybe move them to a "samples" subdirectory?

(Just finished moving them JS Bin only to discover they're not embeddable in iframes 😞 ).
