### ISSUE TITLE
polymer serve (compile)

### ISSUE THREAD

**Issue by robrez** [Polymer/docs#2369]
I've been using an overcomplicated workflow specifically when wanting to serve for ie11:

- `polymer build`
- `polymer serve build/es5-bundled`

Then I happened to read some documentation that is present on the polymer cli repo's README...

>By default, the server will automatically use Babel to transpile any ES6 code down to ES5 for browsers that don't have native support for important ES6 features like classes. This behavior can be explicitly turned on/off for all browsers via the --compile option.

Should this be added to the `polymer serve` documentation? Pehaps along with an example in the "server options" section that demonstrates the --compile flag?

Thanks

**Comment by arthurevans** [comment]
We mention this in the section on es6, but if we don't mention it under polymer serve, we definitely should, because it's a little bit of magic that could be confusing (why does my code work on IE with Polymer serve, but not when I deploy it?)

**Comment by katejeffreys** [comment]
#2370
