### ISSUE TITLE
Polymer 2.2.0 not working in IE11

### ISSUE THREAD

**Issue by arthurevans** [Polymer/docs#2384]
_From @EnzoEghermanne on October 24, 2017 19:26_

### Description
None of the code samples from https://www.polymer-project.org/2.0/start/quick-tour work on IE11.

#### Live Demo
http://plnkr.co/edit/Q4E8zO?p=preview
http://plnkr.co/edit/buPxSJ?p=preview

#### Steps to Reproduce
1. Open any of the plunkers in IE11
2. Check the console output (10 errors)

#### Expected Results
The component renders in IE11.

#### Actual Results
![errors](https://user-images.githubusercontent.com/6171742/31962754-b8a3dab4-b8fe-11e7-94ea-8e1755013729.png)

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [X] IE 11

### Versions
- Polymer: v2.2.0
- webcomponents: v1.0.0-rc.5

_Copied from original issue: Polymer/polymer#4900_

**Comment by arthurevans** [comment]
_From @TimvdLippe on October 24, 2017 19:33_

There seem to be 2 issues:

1. You are not transpiling. As IE11 does not support ES6, you have to transpile. `polymer serve` does this automatically for you. Else you have to run `babel` or use `polymer build` with `es5-bundled`
2. Your polyfill version is quite old. Please upgrade to [1.0.17](https://github.com/webcomponents/webcomponentsjs/releases/tag/v1.0.17)

**Comment by arthurevans** [comment]
_From @azakus on November 14, 2017 20:42_

What @TimvdLippe says is correct, IE 11 requires transpiling your code to ES5. This can be done with the [Polymer command line tool](https://github.com/polymer/polymer-cli), or any number of other tools.

**Comment by arthurevans** [comment]
These are the samples in the quick tour, so this should really be a doc bug.

1) Currently we don't have a good way to transpile the plunkers for IE11. We're working on a fix for that.

2) But we can (and should) add a note that the samples don't work on IE11, because they need to be transpiled.

3) And we should update the plunkers to use a released version of the polyfill. (The polyfill line in all of these plunkers should probably just be: `<script src="https://polygit.org/components/webcomponentsjs/webcomponents-loader.js"></script>`)

**Comment by katejeffreys** [comment]
Updated with correct polyfill: 
* http://plnkr.co/edit/Q4E8zO?p=preview
* http://plnkr.co/edit/buPxSJ?p=preview
* http://plnkr.co/edit/KvBnmE?p=preview
* http://plnkr.co/edit/8mZK8S?p=preview
* http://plnkr.co/edit/3Nz8GL?p=preview
* http://plnkr.co/edit/03HGzn98uIN5I1WgkDwu?p=preview
* http://plnkr.co/edit/FdgkAtcLFHX5TpTsYtZn?p=preview

**Comment by TimvdLippe** [comment]
@luan-cestari IE11 does not support ES6, so you can not use the class syntax. You have to use the Polymer hybrid syntax or transpile from ES6 to ES5 with transpilers like Babel to make it work.

**Comment by TimvdLippe** [comment]
Oh pardon, this was the wrong post I was replying to. The plunkers are working for me on Firefox 59. Could you upgrade your browser and see if that fixes the issue?

**Comment by TimvdLippe** [comment]
Per https://www.polymer-project.org/2.0/docs/browsers we support the last 2 versions of Firefox. The polyfills should just work for Firefox 58 as well :thinking:

**Comment by TimvdLippe** [comment]
Yes please.
