### ISSUE TITLE
boolean property is undefined if HTML attribute corresponding to property is not set

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/docs#2405]
_From @punzki on June 9, 2015 0:37_

See: http://jsbin.com/xoruqa/1/edit?html,console,output

According to the documentation at https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-deserialization:

> Boolean properties set based on the existence of the attribute: if the attribute exists at all, its value is true, regardless of its string-value (and the value is only false if the attribute does not exist).

Yet from the above jsbin, it is clearly being set us `undefined`. A workaround is to set a default value of `false` for the property, but this should not be required.

_Copied from original issue: Polymer/polymer#1794_

**Comment by TimvdLippe** [comment]
_From @punzki on June 15, 2015 23:38_

Thanks for the clarification. But I do think that in general, deserialization of Boolean properties can be quite confusing. As you say, "the lack of an attribute will not result in deserialization," but how else are developers supposed to declare that a property of the custom element should be `false`?

The only thing that will make the custom element behave logically is to always set a default value of `false` for a property. I'd try to see if there's a way to make this more clear in the docs.

**Comment by TimvdLippe** [comment]
@arthurevans I think we should move this to the docs, if it hasn't been addressed already?

**Comment by katejeffreys** [comment]
@TimvdLippe 

https://html-helper-dot-polymer-project.appspot.com/2.0/docs/devguide/properties#configuring-boolean-properties

https://html-helper-dot-polymer-project.appspot.com/1.0/docs/devguide/properties#configuring-boolean-properties

Both pages mention this behavior - is it ok to close this issue?

**Comment by TimvdLippe** [comment]
Yes seems fine :)
