### ISSUE TITLE
Template bound variables which are undefined leave a space between open and closing tag

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/docs#2426]
_From @klebba on November 24, 2015 21:4_

It's not possible to use the css `:empty` selector on a template bound property which is `undefined` because there is a space inserted in the tag.

For example:

```
<span>[[myBoundVar]]</span>
```

when `myBoundVar === undefined`, the tag will look like `<span> </span>` -- note there's a space inserted here

when `myBoundVar === ''` the tag will look like `<span></span>` and then its possible to use `:empty` selectors on the tag

This behavior is new in Polymer 1.0 -- previous versions handled `undefined` and `''` the same way in template bindings

Repro: http://codepen.io/klebba/pen/jbovye

_Copied from original issue: Polymer/polymer#3086_

**Comment by TimvdLippe** [comment]
After a quick investigation, it appears that [the parser of text annotations](https://github.com/Polymer/polymer/blob/master/src/lib/annotations/annotations.html#L182) is the culprit. However, this seems intentional reading the note of @kevinpschaaf [in the test suite](https://github.com/Polymer/polymer/commit/2f1bd31d4e75b00407647cc822477d98db6c2d0f#diff-f34edf90299c8a4197ca5874d411e293R770).

Therefore it seems necessary to instantiate empty `String`s with `''` to prevent this from happening (and breaking in other browsers such as IE).

This is maybe a good thing to add in the documentation. cc @ebidel

**Comment by TimvdLippe** [comment]
_From @klebba on November 28, 2015 8:50_

Thanks for investigating -- it would be nice to know if this is strictly an IE workaround. It's strange that if I initialize the property with an empty string it works as expected. This seems contrary to the inline comments, or maybe I misunderstood them

**Comment by TimvdLippe** [comment]
Speculation:

On startup, the initial value of the `span` is `' '`. IE checks if the span is empty, which is not, so it leaves the node intact. Then Polymer assigns the default value to the node and sets the `span` to `''`.

This is pure speculation, a core developer could maybe clarify.

**Comment by TimvdLippe** [comment]
_From @kevinpschaaf on December 3, 2015 18:28_

What @JeremybellEU said is correct.  When cloning the template on IE, the text node inside `<span>{{foo}}</span>` that originally contained `{{foo}}` becomes empty, and thus IE removes it when calling `importNode` to clone the template.  Rather than complicate/slow the system with logic to re-insert empty textNodes in these positions after cloning, we took this simple approach or inserting a space.

The only immediate workaround is to ensure the value being bound is initialized to an empty space.

**Comment by TimvdLippe** [comment]
_From @klebba on December 3, 2015 22:58_

Ok, got it. Thanks for the explanation. This is a slight bummer because I'm not actually targeting IE

**Comment by TimvdLippe** [comment]
_From @klebba on November 12, 2016 1:41_

@kevinpschaaf will Polymer 2.x incorporate this same workaround?

**Comment by TimvdLippe** [comment]
_From @jehna on February 10, 2017 13:42_

@klebba At least the current `2.0-preview` branch seems to have the same issue & workaround (as I tested on #4295)

**Comment by TimvdLippe** [comment]
_From @klebba on February 14, 2017 2:8_

@jehna Dang. Worth noting that if you bind to an object's undefined property `2.0-preview` does not fill with a space, e.g. `<div>[[empty.empty]]</div>` where you have defined an object property like `empty: { type: Object, empty: undefined }`

If I remember correctly this is a different behavior from `1.x`

**Comment by TimvdLippe** [comment]
This is an unfortunate known limitation of the data-binding system. We should add a mention of this limitation in https://www.polymer-project.org/2.0/docs/devguide/data-binding#bind-to-text-content with a workaround noting that assigning an empty string does work (http://jsbin.com/kudezurohi/2/edit?html,output)

**Comment by katejeffreys** [comment]
@TimvdLippe @kevinpschaaf @arthurevans 

Here is my understanding of what needs to be mentioned in that section, hoping you can confirm or correct:

* Data binding an undefined property in an "empty" node will result in a space, instead of empty node (`<div>[[undefinedThing]]</div>` ==> `<div> </div>` instead of `<div></div>`)
* This is to stop IE from eating empty nodes during cloning
* The workaround, if you need it to be empty (e.g in order to use the css `:empty` selector) is to instantiate the property with empty string (`this.undefinedThing = ''` or `static get properties () { return { undefinedThing: { type: String, value: ''}};} etc)

**Comment by TimvdLippe** [comment]
That is correct!
