### ISSUE TITLE
Why there are Legacy callbacks listed in docs? Should new callbacks be listed instead?

### ISSUE THREAD

**Issue by limonte** [Polymer/docs#2435]
In https://www.polymer-project.org/2.0/docs/devguide/registering-elements legacy callback are listed:
![](https://i.imgur.com/4Q3NB4q.png)

Any particular reason to document non-native, legacy API for Polymer 2?

**Comment by TimvdLippe** [comment]
This probably needs to be removed and point to https://www.polymer-project.org/2.0/docs/devguide/custom-elements#element-lifecycle instead
