### ISSUE TITLE
Site broken with Firefox Native CE

### ISSUE THREAD

**Issue by karlcow** [Polymer/docs#2437]
This is a spin off of https://webcompat.com/issues/14819 issue.

## Steps to Reproduce:

The bulk of the issue is https://github.com/webcompat/web-bugs/issues/14819#issuecomment-357685273 (see screenshots)
1. With Firefox on Android (reproducible on desktop too)
2. Go to https://www.polymer-project.org/2.0/docs/devguide/feature-overview
3. (Note how the top banner is not visible)
4. Reload the page
5. (Note how the page is blank)

## Partial Analysis
From https://github.com/webcompat/web-bugs/issues/14819#issuecomment-357825104

[![Screenshot Description](https://webcompat.com/uploads/2018/1/8d4f248a-f3a0-40e0-924e-2c074ba188a4-thumb.jpg)](https://webcompat.com/uploads/2018/1/8d4f248a-f3a0-40e0-924e-2c074ba188a4.jpg)

hmm let's add the HTTP requests. Firefox gets a 404 Not Found on one of the requests.
https://www.polymer-project.org/bower_components/webcomponentsjs/webcomponents-hi-sd.js

[![Screenshot Description](https://webcompat.com/uploads/2018/1/113d8bdb-f2dc-472d-adc7-823748e673d4-thumb.jpg)](https://webcompat.com/uploads/2018/1/113d8bdb-f2dc-472d-adc7-823748e673d4.jpg)

Interestingly enough, Safari gets a response but for this URI.
https://www.polymer-project.org/bower_components/webcomponentsjs/webcomponents-hi.js

from 

```html
<script src="https://www.polymer-project.org/bower_components/webcomponentsjs/webcomponents-hi.js"></script>
```

while Firefox receives

```html
<script src="https://www.polymer-project.org/bower_components/webcomponentsjs/webcomponents-hi-sd.js"></script>
```

**Comment by web-padawan** [comment]
Related to webcomponents/webcomponentsjs#874
webcomponents/webcomponentsjs#817

**Comment by keanulee** [comment]
Probably some compatibility issue with native Custom Elements (https://twitter.com/FirefoxNightly/status/951009715584225280) and shimmed Shady DOM - this is the first browser with the combination. Will look into this; for now if you use Firefox please use a stable version.

**Comment by arthurevans** [comment]
Updated the polyfills on the site, and @keanulee says it tests out... Please let us know if the problem reoccurs!
