### ISSUE TITLE
Doc imperative/dynamic Import loading

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#244]
https://github.com/Polymer/polymer-dev/commit/271c8a2d156508944ccef5a1f7015ae13b542cb5

We've also included a helper mechanism for loading imports: `HTMLImports.whenImportsReady(callback)`. This will notify you when the imports existing in the document at call time have all loaded.

http://stackoverflow.com/a/21649225/274673

**Comment by arthurevans** [comment]
Closing 0.5 bugs.
