### ISSUE TITLE
Landing page: Eric's photo is a dead link

### ISSUE THREAD

**Issue by poweif** [Polymer/docs#2446]
Repro:

- Visit https://www.polymer-project.org/
- Scroll to section "Create your own elements"

See link which says 'Eric's Photo' as oppose to showing an actual photo.

**Comment by TimvdLippe** [comment]
Seems like we need to use https://twitter.com/ebidel/profile_image?size=mini for this instead, per https://stackoverflow.com/a/30322178/2761676
