### ISSUE TITLE
Add documentation for polymer-cli new `exclude` option for `minify` and `compile`

### ISSUE THREAD

**Issue by usergenic** [Polymer/docs#2448]
Polymer CLI has unreleased feature (but merged into master) to support expressing paths/patterns for matching files to `exclude` from minification and/or compilation as part of the `build` command.  The PR https://github.com/Polymer/polymer-cli/pull/952 has the code and a test or two to demonstrate it, but we don't yet have documentation for it.

**Comment by andrewspy** [comment]
Can someone update the documentation in [polymer.json spec](https://www.polymer-project.org/2.0/docs/tools/polymer-json) with an example? Is the option name "excludes" (or "exclude")? Should the "excludes" option be under "js" or "minify"? (i.e. Is the sample below valid?)

```json
{
  "builds": [
    {
      "preset": "es6-unbundled",
      "js": { 
        "minify": {
          "excludes": [
            "*.min.js",
            "bower_components/firebase/**/*.js",
            "firebase-database.js"
          ]
        },
        "compile": false
      }
    }
  ]
}
```

Also, currently VSCode warns that "minify" is expecting a "boolean", and as a user, I am really confused without proper documentation.

**Comment by andrewspy** [comment]
Just to share, the following works for me:-

```json
{
  "builds": [
    {
      "preset": "es6-unbundled",
      "js": { 
        "minify": true,
        "compile": false,
        "excludes": [
          "*.min.js",
          "bower_components/firebase/**/*.js"
        ]
      }
    }
  ]
}
```
