### ISSUE TITLE
Is the Behaviors doc page referenced in the side nav?

### ISSUE THREAD

**Issue by jjoselv** [Polymer/docs#2460]
I can't manage to find this page on the side nav:

https://www.polymer-project.org/2.0/docs/devguide/behaviors
(or)
https://github.com/Polymer/docs/edit/master/app/2.0/docs/devguide/behaviors.md

Am I missing something?

**Comment by web-padawan** [comment]
Yes you are: 
![screen shot 2018-02-06 at 11 29 43](https://user-images.githubusercontent.com/10589913/35851564-0f1cae00-0b31-11e8-9f3a-6460d1d56517.png)

**Comment by jjoselv** [comment]
Sorry, I confused it with Behaviours, I updated the descriptoin and title.

**Comment by web-padawan** [comment]
The behaviors page is documented in sidebar for 1.0 version but not for 2.0 (because of not being a native way to implement inheritance). There is a short mention here: https://www.polymer-project.org/2.0/docs/devguide/registering-elements#prototype-mixins

**Comment by jjoselv** [comment]
@web-padawan Should the page then have a warning text saying that same text?

I'll include one and you can tell me if it fits. :-)

**Comment by jjoselv** [comment]
#2461

**Comment by arthurevans** [comment]
This file should've been deleted, which is why it's not in the side nav. Did you find a link to it somewhere?
