### ISSUE TITLE
brocken link on upgrade.md

### ISSUE THREAD

**Issue by boguz** [Polymer/docs#2480]
on line 1470 of the upgrade.md file the link to "Fire custom events" is brocken.
It is pointing to [Fire Custom Event](https://github.com/Polymer/docs/blob/master/%7B%7B%7Bpolymer_version_dir%7D%7D%7D/docs/devguide/events#custom-events), which leads to a 404

**Comment by TimvdLippe** [comment]
This is working as intended, as the rendered version (https://www.polymer-project.org/2.0/docs/upgrade) correctly links to https://www.polymer-project.org/2.0/docs/devguide/events#custom-events The markdown files in this repository are not supposed to inter-link, but are instead rendered to the full docs site on https://www.polymer-project.org/
