### ISSUE TITLE
is it possible to apply styles to parent to child dom

### ISSUE THREAD

**Issue by santhoshrajuvysyaraju** [Polymer/docs#2489]
Hi I want to apply styles to parent dom to child dom both are in single file

here is the dom1 

`<dom-module id="nuxeo-document-viewer" assetpath="nuxeo-document-viewer/">
  <template>
    <style include="nuxeo-styles">
      nuxeo-dropzone {
        height: calc(80vh - 100px);
        display: block;
      }

      nuxeo-document-preview {
        width: 100%;
        height: calc(80vh - 100px);
        display: block;
      }

      nuxeo-document-blob {
        margin-top: 8px;
       /* display:none !important; */
      } 
     nuxeo-document-blob  .row .actions{
        display:none !important;
      }
      :host(.actions){
        display:none;
      }
     
    </style>

    <nuxeo-dropzone document="{{document}}" hidden$="[[document.properties.file:content.data]]" update-document=""></nuxeo-dropzone>
    <nuxeo-document-preview document="[[document]]" hidden$="[[!document.properties.file:content.data]]"></nuxeo-document-preview>
    <div class="testblob">
    <nuxeo-document-blob document="[[document]]" hidden$="[[!document.properties.file:content.data]]"></nuxeo-document-blob>
    </div>
  </template>

</dom-module>`

here is my dom2

`<dom-module id="nuxeo-document-blob" assetpath="nuxeo-document-blob/">
  <template>

    <style include="nuxeo-styles">
      :host {
        display: block;
      }
      .row {
        @apply --layout-horizontal;
        @apply --layout-center;
      }

      .row .info {
        @apply --layout-vertical;
        @apply --layout-flex;
      }

      .row .actions {
        @apply --layout-horizontal;
        @apply --layout-center;
      }

      .detail {
        opacity: .5;
      }

      .actions ::content paper-icon-button {
        width: 36px;
        height: 36px;
      }
    </style>

    <nuxeo-connection user="{{user}}"></nuxeo-connection>

    <template is="dom-if" if="[[blob]]">
      <div class="row">
        <div class="info">
          <div><a href="[[blob.data]]">[[blob.name]]</a></div>
          <div class="detail">[[formatSize(blob.length)]]</div>
        </div>
        <div class="actions" id="test_action">
          <nuxeo-slot slot="BLOB_ACTIONS" model="[[actionContext]]"></nuxeo-slot>
        </div>
      </div>
    </template>

  </template>

</dom-module>`

i want to apply the styles to dom2 in the first dom it is it possible to use the classes of 2 nd dom inside the first please help me to solve the issue.

**Comment by TimvdLippe** [comment]
Custom elements should not rely on behavior from the outside. Therefore, you should not update styles to a parent from a child.

What you can do is fire an event for the style-change you want to trigger, listen to the event in the parent and then change the styles accordingly (in the parent). By firing events up, you neatly separate the two elements with a clear API.

Closing this issue per the above clarification. Feel free to reopen if you are still running into problems.
