### ISSUE TITLE
There is something wrong on examples of docs

### ISSUE THREAD

**Issue by tankdeper** [Polymer/docs#2491]
![image](https://user-images.githubusercontent.com/13122039/37241701-69a9f17c-2498-11e8-823f-7f64b56d91c7.png)
![2wsq6juz 7t5wxau7 a5qtv](https://user-images.githubusercontent.com/13122039/37241721-b60c4a60-2498-11e8-90b0-9db0975c0b04.png)
For the second capture, where is the `users`? I think it should be declared in the element's constructor。

**Comment by TimvdLippe** [comment]
The first one is an actual typo. The second one is intended. For more information see #2463

**Comment by tankdeper** [comment]
There are some typos in some examples, still based on Polymer 1.X Object properties.

**Comment by TimvdLippe** [comment]
@tankdeper if you find more, please open a PR for them :)

**Comment by tankdeper** [comment]
Okay.

________________________________
