### ISSUE TITLE
Describe whether changed watchers can be called before `attached`

### ISSUE THREAD

**Issue by jyasskin** [Polymer/docs#293]
At http://www.polymer-project.org/docs/polymer/polymer.html#change-watchers, it's not clear when a _changed watcher_ can be called for the first time. Is it after `ready`? After `attached`? Is it guaranteed to be called once for the initial value of the attribute set as the element upgrades? Can it be called between `detached` and the next `attached`?

**Comment by arthurevans** [comment]
Closing 0.5 issues.
