### ISSUE TITLE
Styling reference > clarify scoping limitations of injected stylesheets

### ISSUE THREAD

**Issue by addyosmani** [Polymer/docs#294]
It would be great to summarize or link to Scott's answer about the limitations of polyfilling scoping for injected stylesheets at the moment. 

I can into this when attempting to add theming support to an element and think it would be useful for others:

http://stackoverflow.com/questions/22076302/how-do-you-scope-polymer-imports-stylesheets-which-are-dynamically-injected-int/22110355?noredirect=1#22110355

**Comment by arthurevans** [comment]
Closing 0.5 bugs.
