### ISSUE TITLE
Don't do syntax highlighting at runtime/page load time.

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#298]
Syntax hilighting in JS can take up to 300ms for our longest pages with heavy code. We should do the syntax highlighting ahead of time. This is a source of jank on Chrome stable. The ajax page is loaded and `prettyPrint()` runs.

![screen shot 2014-03-03 at 1 54 23 pm](https://f.cloud.github.com/assets/238208/2315043/633e8fb4-a31e-11e3-821c-77403a3641e3.png)

The reason it's done in JS right now is to avoid having to wrap all code blocks in `{% highlight %}`.

**Comment by arthurevans** [comment]
So, we're not likely to do this for the current site.

Is this a consideration for the next-gen doc site, it would be an argument for retaining the build step so we can do things like this in advance.

@ebidel @frankiefu WDYT?

**Comment by ebidel** [comment]
If we stick with jekyll, but I think we're just going pure HTML.

**Comment by arthurevans** [comment]
My point was -- if syntax highlighting at runtime is going to make our site janky, that might be an argument for jeckyll -- or at least for finding a way to syntax highlight at build time.

**Comment by ebidel** [comment]
Yea I understand. Right  now, we just turn it off on mobile (where jank would actually be a problem). We may want to just continue to do that route?

**Comment by katejeffreys** [comment]
@arthurevans What's the status of this? It's the oldest issue in our repo :)

**Comment by arthurevans** [comment]
What's old is new again! We still do runtime highlighting on the home page (and the API docs, but that's a separate issue). We have another open issue for the front-page highlighting (which is broken): https://github.com/Polymer/docs/issues/2129

Closing this one, since it refers to an old system we don't use anymore.
