### ISSUE TITLE
 Establish conventions for documenting allowed child elements

### ISSUE THREAD

**Issue by addyosmani** [Polymer/docs#317]
Right now, we have conventions in place for documenting an element's public properties but it's been mentioned that real-world elements may need to also include child elements that could be composed and distributed into their parents.

Our current state is that docs of what child elements a component takes is somewhat implicit in `<content select="<selector>">`. This requires looking through the source to understand the valid content selectors that can be included. (We also have another issue that many of our existing elements don't take child elements, so examples of how to handle this problem are somewhat scarce).

Could we investigate setting up conventions for how child elements should be documented? It appears the content model is one of the only things our current API docs doesn't cover as well as it could.

cc @sjmiles

**Comment by arthurevans** [comment]
This issue was moved to Polymer/hydrolysis#218
