### ISSUE TITLE
Improve docs on global variables, review best practices

### ISSUE THREAD

**Issue by addyosmani** [Polymer/docs#334]
Carrying on from #320:

"`<app-globals>` could wrap the properties in a "globals" object and published it. That would allow you to write: `<app-globals id="globals" globals="{{globals}}"></app-globals>` and not have to do the business in `ready()`" from @ebidel

**Comment by katejeffreys** [comment]
@addyosmani  Is this still a thing? Can the issue be closed?

**Comment by katejeffreys** [comment]
Closing this, as part of my aim to gradually reduce the open issues to a manageable number such that the open issues are meaningful to us. If this is the wrong thing to do, please re-open.
