### ISSUE TITLE
Best practices section?

### ISSUE THREAD

**Issue by robdodson** [Polymer/docs#339]
Would it make sense to have a best practices section on the site? We could nest topics underneath it such as: Bower/sharing, styling, accessibility, lifecycle callbacks, etc.

I could take a stab at drafting this up if there's interest.

**Comment by RichOren** [comment]
Hello guys - I am a huge fan of Polymer and come from the Flex Community. I have always found this type of website extremely helpful. http://blog.flexexamples.com/2010/12/18/setting-the-icon-placement-on-a-spark-button-control-in-flex-hero/#more-3471

It basically focused on solving small real world problems and provides solutions for them with code examples and downloadable project that one could integrate alone or into a current project. 
It needs to be searchable and easy to locate the information one might need and would take a dedicated evangelist to keep the content fresh and current. 

Thank you for all your hard work.

**Comment by robdodson** [comment]
Thanks @RichOren. We've been kicking around the idea of having a dedicated place for tutorials and samples so I'll factor your comment in as a +1 for that approach :+1:

**Comment by arthurevans** [comment]
I think we should avoid a best practices section per se, and file these under specific topics (performance, a11y, etc.).

Recommend closing this out. 

+1 for concrete samples, though.

**Comment by robdodson** [comment]
yeah i think we can close this
