### ISSUE TITLE
Glossary for polymer / webcomponents

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#360]
It might be handy to define common terms we use an have pointers to the relevant docs.
- light dom / shadow dom
- custom element
- changed watcher
- automatic node findin
- microtask
- ...

**Comment by ebidel** [comment]
@arthurevans is working on this for 0.8

**Comment by arthurevans** [comment]
This one has been pushed to the back burner so many times that it still isn't done. Going to put it down as an objective for the quarter.

**Comment by katejeffreys** [comment]
I was working on a glossary to help myself learn when I started on the team. I've shared the doc with you all. If it's still useful I can complete it and publish it on the docs site.

**Comment by katejeffreys** [comment]
https://www.polymer-project.org/2.0/docs/glossary

Closing this issue since the glossary at least now exists. I will keep working on it though. Feel free to add/suggest changes.
