### ISSUE TITLE
Make heading anchor links a custom element

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#364]
Rather than app.js handling it, it would be nice if this was wrapped up in a custom element:

    # Heading
    {:is="x-link"}

http://stackoverflow.com/questions/23088517/is-it-possible-to-modify-existing-elements/23092037#23092037

**Comment by arthurevans** [comment]
I have a feeling we're not going to do this at this point ...

**Comment by ebidel** [comment]
Nope :)
