### ISSUE TITLE
Extending other elements doc

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#394]
We have http://www.polymer-project.org/docs/polymer/polymer.html#extending-other-elements, but it should probably be a separate page/article under core.

Examples of how to extend and use native elements (e.g. `<button is="super-button">` type extensions) and extend others` custom elements using Polymer.

This is a good place to talk about `<shadow>` (see https://github.com/Polymer/docs/issues/184)

`<google-maps-with-markers>` may be a good example: http://jsbin.com/tekolewi/9/edit

**Comment by arthurevans** [comment]
No longer relevant under 1.x. Will open a new ticket when we get an extension mechanism in 1.x.
