### ISSUE TITLE
Distributing Components article should include best practices for versioning releases and dependencies

### ISSUE THREAD

**Issue by jyasskin** [Polymer/docs#399]
http://www.polymer-project.org/articles/distributing-components-with-bower.html talks about including the `version: '0.0.1'` tag in the master `bower.json` file and depending on the generic `"Polymer/polymer"` version. However, Polymer itself has no `version` field in its [master `bower.json`](https://github.com/Polymer/polymer/blob/master/bower.json), adds the `version` in the [release tag](https://github.com/Polymer/polymer/blob/0.2.3/bower.json), and updates the dependency versions to be exact (`"Polymer/platform#0.2.3"`) in the release.

For new component authors, it'd be nice to suggest a best practice in this article.

**Comment by arthurevans** [comment]
It looks like there are maybe 3 or 4 lines in this article that need to be updated (like, there's a reference to core-something, webcomponents-lite.js and the aforementioned versioning for Polymer). Can we just update this puppy?

**Comment by katejeffreys** [comment]
http://www.polymer-project.org/articles/distributing-components-with-bower.html

This link gives a 404 and a site search for "distributing components with bower" does not return a similarly titled article.

Can this issue be closed, or is there an article floating around somewhere that needs updating? @arthurevans @robdodson

**Comment by arthurevans** [comment]
That was basically replaced by https://www.polymer-project.org/1.0/docs/tools/reusable-elements

That doesn't actually mention dependency versioning, though... We should probably have best practices at some point. Low priority compared to ongoing 2.0 work, though.

**Comment by katejeffreys** [comment]
@arthurevans I have created some examples. Could you comment on this pls? 

1. Is the info correct?
2. Anything else to mention?
3. Where to put it?

## Dependency versioning best practices

When you're ready to publish your element, you should define its dependencies and their required versions in `bower.json` so users can install and use your element.

Best practice is to define a version or range of versions of dependencies. Don't rely on generic versions of your element's dependencies:

  ```
    "dependencies": {
      //don't do this
      "polymer": "Polymer/polymer,
      "paper-input": "PolymerElements/paper-input,
      ...
    },
    
  ```

Instead, append version ranges to the end, as follows:
  
2.0 example (modified from https://github.com/PolymerElements/paper-slider/blob/2.0-preview/bower.json)
  
  ```
    "dependencies": {
      "polymer": "Polymer/polymer#^2.0.0",
      "paper-input": "PolymerElements/paper-input#2.0",
      "paper-progress": "PolymerElements/paper-progress#2.0",
      "iron-flex-layout": "PolymerElements/iron-flex-layout#2.0",
      "paper-styles": "PolymerElements/paper-styles#2.0",
      "iron-behaviors": "PolymerElements/iron-behaviors#2.0",
      "paper-behaviors": "PolymerElements/paper-behaviors#2.0",
      "iron-a11y-keys-behavior": "PolymerElements/iron-a11y-keys-behavior#2.0",
      "iron-form-element-behavior": "PolymerElements/iron-form-element-behavior#2.0"
    },

Hybrid example (taken from https://github.com/PolymerElements/paper-slider/blob/master/bower.json)
  
  ```
    "dependencies": {
      "polymer": "Polymer/polymer#1.9 - 2",
      "paper-input": "PolymerElements/paper-input#1 - 2",
      "paper-progress": "PolymerElements/paper-progress#1 - 2",
      "iron-flex-layout": "PolymerElements/iron-flex-layout#1 - 2",
      "paper-styles": "PolymerElements/paper-styles#1 - 2",
      "iron-behaviors": "PolymerElements/iron-behaviors#1 - 2",
      "paper-behaviors": "PolymerElements/paper-behaviors#1 - 2",
      "iron-a11y-keys-behavior": "PolymerElements/iron-a11y-keys-behavior#1 - 2",
      "iron-form-element-behavior": "PolymerElements/iron-form-element-behavior#1 - 2"
    },
  
1.0 example (taken from https://github.com/PolymerElements/paper-slider/blob/1.x/bower.json)

  ```
    "dependencies": {
      "polymer": "Polymer/polymer#^1.1.0",
      "paper-input": "PolymerElements/paper-input#^1.0.0",
      "paper-progress": "PolymerElements/paper-progress#^1.0.0",
      "iron-flex-layout": "PolymerElements/iron-flex-layout#^1.0.0",
      "paper-styles": "PolymerElements/paper-styles#^1.0.0",
      "iron-behaviors": "PolymerElements/iron-behaviors#^1.0.0",
      "paper-behaviors": "PolymerElements/paper-behaviors#^1.0.0",
      "iron-a11y-keys-behavior": "PolymerElements/iron-a11y-keys-behavior#^1.0.0",
      "iron-form-element-behavior": "PolymerElements/iron-form-element-behavior#^1.0.0"
    },
  ```

**Comment by katejeffreys** [comment]
This is our oldest issue! It would be nice to close it out. What do you think @arthurevans ?

**Comment by katejeffreys** [comment]
To help with prioritization and manage workload, I will close this issue with no docs changes in 7 days. To prevent that from happening, please comment within 7 days. Thanks!
