### ISSUE TITLE
Article: elements getting data from external data sources

### ISSUE THREAD

**Issue by cosmicdreams** [Polymer/docs#400]
It would be great if you made an article that demonstrates how easy it is to use Polymer with external datasources.  Walk through how, by using datasources that expose web services, you can create a polymer-ajax element then use the data retrieved by that element to drive the generation of markup with polymer-elements.

I've started doing this myself using Drupal 8's RESTful API and creating elements to represent the retrieved data.  Drupal provides many common elements like a post (or to use a Drupal term, node) or a block.  I've been able to create a drupal-node and drupal-block elements and represent the default markup that comes from those elements.

**Comment by arthurevans** [comment]
@ebidel any interest in doing this? Seems like it might be more suitable for a codelab (hmm... maybe it already _is_ a codelab)?

**Comment by ebidel** [comment]
I think we already have examples like this in the docs. Mine as well close
