### ISSUE TITLE
Examples on how to filter & sort a model

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#435]
A common thing to do is create a sortable view (table). chromestatus for example, does filtering on the data model. We should explain that to people.

Basic idea is to have an array of truth (e.g. `list`), and create a `filteredList` "view" from it:

    <template repeat="{{item, i in filteredList}}">

    this.filteredListed = this.list.filter(function(item, i) {
      return item.category == 'special';
    });

cc @rafaelw @arthurevans for the most optimized approach.

**Comment by arthurevans** [comment]
Closing as obsolete. Filtering & sorting in 1.0 uses a different (documented) system:

https://www.polymer-project.org/1.0/docs/devguide/templates.html#filtering-and-sorting-lists
