### ISSUE TITLE
Article about inheritance and composition in Polymer

### ISSUE THREAD

**Issue by 0x-r4bbit** [Polymer/docs#443]
Hey there!

So as a few of you obviously noted, I posted some questions at StackOverflow about extending elements, inheritance and composition in Polymer.
- http://stackoverflow.com/questions/24157576/how-to-extend-multiple-elements-with-polymer/
- http://stackoverflow.com/questions/24180622/is-it-possible-to-share-mixins-across-web-components-and-imports-in-polymer

I plan to write a detailed blog post about extending elements, inheritance and composition in Polymer (things like, what use cases exist, how to handle them, what's possible, what's not etc.). But before I start publishing such article in my personal blog, I wanted to ask if you guys were interested in a contribution to Polymer's "Articles" section on http://www.polymer-project.org/articles/.

I would then send a PR and add an article for Polymer's website. In case you're not interested I would just write it for my blog.

What do you think? @ebidel @sjmiles

**Comment by 01es** [comment]
Does anybody know is there any hope for element inheritance in Polymer 1.x of the same kind as in Polymer 0.5?
