### ISSUE TITLE
Compatibility with binding to attributes

### ISSUE THREAD

**Issue by prtksxna** [Polymer/docs#472]
In the compatibility note about [binding to attributes](http://www.polymer-project.org/docs/polymer/databinding-compat.html#binding-to-attributes) its mentioned that certain attributes like `src`, `style`, `href` etc. should be prefixed with an `_`. Is that list exhaustive? Should all attributes be prefixed? Is there a larger but exhaustive list of such attributes?

**Comment by katejeffreys** [comment]
@arthurevans @robdodson Is this issue still relevant?

**Comment by robdodson** [comment]
@sorvell or @kevinpschaaf ?

**Comment by kevinpschaaf** [comment]
No can close, that was 0.5-specific.
