### ISSUE TITLE
Document this.shadowRoot

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#477]
We don't have this anywhere on the site. Where node finding is not enough, people ask how to query nodes in the element's shadow dom. 

    this.shadowRoot.querySelectorAll('.myClass')

This is also how you get to nodes that are dynamically stamped by data binding. Related: https://github.com/Polymer/docs/issues/460

Should be somewhere in http://www.polymer-project.org/docs/polymer/polymer.html.

**Comment by gertcuykens** [comment]
I am been playing around with '?dom=shadow' and to my surprise it breaks my site on this line when it loads `this.$.list.items.indexOf(this.$.list.selectedItem);` Do I need to worry about when `shady` becomes `shadow` again, hell is going to break lose because of `shadowRoot`?

**Comment by arthurevans** [comment]
@gertcuykens I'm not sure what you're seeing there without more code, but I don't think it has anything to do with `this.shadowRoot`.

Closing this as an 0.5 issue. 1.0 equivalent is documented here: https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#work-with-local-dom

**Comment by gertcuykens** [comment]
quick shot http://gcl-12.appspot.com/?dom=shadow :) i wil upload a cleaner version in a second because there are multiple thing wrong with that side but still you wil see a difference between shady and shadow

**Comment by gertcuykens** [comment]
http://gcl-12.appspot.com/?dom=shadow
http://gcl-12.appspot.com/

**Comment by mgiuffrida** [comment]
@sjmiles `this.shadowRoot` references the root hosted by `this`. How can that be different when `this` is a "sub-class" (but still the same object)?

**Comment by arthurevans** [comment]
@mgiuffrida That comment references an earlier, deprecated feature of the shadow DOM spec where an element could have multiple shadow roots. If you have a `bar-element` that extends `foo-element`, `bar-element` could declare its own shadow root, but also access the shadow root created by the superclass (the "older shadow root"). 

This feature is essentially dead; Polymer doesn't use it, and it may already have been removed from the browser as well. So working with Polymer 1 now—you can't. You can only  have one shadow root per element.

**Comment by mgiuffrida** [comment]
Oh. I got here while thinking about Polymer/polymer#3703 and didn't realize this was closed. Thanks!
