### ISSUE TITLE
Minor website polish issues

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/docs#557]
This is an umbrella issue for small polish issues found when doing a quick QA of the `perf` branch:

- [ ] Static images in carousel get distorted on narrow mobile screen (iPhone, Nexus)
- [ ] Tapping search icon on iOS does not focus the search input
- [ ] No way to return search input back to non-active state on iOS (focusing/de-focusing the input does nothing)
- [ ] Search icon floats in the center of the screen on iPad (should be left-aligned when search input is active?)
- [ ] On component-docs page, component-download-button and "demo" button sizes differ on polyfill (iOS & Firefox)
- [ ] On component-docs page, component-download-button and "demo" button look ugly when demo button wraps under it on polyfill (they touch with no margin, and left-alignment is different) - see on iOS
- [ ] code-explainer not tappable on iOS
- [ ] component-download-button dialog not tappable on iOS
- [ ] component-download-button not responsive on mobile (hangs off page)

**Comment by ebidel** [comment]
This issue has gone stale. Marking obsolete.
