### ISSUE TITLE
Example of monostate pattern for globals possibly in error

### ISSUE THREAD

**Issue by sjmiles** [Polymer/docs#565]
This section http://www.polymer-project.org/docs/polymer/polymer.html#global doesn't look quite right to me.

I described a change here http://stackoverflow.com/questions/25035587/polymer-global-variables-document-may-be-wrong/25045695#25045695

I hope I'm not missing something. I think this whole section deserves a review from the engineering team, there are a lot of tradeoffs and it would be good to make sure we agree on best practices.

**Comment by arthurevans** [comment]
Merged long ago. Closing.
