### ISSUE TITLE
Browser Compatibility Matrix is Missing 

### ISSUE THREAD

**Issue by jcrubino** [Polymer/docs#577]
Browser Compatibility Matrix is Missing 

and on a side note:  are we getting closer to a 1.0 api freeze?

**Comment by mohislm** [comment]
Is there a Browser Compatibility Matrix for 1.0?

**Comment by ebidel** [comment]
We don't have an up to date one, but it's more or less the same as 0.5:
https://www.polymer-project.org/0.5/resources/compatibility.html
