### ISSUE TITLE
An article on animations and core animation pages 

### ISSUE THREAD

**Issue by cleaverpj** [Polymer/docs#582]
I'd like to see an article giving more details on core animation pages as these look superb!

Specifically doing more advanced transitions and using it with conditional templating would be awesome.

**Comment by arthurevans** [comment]
the core-animation replacement, neon-animations have their own guide here: 

https://elements.polymer-project.org/guides/using-neon-animations

Happy to take enhancement requests on the existing guide, but I'm closing this out.
