### ISSUE TITLE
Doc injectBoundHTML() for .innerHTML'ing

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#607]
There's a new `injectBoundHTML` on all polymer elements that is useful for `.innerHTML`ing markup into a container element. It picks up the bindings

```
/**
 * Inject HTML which contains markup bound to this element into
 * a target element (replacing target element content).
 * @param String html to inject
 * @param Element target element
 */
injectBoundHTML: function(html, element)
```

Example and explanation: http://stackoverflow.com/a/25434691/274673

Demo: http://jsbin.com/kacokevitabe/1/edit

We should also update this FAQ entry: http://www.polymer-project.org/resources/faq.html#setinnerHTML

**Comment by RuedigerMoeller** [comment]
Is there any way to emulate this with 1.0 . Template customizing is a very common use case when rendering collections

**Comment by perdona** [comment]
Same issue here, need to render html dynamically (stored on db) on a dom-repeat and polymer keeps holding me back.. =\

**Comment by k7moorthi** [comment]
+1

**Comment by dioptre** [comment]
+1

**Comment by atulkshirsagar** [comment]
+1

**Comment by adaptivefrog** [comment]
+1
