### ISSUE TITLE
"Runtime config -> Debug flags" article out of date?

### ISSUE THREAD

**Issue by kamiltrebunia** [Polymer/docs#610]
Hey, I was just trying to setup dev runtime and failed. I tried to debug this problem for while, but I failed.

Basically I use 1st method described in the guide (I also tried 2nd method):
```
bower install Polymer/platform-dev Polymer/polymer-dev
Rewrite platform/platform.js to platform-dev/platform.js in index.html
Comment out line 12 and uncomment line 13 in polymer.html
```

And then I load my app with:
`http://localhost/?debug&log=bind,data,watch,events,ready`
(I also tried script tag attributes way)

And despite using few custom (simple) elements and imports I see nothing in the console.

Can someone else confirm it's a problem?

I actually have found a blog post describing the same problem here (it's few months old btw):
http://japhr.blogspot.com/2014/04/no-debugging-polymer.html

**Comment by ebidel** [comment]
This issue has gone stale. Marking obsolete.

**Comment by arthurevans** [comment]
Pulled this page the TOC quite a while back. It's had 87 hits in the last quarter, so I'd say we could safely remove it at this point.
