### ISSUE TITLE
Polymer site appears broken on Safari 8

### ISSUE THREAD

**Issue by tjsavage** [Polymer/docs#612]
http://www.polymer-project.org appears incorrect on Safari 8 both mobile 
![Mobile](http://cl.ly/image/3o0v3h1o2934/IMG_1742.PNG)
![Desktop](http://cl.ly/image/1J2t47180I3q/Screen%20Shot%202014-08-20%20at%2013.00.14.png)
and desktop.
Some elements (e.g. download&github buttons, examples sections) are completely missing. No errors appear in JavaScript error console

**Comment by Alkatrank** [comment]
Fixed? Where you can fix the problem with Safari? Even the official website of Polymer is not working on Safari, where you can fix it? -.-"

Polymer Homepage on Safari 20/05/2015 (almost one year later)
![safari pp](https://cloud.githubusercontent.com/assets/12527355/7723728/0e263908-feeb-11e4-8f8f-8acf1c411d66.JPG)

**Comment by ebidel** [comment]
@Alkatrank what version of safari are you on? I don't have it personally, but I'm told everything looks fine in 8.0.6

**Comment by arthurevans** [comment]
It's working fine for me on 7.1.6.

**Comment by arthurevans** [comment]
Could be an extension? Someone reported this issue last year using Norton Internet Security:

https://github.com/Polymer/polymer/issues/1048

**Comment by mlabarre** [comment]
Google works for ... Chrome. That's all. From Polymer version 1.0 all seems good in Chrome but in Firefow or Safari (on mac) it's the war ! Lol
