### ISSUE TITLE
Document edge cases for type inference with published properties

### ISSUE THREAD

**Issue by tjsavage** [Polymer/docs#614]
e.g. troublesome cases:
``` html
<x-foo bar="">
<x-foo bar="true">
<x-foo bar="false">
<x-foo bar="0">
...
```

**Comment by arthurevans** [comment]
This is an old 0.5 bug; stuff works a bit differently in 1.0 (no type hinting involved), and we have some coverage on the peculiarities of boolean properties & attributes:

https://www.polymer-project.org/1.0/docs/devguide/properties.html#configuring-boolean-properties

So closing this one out.
