### ISSUE TITLE
Right clicking on links performs navigation instead of showing context menu.

### ISSUE THREAD

**Issue by spikewilliams** [Polymer/docs#626]
This is similar to the issue in https://github.com/Polymer/docs/issues/398 except that was resolved for cmd-clicking on a Mac. On Windows, this is similar to a right-click, which would ordinarily reveal a context menu, with "open in new tab" as one of the options. This happens in both Chrome and Firefox, but it works correctly in IE 11.

**Comment by arthurevans** [comment]
I can't reproduce in Chrome on Windows. Is this still reproducible?

I tested on a VM, possibly that's glossing over the problem.

**Comment by spikewilliams** [comment]
I can't reproduce this anymore either. The problem seems to have gone away.

**Comment by arthurevans** [comment]
Awesome. Thanks for following up!
