### ISSUE TITLE
Add a badge to homepage that calls out "Developer Preview" 

### ISSUE THREAD

**Issue by addyosmani** [Polymer/docs#648]
Some feedback I've heard from a few developers:

Today, the site doesn't make it too clear about Polymer's state of readiness (e.g alpha, beta, preview?). This gives makes it unclear to developers whether they should consider using Polymer for production apps. We also don't currently distinguish between the readiness state of Polymer vs Paper and Core elements, which we could make more clear too.

Per a chat with Taylor, we should add a badge to the homescreen that calls out "Developer Preview" and links to the FAQ. We could also add a line to the Elements description indicating that they'll be frequently updated.

**Comment by ebidel** [comment]
Had this for a while
