### ISSUE TITLE
Include file-size of Polymer more clearly on the site

### ISSUE THREAD

**Issue by addyosmani** [Polymer/docs#649]
We don't indicate the cost of buying in to using us very clearly on the site today. What's the file-size of Polymer + Platform? Being upfront about this would allow devs to make informed decisions about ability to use it.

Taylor suggested we could include more information about this on the Get Polymer page.

**Comment by katejeffreys** [comment]
To help with prioritization and manage workload, I will close this issue with no docs changes in 7 days. To prevent that from happening, please comment within 7 days. Thanks!
