### ISSUE TITLE
Documenting elements guide

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#677]
Discusses `core-doc-viewer`, its features, setup, usage, supported `@pragmas`, deep links, etc.

Addy's got a bit on it http://www.polymer-project.org/docs/start/reusableelements.html#publishing-a-demo-and-landing-page-for-your-element, but we need more.

**Comment by arthurevans** [comment]
This is an objective for Q4. Not a top-priority one, though, so it could slip.

**Comment by arthurevans** [comment]
Fixed in https://github.com/Polymer/docs/pull/1500.
