### ISSUE TITLE
Highlight start->finish developer workflow

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#678]
We should be able to give a clear lit path by end of quarter:
- Creating sharable elements
  - seed-element - http://www.polymer-project.org/docs/start/reusableelements.html 
  - several app scaffolds/templates (in the works)
- Document elements - https://github.com/Polymer/docs/issues/677
- [Debugging](https://github.com/Polymer/docs/pull/663)
- Testing - https://github.com/Polymer/docs/issues/164
- Misc
  - Accessibility - http://www.polymer-project.org/articles/accessible-web-components.html
  - [Build tools](http://www.polymer-project.org/articles/concatenating-web-components.html) & [optimizations](https://github.com/Polymer/docs/issues/339)
- [Distributing elements](http://www.polymer-project.org/articles/distributing-components-with-bower.html)

cc @arthurevans @robdodson @addyosmani

**Comment by katejeffreys** [comment]
To help with prioritization and manage workload, I will close this issue with no docs changes in 7 days. To prevent that from happening, please comment within 7 days. Thanks!
