### ISSUE TITLE
Docs around Iteration Workflow

### ISSUE THREAD

**Issue by addyosmani** [Polymer/docs#680]
There's a missing piece to our current story we'll be in a better position to talk about in Q1: Iteration workflow. 

E.g I want to build an app with Polymer with a workflow that does...
- Linting of my script sources, whether they exist in HTML Imports or otherwise
- Live-reload of elements as I author them
- Testing setup for my app _and_ my elements (web-component-tester does this well on a per-element basis atm. Interesting to see our testing advice cover working with apps. E.g should devs write tests for each element separately? Should they write them for their whole app? Does this change at all?)
- Build time optimization beyond Vulcanize. We currently rely heavily on it for flattening imports, but how should it hook into an app that requires image, icon and asset optimization?
- How should you setup your build process to work well with preprocessors and transpilers / anything that assumes script/styles are external? What does the optimal source > production workflow look like for Polymer apps?
- Maybe I care about element scaffolding. Where does Yeoman place into that?

Some of this will be made easier once we've implemented Web App Starter Kit, but I'd like to see stuff around this covered next year.

Current solution: https://github.com/yeoman/generator-polymer

**Comment by arthurevans** [comment]
Ping. I think this sounds more like an article than a doc. Is this something you're still interested in?
