### ISSUE TITLE
Give every element one or more tag names.

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#695]
I am having trouble finding the element I need, let say I want a button. These are general buttons scattered throughout the elements list.

- core-icon-button
- paper-button
- paper-icon-button
- paper-toggle-button
- paper-fab

Can you make a tag list please so when more elements are added you have some structure to group them together.

Here is a list of tag examples I think are useful

- button tag
- form tag
- animation tag
- icon tag
- layout tag
- xhr tag
- beta tag
- core tag
- paper tag
- ...

Note that one element can have more than one tag.

**Comment by arthurevans** [comment]
Closing 0.5 bugs.
