### ISSUE TITLE
Middle mouse click lacking, to open on new tab, e.g. Edit on plunker button

### ISSUE THREAD

**Issue by fancellu** [Polymer/docs#697]
https://www.polymer-project.org/docs/start/creatingelements.html

I see an "EDIT ON PLUNKER" button. 

I'd like to middle mouse click it to open on a new tab, so I don't lose my place in the docs. No can do. 

Just makes a tap, goes nowhere. doesn't open in new tab, shows 4 way mouse cursor.

**Comment by ScalaWilliam** [comment]
Imagine a newcomer:
"All works nicely, what's this, no support for middle mouse click?"

**Comment by robdodson** [comment]
I realize the problem, however the solution will probably require us to redo all of our interactive examples since it would mean dropping form submissions. IOW, this is a non-trivial fix but it's on our radar.

**Comment by arthurevans** [comment]
Note that the general case (navigation links, etc. -- everything except the Plunker button) is a different bug, #509, and I've just submitted a PR for it: https://github.com/Polymer/docs/pull/890.

**Comment by fancellu** [comment]
Hurrah. Thanks.

**Comment by arthurevans** [comment]
Closing this as I don't think we'll  update the plunker-button element at this point.
