### ISSUE TITLE
Inconsistent download steps

### ISSUE THREAD

**Issue by bibhas2** [Polymer/docs#727]
By clicking on **Get Polymer** button on home page takes you to https://www.polymer-project.org/docs/start/getting-the-code.html where there is a link to download a starter project. The same happens when you click **Get the Code** on the left hand side menu.

However, in the **Using elements** page (https://www.polymer-project.org/docs/start/usingelements.html), there are buttons to download Polymer core and Paper elements. They give a choice to download the code as ZIP file, using Bower and from Github.

These are two inconsistent steps. If I had to choose, the downloading of ZIP or Bower approach should be highlighted as the primary approach. The starter project seems to contain only a subset of the elements and also that code is not kept up to date. At the time of this writing, the starter project is using **platform.js** where as the downloadable ZIP file has switched to using **webcomponents.js**.

**Comment by arthurevans** [comment]
This was fixed in 0.5, and there's a separate bug open to update the structure of GTC in 1.0 (which is a little different to start with). So: closing.
