### ISSUE TITLE
IE10 - Side Nav Menu links do not update the url hash

### ISSUE THREAD

**Issue by sesteva** [Polymer/docs#739]
If you are looking at core-elements, such as  https://www.polymer-project.org/docs/elements/core-elements.html#core-ajax , and then you click on core-xhr, the hash does not update. Therefore, the content page is not updated with the proper element component page.

**Comment by katejeffreys** [comment]
Thanks for raising this issue. It looks like it wasn't addressed and is now obsolete, so I apologize. Closing it now.
