### ISSUE TITLE
Back button navigation somtimes broken on polymer-project website

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#741]
_From @steren on November 11, 2014 12:36_

How to reproduce: 
- go to https://www.polymer-project.org/
- click "Get Polymer" (it goes to https://www.polymer-project.org/docs/start/getting-the-code.html)
- hit the back button

What is expected:
- browser goes back to main page (the previous page)
  What happens:
- stays on the same page, I have to click twice to go to main page

Another occurrence of serious back button breakage:
- go to https://www.polymer-project.org/
- click Topeka
- hit back button

What happens:
- stays on the same page, impossible to go back to previous page, back button is stuck

_Copied from original issue: Polymer/polymer#907_

**Comment by katejeffreys** [comment]
To help with prioritization and manage workload, I will close this issue with no docs changes in 7 days. To prevent that from happening, please comment within 7 days. Thanks!
