### ISSUE TITLE
Article Ideas - Using Chrome Dev Editor (CDE) workflow, best practices, offline, Cordova, etc.

### ISSUE THREAD

**Issue by landmaxcanada** [Polymer/docs#744]
Hi, I just started using CDE (Developer Preview) and I really like it!  It comes with "New Project" - Javascript Chrome App (using Polymer paper elements) as a starting point. It would be nice to have articles that go from this starting template to various finished Cordova Chrome Phone Apps. I am particularly  interested in the "Webview" Chrome App component and it interacting with the main app. 

Another issues unique to Chrome Apps is "Offline First", so it would be useful explain all the best ways to save data to the File System. For offline maps, it appears that there is no way to use Google Maps (my favorite) so I am looking at Leaflet and XHR requests to get the map image tiles, then I need a way to save them on the local file system.

**Comment by ebidel** [comment]
Unfortunately, covering CDE is out of scope for us.
