### ISSUE TITLE
Printing pages from polymer-project.org has large left nav bar/ margin...

### ISSUE THREAD

**Issue by marycampione** [Polymer/docs#746]
When printing, the side nav bar shows up taking up almost half the width of the page. Even when the page is narrowed and the nav bar disappears, the margin is blank but just as wide. So printing anything is impractical.
mem

**Comment by ebidel** [comment]
This issue has gone stale. Marking obsolete.

**Comment by ebidel** [comment]
This issue has gone stale. Marking obsolete.
