### ISSUE TITLE
Should have a mapping from Material Design components to the paper elements that implement them

### ISSUE THREAD

**Issue by jyasskin** [Polymer/docs#747]
For each component in http://www.google.com/design/spec/components/, it'd be nice to have a description of how to get the right effect using `<paper-*>` elements, even if for many of the components that's just "start with this element and add lots of DOM" for now.

**Comment by katejeffreys** [comment]
To help with prioritization and manage workload, I will close this issue with no docs changes in 7 days. To prevent that from happening, please comment within 7 days. Thanks!
