### ISSUE TITLE
Search box should close on mobile when unfocused

### ISSUE THREAD

**Issue by tjsavage** [Polymer/docs#766]
Repro:
0. Clear cache
1. Navigate to homepage
2. Tap search icon
3. Exit search box (close keyboard)
Expected: Search box closes to re-reveal the hamburger menu
Saw: Search bar stays open and obscured nav

**Comment by arthurvr** [comment]
Shouldn't this issue be closed? This was fixed in 9c1e028.

**Comment by robdodson** [comment]
Just tried on my phone. Seems fixed to me
