### ISSUE TITLE
Document space-separated list of attributes as key in an observe block

### ISSUE THREAD

**Issue by jeffposnick** [Polymer/docs#768]
I noticed that the [docs for the `observe` block](https://www.polymer-project.org/docs/polymer/polymer.html#observeblock) doesn't mention that you can provide a space-separated list of attribute names that all share the same data changed callback.

This [appears to be supported](http://jsbin.com/yonoci/1/edit?html,console,output), so unless there's a reason we don't want people to use that syntax, it seems like an oversight.

(Apologies if it's documented but I'm missing it somehow!)

**Comment by ebidel** [comment]
This has been documented in 0.8. Marking this as obsolete for 0.5.
