### ISSUE TITLE
[vulcanize] doesn't do what is claimed

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#773]
https://www.polymer-project.org/articles/concatenating-web-components.html

Quote :

"In the Polymer world, Vulcanize is the name given to a build tool that lets you concatenate a set of elements and their HTML imported dependencies into a single file"

It simply does not do this. For example, if I have a directory full of polymer elements, I want to concatenate them into a single file, but vulcanize (afaict) cannot do this.

Ideally, I'd want to simply specify a polymer 'element' file and vulcanize would produce a copy of it with all its imports already in the file, and all their imports too, and so on. This way, I can distribute my element in an optimised and self-contained way.

The current behaviour, when specifying a my-element.html file, seems to be to enclose the file with html, etc tags and pretend to produce a web page from it - that doesn't seem to be so useful to me, though I suppose it has its place as a web page optimisation step.

Please consider changing the documentation to state what it does more specifically/accurately - ie something like :

"...lets you concatenate a set of elements used in an html document...and their..."

Of course, much more preferable from my point of view is to have it work on element files themselves, since my 'index.html' is auto-generated such that I can't use vulcanize on it - I imagine it would be the same for any extension that uses a content script to inject polymer elements into a web page.

**Comment by katejeffreys** [comment]
To help with prioritization and manage workload, I will close this issue with no docs changes in 7 days. To prevent that from happening, please comment within 7 days. Thanks!
