### ISSUE TITLE
[vulcanize] please add 

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#774]
<https://www.polymer-project.org/articles/concatenating-web-components.html>

Please add advice for people writing packaged apps and extensions. I'm looking for something along the lines of :

<https://www.polymer-project.org/articles/concatenating-web-components.html#is-concatenation-a-good-idea>

I suppose the author might consider that to be enough, in which case never mind. It'd be nice to get some more guidance specific to our use-case, or at least a mention, so we know it applies to us too.

Most of the page assumes there are network downloads, but that's not always true.

**Comment by arthurevans** [comment]
Going through the backlog. The updated version of the vulcanize doc mentions Chrome apps here:

https://www.polymer-project.org/1.0/tools/optimize-for-production.html#content-security-policy

However, it might be nice to add a quick paragraph about CSP right at the beginning to introduce this. Like maybe add a paragraph immediately after the first intro paragraph:

"The Polymer build tools can also be used to transform your code to run in an environment that enforces content security policy (CSP), including Chrome Apps and Extensions."

@robdodson WDYT?
