### ISSUE TITLE
"Polymer in 10 Minutes" - webcomponents.min.js and core-ajax don't exist in the recommended Download

### ISSUE THREAD

**Issue by actcontpr** [Polymer/docs#776]
bower_components/webcomponentsjs/webcomponents.min.js and the core-ajax directory are missing from the Zip Download of Polymer, thus the Tutorial isn't correct in this regard. Either one needs correcting/fixing.

**Comment by arthurevans** [comment]
The "in 10 minutes" page now shows how to install core-ajax with bower.

It also provides plunker buttons as an alternative to installing anything. 

In the future, the "in 10 minutes" page should omit the installs entirely. The required setup (downloading stuff, setting up a web server) eats up too much time for the light-weight intro this is supposed to be.
