### ISSUE TITLE
Article: Using Sass with Custom Elements

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#78]
I've been using Compass on a few different Polymer projects for a while now. In fact, I've been meaning to write an article on the topic.

My approach has been to create an _elements.scss file that elements can reuse in their own stylesheets.

The two gotchas I've ran in to:
1. The sass compiler barfs on ^ and ^^ selectors. Bug filed.
2. Be careful if you're compiling such that comments are removed. Any rules with `/* @poyfill */` will be stripped out. I've mostly avoided this by include these advanced rules in an inline `<style>` in the element.

https://groups.google.com/forum/#!msg/polymer-dev/gNlsZDltpUY/QZEYYsrdOvwJ

**Comment by arthurevans** [comment]
Ping @robdodson @ebidel  is this still relevant or can we close it out?

**Comment by ebidel** [comment]
We can close
