### ISSUE TITLE
Minor scroll perf tweaks

### ISSUE THREAD

**Issue by paullewis** [Polymer/docs#791]
Sup!

I noticed there are a few small perf issues in Chrome on the Polymer docs site, e.g. [the app tutorial](https://www.polymer-project.org/docs/start/tutorial/step-4.html):

1. Chrome isn't promoting the header and sidebar elements to their own layer, so they're being repainted on each scroll. We could add `will-change: transform` or `-webkit-backface-visibility: hidden` here to create a new compositor layer and that gets those sorted. That should help Firefox and Safari visitors in particular.
2. The header seems to go a bit bonkers when it switches from full height to collapsed.

For 2, I see a big block, like 20ms of Recalc Style agains 404 elements, and I'm not sure if it's a Chrome bug or not. (Feels like it might be given that tree size.) I've got it down to this code:

```javascript
if (this.smallBannerSizeReached) {
  this.classList.add("scrolling");
  this.header && this.header.classList.add("shrink")
} else {
  this.classList.remove("scrolling");
  this.header && this.header.classList.remove("shrink");
  if (this.header && this.header.offsetTop - currentScrollY <= 0) {
    this.header.classList.add("shrink")
  }
}
```

That may not map perfectly, but it's basically the scroll handler for `scroll-area`. I can't tell what the exact issue is, but I have a feeling that the `scrolling` class is quite far-reaching in terms of tree invalidation, and wonder if we can target whatever its effects are more closely. Mind you, it could be `shrink`... hard to say.

If I get a moment I'll try and dig in and get a PR done, but I wanted to file it in any case.

**Comment by arthurevans** [comment]
I'm going to go out on a limb and say that we're not going to fix this in the existing site, and the new site will be using a different set of elements, so closing as Will Not Fix.
