### ISSUE TITLE
Categorization of elements

### ISSUE THREAD

**Issue by joepie91** [Polymer/docs#812]
Currently, the documentation items under "Elements" are sorted kind-of-alphabetically, which makes the list look very awkward to navigate through, right off the bat. As there's also (apparently) no page that has a demo of all the available elements, the Polymer element collection looks very daunting and it's hard to get an idea of exactly what Polymer offers.

I'd suggest categorizing the elements rather than just sorting them alphabetically, similar to how eg. Visual Studio categorizes them in the form designer. In the case of Polymer, I'd be thinking of categories like "Form Inputs", "AJAX", "Animation", "Layout", and so on. This would make it obvious where to look to get an idea of what Polymer has to offer, and makes it easier to navigate for developers actually using Polymer.

**Comment by katejeffreys** [comment]
Resolved in webcomponents.org
