### ISSUE TITLE
Broken link in paper-radio-group documentation

### ISSUE THREAD

**Issue by erickoledadevrel** [Polymer/docs#814]
https://www.polymer-project.org/docs/elements/paper-elements.html#paper-radio-group

This page cross-links to the paper-radio-button documentation:

    <a href="../paper-radio-button/">paper-radio-button</a>

However that URL returns a 404.

**Comment by ebidel** [comment]
This is fixed in master of paper-radio-group, but we haven't had an elements release in a while.

https://github.com/Polymer/paper-radio-group/blob/master/paper-radio-group.html#L24
