### ISSUE TITLE
paper-autogrow-textarea documentation example not working

### ISSUE THREAD

**Issue by arielkroszynski** [Polymer/docs#817]
the example here:
https://www.polymer-project.org/docs/elements/paper-elements.html#paper-autogrow-textarea
shows the following snippet:

```
/* using example HTML above */
t1.value = 'some\ntext';
a1.update();
```

however this doesn't work. it should be:

```
/* using example HTML above */
t1.value = 'some\ntext';
a1.update(t1); // <== you need to pass the decorated element here.
```

Is this working as intended?

**Comment by katejeffreys** [comment]
Closing, obsolete.
