### ISSUE TITLE
Offer to write article

### ISSUE THREAD

**Issue by Will-in-BC** [Polymer/docs#819]
Eric,

I wanted to learn Polymer so I built a sample application to create, retrieve, update and delete records from a data store. I noticed that there are many questions about how to use Polymer to build forms applications so I wrote my sample to illustrate how I would address such an application in a transaction processing environment.

You can find a hosted version of the application at http://www.aureusarcus.com/polymerqa004/aaa-polymercrud-application/aaa-polymercrud-application.html

You can also bower instal aaa-polymercrud-application.

I'd write the article from the perspective of someone new to Polymer and look at how I explored its capabilities and decided how to break my application into components. I'd also highlight what I see as some of Polymers most powerful capabilities for producing reusable components.

I am happy to write to your editorial standards and happy to take criticism.   

If you are interested you can contact me at williamr.hopkins@gmail.com

**Comment by ebidel** [comment]
Thanks for the offer to write article. Right now, we're focusing on 0.8 and things may change at bit.

I think a post like this would be better lived on a personal blog. It's true that a lot of people want to know how to use forms + polymer, but there's pretty solid info on StackOverflow these days.
