### ISSUE TITLE
Hot-linking to www.polymer-project.org/webcomponents.js doesn't work

### ISSUE THREAD

**Issue by jeffposnick** [Polymer/docs#823]
Hot-linking to www.polymer-project.org/webcomponents.js doesn't work right now. Hot-linking to the minified version, www.polymer-project.org/webcomponents.min.js, does.

The [FAQ](https://www.polymer-project.org/resources/faq.html#is-the-code-hosted-on-a-cdn) currently tells people to use the minified version for testing, but prior to https://github.com/Polymer/docs/commit/7984e546f7c37a1deed1b0a67fe5a10dc8498367 it directed folks to the un-minified version, so there are probably folks out there still using that broken version.

You can see the breakage at http://jsbin.com/yatub/1/edit?html,console,output which leads to the following JS console errors. It seems like JS dependencies that are meant to be available under `www.polymer-project.org/src/` are missing.

    GET https://www.polymer-project.org/src/HTMLImports/HTMLImports.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/WebComponents/lang.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/WebComponents/bc.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/WebComponents/unresolved.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/WebComponents/shadowdom.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/WebComponents/dom.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/CustomElements/CustomElements.js 
    runner-3.23.10.min.js:1 Script error. (line 0)
    polymer.js:11519 Uncaught ReferenceError: HTMLImports is not defined
    runner-3.23.10.min.js:1 error Script error. (line 0)
    polymer.js:10244 Uncaught Element name could not be inferred.
    webcomponents.js:92 GET https://www.polymer-project.org/src/WebComponents/shadowdom.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/HTMLImports/HTMLImports.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/WebComponents/dom.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/WebComponents/unresolved.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/CustomElements/CustomElements.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/WebComponents/lang.js 
    webcomponents.js:92 GET https://www.polymer-project.org/src/WebComponents/bc.js 
    runner-3.23.10.min.js:1 error Script error. (line 0)
    polymer.js:11519 Uncaught ReferenceError: HTMLImports is not defined
    runner-3.23.10.min.js:1 error Script error. (line 0)
    polymer.js:10244 Uncaught Element name could not be inferred.

**Comment by ebidel** [comment]
Closing as this is old.  We're got the minified version up and folks should use that if they want to link.
