### ISSUE TITLE
Polymer in 10 minutes - horizontal scroll bar doesn't work in chrome

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#831]
_From @mattkrick on December 15, 2014 21:39_

For the last few examples, the horizontal scroll bar in chrome (39.0.2171.95) doesn't work when clicked or dragged, but a mouse wheel click can scroll the area. However, this works in IE.

_Copied from original issue: Polymer/polymer#1030_

**Comment by arthurevans** [comment]
Is this still an issue? I'm not sure how it's supposed  to work. 

If I select text and pull to the right, it scrolls. If I start scrolling (i.e., with the trackpad) the scrollbar shows up, at which point I can click and drag it. So it appears to be working here (Chrome 42, OS X).

If anyone is still seeing this, can they comment here and I'll reopen?
