### ISSUE TITLE
How do you cancel job1 completely before its timeout value occur?

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#847]
https://www.polymer-project.org/docs/polymer/polymer.html#job

```html
this.responseChanged = function() {
  this.job('job1', function() { // first arg is the name of the "job"
    this.fire('done');
  }, 500);
}
```

**Comment by ebidel** [comment]
This issue has gone stale. Marking as obsolete.

**Comment by gertcuykens** [comment]
I am happy the github issues are getting cleaned up. I know you all have things to do and I also know allot of them are invalid, but still every open issue is a frustrated user and every polymer team member should know that even it is not there fault.

**Comment by arthurevans** [comment]
Talked to core folks. I'm going to re-open and move this to Polymer/polymer as an 0.8 feature request.

**Comment by arthurevans** [comment]
This issue was moved to Polymer/polymer#1374
