### ISSUE TITLE
no 0.5.2 in changelog.html

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#849]
https://www.polymer-project.org/resources/changelog.html

We are at 0.5.2 right?

I would just link to https://github.com/Polymer/polymer/tags instead of making a seperate changelog.html

**Comment by ebidel** [comment]
We already link to the releases page from https://www.polymer-project.org/resources/changelog.html. I've heard people use the latter to know when there's a new version of Polymer.

**Comment by gertcuykens** [comment]
https://www.polymer-project.org/docs/start/getting-the-code.html <- 0.5.1 also

**Comment by ebidel** [comment]
This has gone stale. We've been updating since 0.5.1: https://www.polymer-project.org/resources/changelog.html
