### ISSUE TITLE
Missing e in function - Tutorial

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#875]
_From @voxic on January 20, 2015 11:50_

Hi 

Noticed that there is an error in the code in the tutorial instructions.

https://www.polymer-project.org/docs/start/tutorial/step-1.html

The last code box:
```javascript
<script>
  var tabs = document.querySelector('paper-tabs');
  tabs.addEventListener('core-select', function() {
    console.log("Selected: " + tabs.selected);
  });
</script>
</body>
```
Should be:
```javascript
<script>
    var tabs = document.querySelector('paper-tabs');
    tabs.addEventListener('core-select', function(e) {
      console.log("Selected: " + tabs.selected);
    });
</script>
</body>
```
/Emil

_Copied from original issue: Polymer/polymer#1110_

**Comment by ebidel** [comment]
This isn't critical because the event isn't being used in the callback. I'll leave to @arthurevans to decide if we should add it.

**Comment by ssorallen** [comment]
A linter like JSHint would warn that the `e` variable is declared but never used. Minifying with something like Uglify would remove the `e`. I lean toward leaving it out entirely, but either way works.

**Comment by voxic** [comment]
Well, if you look at the attached support file, witch should contain the "correct" solution, it has the ``` e ``` witch can be confusing if you are totally new to JavaScript.

ref: https://github.com/Polymer/polymer-tutorial/blob/master/step-1/index.html

/Emil

**Comment by arthurevans** [comment]
Hi Emil,

You're right, those two should match. In this case, I think the solution file is wrong -- the subsequent steps and the finished version all omit the e. Sorry for the confusion -- I'll fix that.

**Comment by arthurevans** [comment]
Updated the polymer-tutorial repo to match the docs. Thanks for the heads-up, @voxic!
