### ISSUE TITLE
Download instructions incorrect, doesn't match the .zip file contents

### ISSUE THREAD

**Issue by sethladd** [Polymer/docs#877]
Go to https://www.polymer-project.org/docs/elements/core-elements.html#core-header-panel

Click "Get core header panel"

![screen shot 2015-01-22 at 4 38 26 pm](https://cloud.githubusercontent.com/assets/5479/5867767/2449ec18-a255-11e4-934b-5b798f229a6e.png)

See this: `<link rel="import" href="components/core-header-panel/core-header-panel.html">`

Expected: the link to just work, with the correct URL.

Actual: net::ERR_FILE_NOT_FOUND, because the .zip actually contains `components/bower_components/core-header-panel`

**Comment by ebidel** [comment]
This issue was moved to Polymer/component-download-button#5
