### ISSUE TITLE
Article about https://github.com/kangax/html-minifier config for polymer

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#879]
The vulcanize tool does not minify the html output itself.

Can somebody make a article how to configure this html minifier for polymer?
https://github.com/kangax/html-minifier

Specifically:
- customAttrAssign
- customAttrSurround
- customAttrCollapse

Currently it does not work out of the box and need allot of extra regex specifications to handle polymer input, but I am not an expert so I need one of you to come up with regexes.

http://kangax.github.io/html-minifier/

**Comment by gertcuykens** [comment]
never mind `--strip` does seem to satisfy https://developers.google.com/speed/pagespeed/insights/

**Comment by Sergey-Kolesnikov** [comment]
```javascript
var gulp = require('gulp'),
    htmlmin = require('gulp-htmlmin');

gulp.task('minify', function () {
    gulp.src('./src/*.html')
        .pipe(htmlmin({
            "caseSensitive": true,
			"customAttrAssign": [
				{"source":"\\$="}
			],
			"customAttrSurround": [
				[ {"source": "\\({\\{"}, {"source": "\\}\\}"} ],
				[ {"source": "\\[\\["}, {"source": "\\]\\]"}  ]
			],
			"minifyJS": true,
			"minifyCSS": true
        }))
        .pipe(gulp.dest('./dist'))
});
```

**Comment by deadlyfingers** [comment]
I got the following 'htmlmin/gulp-html-minifier' options to optimise a vulcanized Polymer html file. 
(But I didn't use any custom attribute surrounds.)
```
.pipe(htmlmin({
      minifyCSS: true,
      collapseWhitespace: true,
      collapseInlineTagWhitespace: true,
      removeComments: true,
      removeCommentsFromCDATA: true,
      caseSensitive: true,
      customAttrAssign: [/\$=/]
}))
```

**Comment by robdodson** [comment]
Related: https://github.com/PolymerElements/polymer-starter-kit/pull/645

**Comment by LRagji** [comment]
@kolesnikof I know i am really late into this post but i really need your help to understand what the following 2 lines do... 

 customAttrAssign: [{"source":"\\$="}],
 customAttrSurround: [
              [ {"source": "\\({\\{"}, {"source": "\\}\\}"} ],
              [ {"source": "\\[\\["}, {"source": "\\]\\]"}  ]
          ]

they are causing big problem if i have html in js files ... and i cant find any documentation on it any help is appreciated

**Comment by robdodson** [comment]
I think those two lines are defining the delimiters for different binding syntax.

```html
<x-foo bar$="[[baz]]">
```

Will bind the `bar=""` HTML attribute to the value of `baz`.

```html
<x-foo bar="{{baz}}">
<!-- or -->
<x-foo bar="[[baz]]">
```

Will bind the DOM instance of `x-foo`'s `bar` JavaScript property to the value of `baz`.
`{{ }}` is used for two-way bindings.
`[[ ]]` is used for one-way bindings.

**Comment by LRagji** [comment]
@robdodson  Thanks for the reply and i am big fan of the Polycast series, i love the simplicity format, and the ease in which you explain polymer to dev folk's.....

Now coming back to the problem: I am still using Polymer 1.X and i have the exact same minification task it runs completely fine until it hits HTML tags in the *.js files, when i remove those 2 lines from the task it runs perfect but i dont know if i am silently breaking anything inside...
EG:
something.js 
var text="<iron-ajax id='fireLaser'></iron-ajax>"
Throws error with this minifcation lines enabled 'Unknown token' any idea why this happens?

Also looking at the regex it looks its trying to match {{}} or [[]] pattern not sure why we have '(' at char position 2 in it "\({\{" is that a typo?

**Comment by robdodson** [comment]
I think some of your comment got gobbled by github's markdown parser.

To clarify, are you just running the regular `polymer build` command to bundle up your site?

**Comment by LRagji** [comment]
Fixed the comment but i did find the problem old version of html-min was causing it,
Just for info i am using custom pipeline with polymer-build for vulcanisation piped into html-min to minify the files; i am still scratching my head how to get polymer-build to minify the whole thing...

**Comment by robdodson** [comment]
I feel like historically we've often run into issues with html minfiers and in the past I've avoided them. @justinfagnani or @FredKSchott, do either of you know if polymer build provides html minification these days or if there's an approved minifier?

**Comment by justinfagnani** [comment]
There's an HTML minifier built into the CLI. We use fairly conservative settings by default.
