### ISSUE TITLE
suggestion: improve porting help

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#880]
This is more about the core and paper elements that are based on polymer than polymer itself.

I recently had a problem with upgrading from 0.4.x to 0.5.x.
We were using the paper-item element, and using the label attribute to set the text of the item. When we did the upgrade the label text disappeared and it took an inordinate amount of time to figure out that I needed to move from :

```
<paper-item label="this item"></paper-item>
```

to :

```
<paper-item>this item</paper-item>
```

I notice that the docs for paper-item show an example which shows this method, but the 'Attributes' list seems to still show the 'label'. Perhaps there's some other factor at work here, but anyway, I kind of feel like there could be more done in the docs to help the user spots these problems.

Some ideas :
1. Perhaps there could be a section on upgrading for each element, when the person doing the upgrade makes changes that are clearly going to effect people using the element.
2. It might also be possible to add code (for a single version) only that outputs an error/warning when the user uses some deprecated attribute/feature.
3. The simplest thing is to perhaps have a RELEASE_NOTES.md file in each element's github repository.

What do you think?

**Comment by davidmaxwaterman** [comment]
FWIW, <https://github.com/Polymer/paper-item/issues/24>

**Comment by ebidel** [comment]
We've been called out breaking changes on the blog. https://blog.polymer-project.org/#0-5-1_paperitem

In the past, deprecated element APIs have also thrown console warnings. It's possible this particular one was missed or not possible to warn about.

Full release notes are always at https://github.com/Polymer/polymer/releases.

Re: docs, I don't see where `label` is still mentioned. https://www.polymer-project.org/docs/elements/paper-elements.html#paper-item. Can you point me to where you're seeing that?

**Comment by davidmaxwaterman** [comment]
OK, if you're happy with that. I just note that they didn't work for me, so it's a data point.

I find it a bit curious to see the elements having release nots on Polymer/polymer...I would be expecting them to be separate from polymer itself.

> Re: docs, I don't see where label is still mentioned

I don't either ....*now*... but it was definitely there this morning :/ I used Google to get there, searching for paper-item. I tried to search the git history in case someone was playing with my mind, but no changes for a while...I'm left with the assumption that it was cached or some cdn thing was out of date :/

I'm not sure why, but I don't find the blog is a satisfactory method. I'd almost prefer someone open an issue on github for each such change - I'm much more likely to see it there.

Anyway, up to you...

Max.

**Comment by ebidel** [comment]
I think we're still trying to figure out the best way to get people updates. A release log per element is a maintenance nightmare, but a single changelog of all Polymer stuff is no good either. For now, I think we're settling on the blog posts as a way to announce breaking changes. Of course, not everyone sees those posts either so it's tricky :\

**Comment by arthurevans** [comment]
Hey Max,

I agree we haven't found the right balance yet. I wonder if it would be easier if we had a living release notes document on the site, so it was closer to the docs, at least. We should probably be two or three sets of release notes -- separating the element release notes from the Polymer core notes definitely makes sense based on the way we've split the docs. We could conceivably split the release notes out for each element set, but I don't know if it'd be helpful at present, because there are a lot of interdependencies. (For example, an issue you're seeing in paper-dropdown could be related to a change in core-dropdown or core-overlay.)

**Comment by davidmaxwaterman** [comment]
I was looking at this :

<https://www.polymer-project.org/docs/elements/paper-elements.html#paper-dropdown-menu>

and the label attribute applies to the paper-dropdown-menu, not to the paper-item, so the error is mine. Sorry about that :)
