### ISSUE TITLE
Suggestion for Polymer blog

### ISSUE THREAD

**Issue by mateusortiz** [Polymer/docs#881]
Would not it be better in the Polymer blog, leave only the articles with the title and a brief introduction to the article, and when you click open the whole article?
This makes it easy to find the articles.

cc // @robdodson @arthurevans @addyosmani

**Comment by arthurevans** [comment]
Yeah, it is a little hard to navigate. I think we should either do this and/or add a TOC so you can easily find previous posts. @tjsavage, what say you?

**Comment by mateusortiz** [comment]
I have some ideas to do this, I can do :smile:

**Comment by tjsavage** [comment]
definitely, i think that makes sense - it looked weird when there were only 2-3 articles but now that we've got a good amount of content up let's do it. @mateusortiz - absolutely, happy to look at a PR on github.com/polymer/blog!

**Comment by mateusortiz** [comment]
I made some changes, I think so is easier to navigate, I will still improve some things.
https://github.com/Polymer/blog/pull/28

**Comment by ebidel** [comment]
Thanks! Closing this in favor of https://github.com/Polymer/docs/issues/881

**Comment by mateusortiz** [comment]
:smile:
