### ISSUE TITLE
add observer example with auto-binding

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#885]
https://www.polymer-project.org/docs/polymer/polymer.html

This works

```html
            Object.observe(myTemplate, function(c) {
                c.forEach(function(change) {
                    if (change.name === 'added') {
                      document.querySelector('core-localstorage').save()
                    }
                })
            }) 
```

But I can't figure out how to do it the polyfil way?

```html
            var observer = new PathObserver(myTemplate, 'myTemplate.added');
            observer.open(function() {
                console.log('test')
                document.querySelector('core-localstorage').save()
            })
```

Doesn't do anything, where do I need to put it?

**Comment by arthurevans** [comment]
I think your path needs to be relative to the object being observed, so it should be `'added'`, not `'myTemplate.added'`. This is what's shown in the README:

https://github.com/polymer/observe-js

(Note that the path is `'foo.bar'`, not `'obj.foo.bar'`.)

That said, I have very little experience with using observers directly. If you find an issue, you should probably file it on the observe-js polyfill repo.

**Comment by gertcuykens** [comment]
ok thanks
