### ISSUE TITLE
The docs of transitions doesn't generate.

### ISSUE THREAD

**Issue by hiyjeain** [Polymer/docs#886]
Overview: 
The docs of transitions doesn't generate.

Description:
I found that the doc comment of transitions (such as hero-transition) is well written in its html file. But I can not find such pages on the document site(No result by searching either). But the page of core-animated-pages (https://www.polymer-project.org/docs/elements/core-elements.html#core-animated-pages) mentions that "See the individual transition's documentation for specific details." I think this is an issue.

**Comment by arthurevans** [comment]
Thanks for the report. This is definitely a bug. We're working on documentation tool improvements that should fix this for 0.8, but I don't know whether it'll be possible to back-port those fixes for 0.5.

**Comment by arthurevans** [comment]
@robdodson It looks like the new tools don't handle these transition elements. Not sure how big an issue it might be to support these?

**Comment by arthurevans** [comment]
Not an issue in the 1.0 element catalog: https://elements.polymer-project.org/elements/neon-animation?active=hero-animation and legacy docs will not be updated.
