### ISSUE TITLE
Change elements demo links to components demo.html and create new doc button to go back.

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#892]
The following two links should be considered the most important pages of the polymer website

https://www.polymer-project.org/components/core-elements/demo.html
https://www.polymer-project.org/components/paper-elements/demo.html

Yet there are almost completely hidden from all other pages. 

Consider create a new infrastructure where each `DEMO` button loads the demo from the previous links like this:

https://www.polymer-project.org/components/core-elements/demo.html#...

And include a `DOC` button on that page to go back to:

https://www.polymer-project.org/docs/elements/core-elements.html#...

**Comment by arthurevans** [comment]
@robdodson @ebidel What do y'all think of this?

Definitely feels like the link should go both ways. Currently, though, the core-elements/paper-elements demos don't include all of the sub-demos for the more complicated elements, so they're less useful than the standalone demos.

**Comment by gertcuykens** [comment]
For the ones that are missing just keep the standalone demo, but the other ones should link to each other.

It is much more friendly for beginners that don't know yet what they are looking for. You can switch allot faster between demos and compare them.

**Comment by gertcuykens** [comment]
The 2 main demo pages should also include a link to each other to switch between core and paper.

In the end you need to be able to go through every paper and core element in less then a minute :) and more important after you went through all of them you should be able to find the one back you liked the most even faster. Beginners do not have much patience, they want there ellement right away or they just stick with html 4 :P

**Comment by ebidel** [comment]
I agree those are much friendlier to navigate the demos. It's not a terrible idea to deep link directly into the sampler demos rather than the standalone ones.

I'm not sure how up to date the samplers are though. If we're continuing to update them as new elements come online, I'd say we go for it. The current demo button already opens in a new tab.

**Comment by katejeffreys** [comment]
To help me manage the issues in the docs repo, I will close this issue in 7 days. If you need it to stay open for some reason, please comment to that effect within 7 days.

**Comment by arthurevans** [comment]
This is obsolete. Closing.
