### ISSUE TITLE
paper-dropdown doesn't update it's scroller div

### ISSUE THREAD

**Issue by AminElNaggar** [Polymer/docs#895]
I have this snippit

    <paper-menu-button class="ticketMenu">
      <paper-icon-button icon="more-vert" noink></paper-icon-button>
      <paper-dropdown class="dropdown no-padding" halign="right">
        <div class="menu">
          <paper-item on-tap="{{toggleSelectThisTicket}}">Info</paper-item>

          <template if="{{!ticket.assignee}}">
            <paper-item on-tap="{{assignThisTicket}}">Assign</paper-item>
          </template>

          <template if="{{ticket.status == 'started'}}">
            <paper-item on-tap="{{resolveThisTicket}}">Resolve</paper-item>
          </template>
        </div>
      </paper-dropdown>
    </paper-menu-button>

If any of the two `if statement`s were `true` at initialization, and then later on were `false` thereby removing the web-component inside it actually removes it from DOM which is good, but the problem is that inside `paper-dropdown`'s shadow there is a `div` with class `scroller` that seems to hardcode it's style based on it's content at initialization.

How do I force it to recalculate height?

just for a visual, before and after:

![screen shot 2015-02-13 at 11 00 31 am](https://cloud.githubusercontent.com/assets/8960297/6190399/a1940f84-b36f-11e4-9310-425268dfbf48.png)

![screen shot 2015-02-13 at 11 00 40 am](https://cloud.githubusercontent.com/assets/8960297/6190404/a6b451d6-b36f-11e4-9414-eb8ba0d12a8a.png)

**Comment by arthurevans** [comment]
Moved to https://github.com/Polymer/paper-dropdown/issues/13
