### ISSUE TITLE
What is logNameValue in this fragment of example code?

### ISSUE THREAD

**Issue by aegor** [Polymer/docs#897]
It is convention over configuration? In any case, 
this example not fired logNameValue: http://codepen.io/aegor/pen/xbYpZJ

```
<polymer-element name="x-form">
  <template>
    <input type="text" id="nameInput">
  </template>
  <script>
    Polymer('x-form', {
      logNameValue: function() {
        console.log(this.$.nameInput.value);
      }
    });
  </script>
</polymer-element>
```

**Comment by arthurevans** [comment]
You're right, that example is really confusing. It's just supposed to show that you can access children by ID using the `this.$` object. As written, nothing calls this method. We'll replace this with a better example.
