### ISSUE TITLE
XTags article has missing elements.

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#904]
![screen shot 2015-02-22 at 1 22 26 pm](https://cloud.githubusercontent.com/assets/238208/6320560/dd574ed2-ba95-11e4-87d9-18355609eaf2.png)

**Comment by ebidel** [comment]
pingy ping

**Comment by robdodson** [comment]
I was just looking at this, this morning actually :) I think I'm going to have to rewrite the article (it uses polymer-ui-ratings and an old version of x-tags). It should probably be updated to Polymer 0.8, XTag 1.0, and vanilla WC. Maybe I can sneak it in this week

**Comment by katejeffreys** [comment]
No longer seems relevant. Closing.
