### ISSUE TITLE
0.8 - Script to bower update each version directory

### ISSUE THREAD

**Issue by ebidel** [Polymer/docs#910]
When we have multiple version dirs, it'll be important to have an automated solution that updates each dirs components.

**Comment by addyosmani** [comment]
Have we decided if we're going to use a major-version-only versioning strategy vs. every-version? i.e

/0.8/ will always be updated for anything that falls in 0.8.x vs
/0.8.1/
/0.8.2/ etc.

Assume we're just doing 0.8 and 0.5 for now.

**Comment by ebidel** [comment]
I envisioned only major versions. Not sure if we can scale a anything else.

**Comment by addyosmani** [comment]
Major versions SGTM.

**Comment by arthurevans** [comment]
Minimal but functional version exists:

https://github.com/Polymer/docs/blob/master/scripts/update_bower.sh

Closing this unless someone wants to get fancy.
