### ISSUE TITLE
Move sass/elements to 0.5 dir

### ISSUE THREAD

**Issue by robdodson** [Polymer/docs#914]
I was wondering if it makes sense to take everything in /sass/elements and move it to 0.5/sass/elements? @ebidel

**Comment by ebidel** [comment]
I left all the /sass alone because it can live on its own and doesn't need to be version aware.

**Comment by robdodson** [comment]
I was imagining that some of the elements might not end up in 0.8 land if they get replaced, like `site-banner` in favor of `core-toolbar` or `core-scroll-header-panel`.

**Comment by addyosmani** [comment]
I'm :+1: on a move.

**Comment by arthurevans** [comment]
Given plans to replace the current infrastructure, we're not going to do this at this point.
