### ISSUE TITLE
paper-action-dialog

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#921]
Sometimes you really need to be sherlock homes to find hidden undocumented properties on a completely different page. Can you guess where I found this

``` html
<paper-action-dialog backdrop autoCloseDisabled layered="false">
```

definitely not here haha :p 
https://www.polymer-project.org/0.5/docs/elements/paper-elements.html#paper-action-dialog

**Comment by ebidel** [comment]
For mixin elements, we don't have a good solution to show inheirted properties. However, that page (https://www.polymer-project.org/0.5/docs/elements/paper-action-dialog) does link to https://www.polymer-project.org/0.5/docs/elements/paper-dialog-base.html which has the info.

**Comment by gertcuykens** [comment]
Hmm not sure if the link contains everything, let me check it later. It has most but not everything

**Comment by gertcuykens** [comment]
autoCloseDisabled found
layered found
backdrop not found?

**Comment by gertcuykens** [comment]
correction found all of them
