### ISSUE TITLE
Missing id for second app-globals example

### ISSUE THREAD

**Issue by MeTaNoV** [Polymer/docs#924]
In the last examples of the Supporting Global Variables passing values via Attributes, the declaration of app-globals is missing its globals id.

`<app-globals id ="globals" "firstname="Addy" lastname="Osmani"></app-globals>`

instead of:

`<app-globals firstname="Addy" lastname="Osmani"></app-globals>`

**Comment by addyosmani** [comment]
Fixed. Thanks for noticing the issue!
