### ISSUE TITLE
Each element should have there own style and class summary section in  documentation

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#930]
``` log
Atributes:
- ...

Properties:
- ...

Event:
- ....

Class:
- content
- ....

Style /deep/:
- core-dropdown-menu 
- core-dropdown
- ... 
```

I know you all want to push everything to production as fast as possible but it ain't over until the fat lady sings and the fat lady does not have the complete set of lyrics yet.

**Comment by ebidel** [comment]
We've got some standard doc practices coming with the 0.8 update.

**Comment by katejeffreys** [comment]
Standards now applied in webcomponents.org Polymer elements. Closing this.
