### ISSUE TITLE
Broken links on Single Page App article

### ISSUE THREAD

**Issue by indolering** [Polymer/docs#931]
There are several broken links on the [SPA article](https://www.polymer-project.org/articles/spa.html) (`polymer-project.org/articles/spa.html`).

* final.html: `https://github.com/Polymer/docs/blob/master/articles/demos/spa/final.html`
* elements.html: `https://github.com/Polymer/docs/blob/master/articles/demos/spa/elements.html`
* app.js: `https://github.com/Polymer/docs/blob/master/articles/demos/spa/app.js`
* styles.css: `https://github.com/Polymer/docs/blob/master/articles/demos/spa/styles.css`

**Comment by ebidel** [comment]
These have all been fixed in master. We're waiting on a push of the site.

https://raw.githubusercontent.com/Polymer/docs/master/0.5/articles/spa.md
