### ISSUE TITLE
Demo and download not available

### ISSUE THREAD

**Issue by Neill83** [Polymer/docs#935]
Hi there!

The download and demo buttons are no longer available for all widgets.

Thanks.

**Comment by ebidel** [comment]
@robdodson we lost this in the Great Element Doc Migration

**Comment by robdodson** [comment]
yep working on it

**Comment by robdodson** [comment]
see #938

**Comment by ebidel** [comment]
Fixed and pushed.

**Comment by Neill83** [comment]
:+1:  Thanks guys
