### ISSUE TITLE
Breakage in hosted links to polyfills & library

### ISSUE THREAD

**Issue by addyosmani** [Polymer/docs#936]
Re: https://twitter.com/tjmortimer1989/status/575287647158988800

I've updated the links in master to point to the latest versions of the polyfills & Polymer over in https://github.com/Polymer/docs/commit/c7762491ad9e9d7e327e36e25c92d7ef2228d966. 

We do recommend folks don't link up or rely on these unless for debugging, but this issue is to track whether or not we want to setup symlinks/redirects for the old paths to the new ones to avoid further breakage.

cc @ebidel

**Comment by ebidel** [comment]
You should use `{% polymer_version_dir % }` instead of hard coding 0.5. That'll keep it up to date with the version in the URL.

**Comment by addyosmani** [comment]
Updated in https://github.com/Polymer/docs/commit/e3280ec42fc4adf375a929b3ecd0033ab4bccbf4. I'm down with us forcing people to update their URLs. We may need to do a PSA. I mean, this was never really supported as a long-term thing anyway.

**Comment by ebidel** [comment]
@tjsavage should we include this info on the blog or other?

**Comment by tjsavage** [comment]
Blog and tweet seems right. I'll draft up a quick post.

**Comment by ebidel** [comment]
Plenty of people already have noticed this. We're also working on getting the download/demo buttons back on the element pages: https://github.com/Polymer/docs/issues/935

**Comment by addyosmani** [comment]
@ebidel I want to say we’ve done sufficient work on getting this fixed that this issue can be closed. Did you want to keep it around for tracking download/demo buttons back or is there a separate issue for that?

**Comment by ebidel** [comment]
Rob already got those back in.
