### ISSUE TITLE
Some more broken URLs

### ISSUE THREAD

**Issue by addyosmani** [Polymer/docs#943]
From Elliot:

Polymer docs don't seem to work for me anymore. https://www.polymer-project.org/ click "Elements" in the top right, click Demo or Docs.
clicking the picture seems to take me to an element. 

He also commented on Google search links being busted but we know this will organically fix itself.

**Comment by addyosmani** [comment]
We might want to do a quick URL audit to catch anything else that no longer resolves correctly.

**Comment by davidmaxwaterman** [comment]
Is there also some issue with the building of the pages?

0.5/articles/unit-testing-elements.md
<https://www.polymer-project.org/0.5/articles/unit-testing-elements.html>
"![ profile pic]( “”) By Published"

or is it just because that's not 'ready' yet?

**Comment by addyosmani** [comment]
Confirmed that I'm seeing breakage there too. @tjsavage we might want to factor in a round of general post-versioning fixes for the current sprint.
