### ISSUE TITLE
Links from GitHub repos are broken

### ISSUE THREAD

**Issue by steren** [Polymer/docs#946]
Go to https://github.com/polymer/core-ajax
Click on the element link in the README file, it arrives on https://www.polymer-project.org/0.5/docs/elements/#core-ajax
Which is not the page of the element.
I expect to land at https://www.polymer-project.org/0.5/docs/elements/core-ajax.html

**Comment by ebidel** [comment]
@robdodson @azakus is there a way we can mass update the element READMEs? I seem to recall we did that at some point using some magic Daniel thing :)

**Comment by steren** [comment]
Fixing the landing page itself may be also an idea, as I noticed that links from Google search [polymer core-selector] had the same issue: see http://imgur.com/dPockLs
The second result (https://www.polymer-project.org/0.5/docs/elements/#core-selector) is actually broken

**Comment by arthurevans** [comment]
@robdodson -- instead of redirecting core-elements.html / paper-elements.html to the generic page, could we replace it with a JS redirect that takes the hash and dynamically redirects `/elements/core-elements.html#hash` to `/elements/{{hash}}.html`?

**Comment by robdodson** [comment]
@arthurevans that seems possible

**Comment by addyosmani** [comment]
Ran into this issue a few times this week. I like Arthur’s suggestion about the improved redirects :)

**Comment by ebidel** [comment]
@azakus Do you have an easy way to update the repo READMEs like last time?

**Comment by azakus** [comment]
Not particularly. Each time has been a mad dash of "checkout all the repos, run a script, commit them all". If you can give me a "make this look like that" level of requirement, I can probably cook something up.

**Comment by ebidel** [comment]
Make this: 

    [https://www.polymer-project.org/0.5/docs/elements/#core-ajax](component page)

Look like this:

    [https://www.polymer-project.org/0.5/docs/elements/core-ajax.html](component documentation)

:)

**Comment by azakus** [comment]
Should be done now.

**Comment by ebidel** [comment]
Sweet thanks Dan!
