### ISSUE TITLE
Overlay problem in attributes and events

### ISSUE THREAD

**Issue by oswaldofreitas** [Polymer/docs#947]
![captura de tela 2015-03-12 as 13 35 05](https://cloud.githubusercontent.com/assets/10772835/6622678/dfb2c5b4-c8bc-11e4-9355-90e78b36ad5b.png)

**Comment by arthurevans** [comment]
@robdodson PTAL?

**Comment by robdodson** [comment]
yeah i don't think this is a new issue (those components are the same from the old site). I can work on this

**Comment by katejeffreys** [comment]
To help me manage the issues in the docs repo, I will close this issue in 7 days. If you need it to stay open for some reason, please comment to that effect within 7 days.

**Comment by arthurevans** [comment]
Old bug from a previous version of the site. Can definitely be closed.
