### ISSUE TITLE
Wrong global variables example

### ISSUE THREAD

**Issue by oswaldomilet** [Polymer/docs#959]
Please, see [this](http://stackoverflow.com/a/24876397/2750721) answer to fix the example showed in [Supporting global variables](https://www.polymer-project.org/0.5/docs/polymer/polymer.html#global) of API Developer Guide page.

Correct way to exchange data between instances of app-globals:
```
<polymer-element name="app-globals">
  <script>
      (function() {
        var data = {
            firstName: 'John';
            lastName: 'Smith';
        }

        Polymer({
          ready: function() {
            this.data = data;
          }
        });
      })();
  </script>
</polymer-element>
```

**Comment by robdodson** [comment]
That's a good point. @arthurevans the tl;dr is that since we're using strings in the original example:

```
<polymer-element name="app-globals">
  <script>
  (function() {
    // these variables are shared by all instances of app-globals
    var firstName = 'John';
    var lastName = 'Smith';

    Polymer({
      ready: function() {
        // copy global values into instance properties
        this.firstName = firstName;
        this.lastName = lastName;
      }
    });
  })();
  </script>
</polymer-element>
```

If those strings ever update, nobody gets notified because they're copied as values instead of by reference. Using an object to hold all of the data is a better approach because if it updates, everyone's reference gets updated too

**Comment by arthurevans** [comment]
Yep, I think the idea there was creating non-writable set of global defaults, but it doesn't really match the rest of the section. Will fix.
