### ISSUE TITLE
How to Unit Testing Polymer Elements in a more typical app structure?

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/docs#961]
The usual app structure is :

```
app/
bower.json
package.json
Gruntfile.js
README.md
test/
```

The tests for the entire app are in test/ and the _source_ for the app is in app/. It is typical for there to be no generated files in app/ at all, and certainly no tests.

To test, we cd to the root of the project and run `grunt test` or something like that. This will run all the tests, and I wish for this to include the tests on the polymer elements (aside, is there a grunt task for wct?).

Reading the guide :

https://www.polymer-project.org/0.5/articles/unit-testing-elements.html

it is unclear how to adopt wct into the above app directory hierarchy. Perhaps something could be added to help?

In the meantime, if someone has some pointers to help me do so, I'd be grateful :)

**Comment by ebidel** [comment]
@addyosmani

**Comment by davidmaxwaterman** [comment]
FWIW, I think I managed it. Most clues were found in the [Grunt](https://github.com/Polymer/web-component-tester#grunt) part of the README in wct's git repo. I ended up not using the command line tool, but using grunt instead - which I wanted to do anyway.

However, I still kind of feel like more people will be using Polymer in their applications rather than developing and publishing elements independently from each other, and so it'd be more useful to have a section on that in the docs.

In case it helps anyone, I ended up with this in my Gruntfile :

```
    'wct-test': {
      local: {
        options: {
          // options listed here : <https://github.com/Polymer/web-component-tester/blob/master/runner/config.js>
          remote: false,
          root: '.', // else is .. (used for testing independent web components rather than in an app
          //persistent: true, // keeps the browser open - useful for debugging wct
          suites: [
            'test/elements' // it seems to use subdirectories, but we could list them here, or have more than one 'suite'?
          ]
        },
      },
      remote: {
        options: {remote: true},
      },
      chrome: {
        options: {browsers: ['chrome']},
      },
    }
```

**Comment by addyosmani** [comment]
Thanks for bringing this up, David. cc @nevir as an FYI

As you discovered, web-component-tester includes sample configurations for folks that want to use it with a build system or task runner like Grunt or Gulp. We could point them either directly to the docs in WCT that cover this, or attempt to document these folks in more detail in the unit testing guide.

My preference would probably be just pointing folks to https://github.com/Polymer/web-component-tester#grunt (etc), mostly because there shouldn’t be a great deal more involved in using WCT with one of these tools. 

Was there something in particular you wanted to see covered or was the suggestion just to link out more clearly to Gulp/Grunt config?

**Comment by davidmaxwaterman** [comment]
I suppose it was more about my presumption that most people wouldn't be making a big set of elements for publishing and so wouldn't be doing testing this way. I realise that the paper and core elements are done this way so it's fine for that, but I would presume most people would be making apps/web sites, and would not want the tests to be mixed in with their app source code. So, I would say that the whole document would be better to be rewritten based on an app structure.

Of course, I could be wrong with my initial assumption, and most people are developing elements outside their apps - but I don't think so ;)

Anyway, you *do* already have a link to wct documentation in this paragraph :

```
Note: While not covered in this guide, the WCT tool has Gulp and Grunt integration as well as support for testing both local and remote browsers. For detailed information on how to use these features, see the WCT >>>documentation.<<<
```

and that basically has all that is needed. So, if you consider that to be enough, then we're done. I might suggest that it be made more prominent though...

**Comment by nevir** [comment]
Related: we would probably do well to set up a seed-app repo, along the same lines as [seed-element](https://github.com/PolymerLabs/seed-element)

**Comment by addyosmani** [comment]
Good idea @nevir!. 

@robdodson This seems like something that could also be useful for the Polymer generator. I know it has support for WCT now - does it handle deps using a different directory structure than the typical seed-element now?

**Comment by robdodson** [comment]
The default generator `yo polymer` will spit out an app scaffold (seed-app
if you want to call it that).

app/
  test/
  elements/
  scripts/
  etc...
bower.json
package.json
node_modules/
bower_components/

There is a sub generator, `yo polymer:seed` which will spit out the seed
element structure

x-foo.html
x-foo.css
test/
bower.json
package.json
etc...

Addy - I thought you were looking into creating a Web App Starter Kit.
Would that be a better place for seed-app to live, vs spinning up another
repo?

**Comment by davidmaxwaterman** [comment]
really? test/ is inside app/? How weird is that...I just tried it and it is indeed in app/ - things have changed since I used yo to start a polymer app.

Is there some rationale for putting it in there? I've always been told that only app files go into app. It'll take some getting used to, for sure.

Well, whatever, that's definitely the best thing to use as an example.

**Comment by nevir** [comment]
Either approach should be totally ok (personally I prefer test/ at the top
level too)

**Comment by davidmaxwaterman** [comment]
Agreed, it'd be great even with app/test/. Good to know about the new generator too.

**Comment by addyosmani** [comment]
I agree either approach should be better. On Rob's comment: absolutely! We are planning a new Polymer Starter Kit and having strong defaults for app-level unit testing is one of our goals.

**Comment by robdodson** [comment]
I'm fine with moving test out of app and to the top level for the app scaffold (or if someone wants to submit a PR I will think they're a really cool person).

**Comment by katejeffreys** [comment]
To help me manage the issues in the docs repo, I will close this issue in 7 days. If you need it to stay open for some reason, please comment to that effect within 7 days.
