### ISSUE TITLE
FOUC on elements page in IE11

### ISSUE THREAD

**Issue by garlicnation** [Polymer/docs#962]
In IE11 on windows 8.1, navigating between paper elements results in a FOUC and a reset of the scroll position of the element picker.

**Comment by ebidel** [comment]
@robdodson?

**Comment by robdodson** [comment]
I'll take a look at this today

**Comment by robdodson** [comment]
I just looked in VirtualBox and the FOUC and resetting scroll position are not that different from the current experience in Chrome. Here's a short video: https://drive.google.com/file/d/0B3bHK5D2_zxES1pHdnZCOVlxWjg/view?usp=sharing

It's not a perfect experience, I'd prefer 0 FOUC, but it's kinda intrinsic to the way we're generating the element pages

**Comment by arthurevans** [comment]
Closing 0.5 docs bugs, we're not going to updates these pages further.
