### ISSUE TITLE
polymer-project.org/webcomponents.js is broken

### ISSUE THREAD

**Issue by garlicnation** [Polymer/docs#963]
This is a pseudo-canonical location for many example issues. Can this link be updated to work, especially since the Polyfills are moving to their own release cadence and are unlikely to include major breaking changes going forwrd.

**Comment by ebidel** [comment]
We made this one work: https://www.polymer-project.org/0.5/webcomponents.js

I suppose we put back the unversioned URL for wc.js since, as you say, it will churn less.
