### ISSUE TITLE
Element landing page layout issue on narrow viewport

### ISSUE THREAD

**Issue by davenotik** [Polymer/docs#967]
Layout is off and page unreadable when browser window is narrow-ish.

Screenshot: http://d.pr/i/1kEGr

**Comment by addyosmani** [comment]
@ebidel Hope some more details are useful. This seems to be an issue with both the screenshots and the heading text in the same area. e.g, hide the thumbnails in narrow viewport and you'll see this:

![screen shot 2015-03-20 at 10 49 29](https://cloud.githubusercontent.com/assets/110953/6750096/d9a0c26a-ceee-11e4-978f-48fb09a85300.png)

**Comment by arthurevans** [comment]
This landing page is no longer in the nav, so closing.
