### ISSUE TITLE
Single Page App: AJAX Not Loading Content in EG. App

### ISSUE THREAD

**Issue by PushkaCom** [Polymer/docs#977]
So.. the AJAX demo isn't working - and I have the same setup on a web server of mine.. but it's acting in the same way ..

https://www.polymer-project.org/0.5/articles/demos/spa/example-ajax.html
It just says "loading" forever.. 

Has there been some update that has broken the AJAX function - or is there some modification to "vulcanized.html" that needs to be made or something?

**Comment by ebidel** [comment]
This is fixed in master.

**Comment by PushkaCom** [comment]
Ah ok - I must have had some other error - 
For anyone else finding this page - I have a working demo available here: http://pushka.com/spa/
Thanks for the awesome work~~
