### ISSUE TITLE
url broken core-icon elements

### ISSUE THREAD

**Issue by mateusortiz** [Polymer/docs#983]
The url of demos of core-icon is broken, as you can see in gif:
![GIF](http://cl.ly/image/3W0c3v1O1Z0S/polymer-url-broken.gif)

**Comment by ebidel** [comment]
This has been fixed in master but needs a release of core-icon to make it to the site.

https://github.com/Polymer/core-icon/blob/master/core-icon.html#L51

**Comment by mateusortiz** [comment]
Oh sorry @ebidel
